(function(G){
 "use strict";
 const V=G.campaign.Validation,M=G.editor.MapAuthoring;
 function conditions(c){V.assert(c&&[null,"PLAYER","ZEON","NEUTRAL","WILDERNESS"].includes(c.controller)&&Array.isArray(c.storyKeys)&&c.storyKeys.every(V.validId),"invalid static-map conditions");}
 function create(id,width=30,height=30,c={controller:null,storyKeys:[]}){V.assert(V.validId(id),"invalid map ID");M.shift(width,height,"EAST",1);V.assert(width>=30&&height>=30,"minimum map dimensions are 30x30");conditions(c);return{id,name:id,width,height,tiles:Array.from({length:height},()=>Array(width).fill("ocean")),conditions:V.clone(c),approaches:["NORTH","SOUTH"],deployment:Object.fromEntries(["NORTH","SOUTH","EAST","WEST"].map(side=>[side,{positions:{FRONT:[],BACK:[]}}])),specialDeployments:[],requiredPoints:[]};}
 function points(map){return[...Object.values(map.deployment).flatMap(d=>Object.values(d.positions).flat()),...map.specialDeployments,...(map.requiredPoints||[])];}
 function special(spec){V.assert(V.validId(spec.id)&&G.data.COMBAT_FACTIONS[spec.faction],"invalid special identity/faction");const u=spec.unit;V.assert(u&&V.validId(u.id)&&typeof u.name==="string"&&u.name.trim()&&u.name.length<=80,"invalid special unit identity/name");V.assert(u&&G.data.UNIT_TYPES[u.typeId]&&G.data.CLASSES[u.currentClassId],"full special-unit definition required");G.campaign.CharacterValidation.progression(u);V.assert(Array.isArray(spec.equipment)&&spec.equipment.every(id=>G.data.ITEMS[id]?.equipmentSlot),"invalid special equipment");let definitions=[];for(const id of spec.equipment){const item=G.data.ITEMS[id];V.assert(!definitions.some(d=>d.equipmentSlot===item.equipmentSlot)&&G.campaign.EquipmentEligibility.withEquipment(u,item,definitions),"illegal special equipment");definitions.push(item);}return true;}
 function shape(map){
  conditions(map.conditions);V.assert(typeof map.name==="string"&&map.name.trim()&&map.name.length<=80,"map name required (80 characters maximum)");
  V.assert(Array.isArray(map.approaches)&&map.approaches.length===2&&G.systems.DeploymentSystem.opposite[map.approaches[0]]===map.approaches[1],"select an opposing approach pair");
  V.assert(map.deployment&&Array.isArray(map.specialDeployments)&&Array.isArray(map.requiredPoints),"missing authored deployment metadata");
  for(const side of Object.keys(G.systems.DeploymentSystem.opposite))for(const group of ["FRONT","BACK"])V.assert(Array.isArray(map.deployment[side]?.positions?.[group]),"missing deployment group");
  for(const p of points(map))V.assert(p&&M.inside(p,map.width,map.height),"authored point out of bounds");
  for(const spec of map.specialDeployments)special(spec);
 }
 function validate(map,strict=true){if(!map||typeof map!=="object")return{valid:false,errors:["Battle Map required"]};const errors=[];const check=fn=>{try{fn();}catch(e){errors.push(e.message);}};check(()=>{G.systems.BattleTerrainSystem.validate(map);shape(map);V.assert(V.validId(map.id),"invalid map ID");V.assert(Array.isArray(map.approaches)&&map.approaches.length===2&&G.systems.DeploymentSystem.opposite[map.approaches[0]]===map.approaches[1],"select an opposing approach pair");for(const row of map.tiles)for(const value of row)M.validateTile(value);});const used=new Set();for(const side of Object.keys(G.systems.DeploymentSystem.opposite)){for(const group of ["FRONT","BACK"]){const slots=map.deployment?.[side]?.positions?.[group];check(()=>V.assert(Array.isArray(slots)&&(!strict||!map.approaches?.includes(side)||slots.length>=6),"author at least six "+side+" "+group+" spots"));for(const p of slots||[])check(()=>{V.assert(M.inside(p,map.width,map.height),"deployment out of bounds");const key=p.x+","+p.y;V.assert(!used.has(key),"conflicting deployment spots");used.add(key);V.assert(G.systems.BattleTerrainSystem.definition(map,p.x,p.y)?.traversable,"deployment terrain invalid or unresolved");});}}
  const ids=new Set();for(const spec of map.specialDeployments||[])check(()=>{special(spec);V.assert(!ids.has(spec.id),"duplicate special ID");ids.add(spec.id);V.assert(M.inside(spec,map.width,map.height)&&!used.has(spec.x+","+spec.y),"special deployment out of bounds or conflicting");used.add(spec.x+","+spec.y);V.assert(G.systems.BattleTerrainSystem.canOccupy(map,spec.unit,spec.x,spec.y),"special terrain invalid");});return{valid:errors.length===0,errors};}
 function resize(map,edge,amount){const out=V.clone(map),r=M.resize(out,edge,amount,points(out));for(const p of points(out)){p.x+=r.dx;p.y+=r.dy;}out.width=r.width;out.height=r.height;out.tiles=r.tiles;return out;}
 function instantiate(map){const positions={},units=[],ids=new Set(),occupied=new Set();for(const spec of map.specialDeployments){special(spec);V.assert(!ids.has(spec.id)&&!occupied.has(spec.x+","+spec.y),"duplicate special deployment");ids.add(spec.id);occupied.add(spec.x+","+spec.y);V.assert(G.systems.BattleTerrainSystem.canOccupy(map,spec.unit,spec.x,spec.y),"special terrain invalid");const u=V.clone(spec.unit);u.id="special_"+map.id+"_"+spec.id;u.faction=spec.faction;u.status="ACTIVE";u.unassignedLocationId=null;u.stats=G.campaign.CharacterStatsSystem.deriveStats(u,spec.equipment.map(id=>G.data.ITEMS[id]));u.possessions=spec.equipment.map((definitionId,n)=>({instance:{id:u.id+"_gear"+n,definitionId,ownerFaction:u.faction,state:"EQUIPPED",place:{type:"UNIT",id:u.id},assignedUnitId:null}}));positions[u.id]={x:spec.x,y:spec.y};units.push(u);}return{units,positions};}
 G.editor.BattleMapAuthoring={create,conditions,shape,validate,resize,points,special,instantiate};
}(window.GBTRPG));
