(function(G){
 "use strict";
 class DeveloperShell {
  constructor(game){this.game=game;for(const k of ["input","renderer","text","ui","assets"])this[k]=game[k];this.overlay=null;this.document=null;this.terminal=null;this.history=["GODMODE / GREEDISGOOD / DEVMODE"];}
  open(screen){if(this.overlay!==screen)this.overlay?.dispose?.();this.overlay=screen;this.input.clear();}
  close(){this.overlay?.dispose?.();this.overlay=null;this.input.textHandler=null;this.input.capture=null;this.input.clear();}
  screen(title,fields,back=()=>this.close()){const s=new G.editor.PropertyScreen(this,title,fields,back);this.open(s);return s;}
  message(title,lines,back){return this.screen(title,lines.flatMap(line=>this.text.wrap(String(line),72)).map(label=>({label})),back);}
  confirm(title,run,back=()=>this.devMenu()){this.screen(title,[{label:"NO / CANCEL",run:back},{label:"YES / CONFIRM",run:()=>{run();}}],back);}
  editText(label,value,commit,previous){let text=String(value);const finish=()=>{this.input.textHandler=null;this.open(previous);};this.input.textHandler=e=>{try{if(e.code==="Escape"){finish();return;}if(e.code==="Enter"){commit(text);finish();return;}if(e.code==="Backspace")text=text.slice(0,-1);else if(e.key?.length===1&&text.length<512)text+=e.key;}catch(err){screen.error=err.message;}};const screen={update:()=>{if(this.input.consumeAction()==="cancel")finish();},render:()=>{this.renderer.clear();this.ui.page(this.renderer.ctx,label,[...this.text.wrap(text+"_",70),"KEYBOARD TEXT / ENTER COMMIT / ESC CANCEL",...(screen.error?[screen.error]:[])],0);}};this.open(screen);}
  toggleTerminal(){if(this.terminal){this.input.textHandler=this.terminal.previousHandler;this.terminal=null;this.input.clear();return;}this.terminal={line:"",previousHandler:this.input.textHandler};this.input.clear();this.input.textHandler=e=>{if(e.code==="Enter"){const line=this.terminal.line,wasDev=G.core.DeveloperRuntime.devmode;this.history.push("> "+line,G.core.DeveloperRuntime.execute(line));if(wasDev&&!G.core.DeveloperRuntime.devmode){this.overlay?.dispose?.();this.overlay=null;this.terminal.previousHandler=null;this.input.capture=null;}this.history=this.history.slice(-24);this.terminal.line="";}else if(e.code==="Backspace")this.terminal.line=this.terminal.line.slice(0,-1);else if(e.code==="Escape")this.toggleTerminal();else if(e.key?.length===1&&this.terminal.line.length<120)this.terminal.line+=e.key;};}
  update(ms){const global=this.input.queue.findIndex(a=>a==="terminal"||a==="devmenu");if(global>=0){const [a]=this.input.queue.splice(global,1);if(a==="terminal")this.toggleTerminal();else if(!this.terminal&&G.core.DeveloperRuntime.devmode){if(this.overlay instanceof G.editor.MapEditorState)this.overlay.menu();else if(this.overlay)this.close();else this.devMenu();}}
   if(this.terminal){if(this.input.consumeAction()==="cancel")this.toggleTerminal();return true;}if(this.overlay){this.overlay.update(ms);return true;}return false;}
  render(){if(this.terminal){this.renderer.clear();this.ui.window(this.renderer.ctx,0,0,480,360);this.text.draw(this.renderer.ctx,"TERMINAL / KEYBOARD COMMAND ENTRY",8,8,76);this.text.draw(this.renderer.ctx,this.history.join("\n"),8,30,76);this.text.draw(this.renderer.ctx,"> "+this.terminal.line+"_",8,326,76);this.text.draw(this.renderer.ctx,"TOGGLE TERMINAL TO RETURN / ESC CLOSE",8,348,76);}else this.overlay?.render();}
  getDocument(){if(!this.document)this.document=new G.editor.EditorDocument(this.game.campaign,this.game.authoredContent||G.data.AUTHORED_CONTENT);return this.document;}
  devMenu(){if(!G.core.DeveloperRuntime.devmode)return;const campaign=this.game.states.current===this.game.campaignMap;this.screen("DEV MENU / "+(campaign?"CAMPAIGN":"RUNTIME"),[
   ...(campaign?[{label:"EDIT CAMPAIGN MAP",run:()=>this.open(new G.editor.MapEditorState(this,"terrain"))},{label:"EDIT LOCATIONS",run:()=>this.open(new G.editor.MapEditorState(this,"locations"))}]:[]),
   ...(this.game.states.current instanceof G.states.EndDayState&&this.game.campaign.state.resolution?.pendingBattleScenario?[{label:"TEST BATTLE RESULTS",run:()=>this.battleTestResults()}]:[]),
   {label:"EDITOR FILES / SAVE IMPORT EXPORT",run:()=>this.files()},
   {label:"ASSET BROWSER / BATTLE SCENE TOOLS",run:()=>new G.editor.AssetBrowser(this).menu()},
   {label:"GAME STATE",run:()=>this.screen("GAME STATE",[{label:"RESET CURRENT GAME",run:()=>this.confirm("RESET CURRENT RUNTIME?",()=>{this.game.resetCurrent();this.close();})},...(campaign?[{label:"CAMPAIGN RUNTIME TOOLS",run:()=>this.legacyTools()},{label:"TACTICAL MOVEMENT TEST",run:()=>{this.close();this.game.openTactical();}}]:[]),{label:"BATTLE FOUNDATION TEST",run:()=>{this.close();this.game.openBattleFoundation();}},{label:"SPELL / PORTAL LAB",run:()=>{this.close();this.game.openSpellLab();}},{label:"RUN RULE CHECKS",run:()=>{const runtime={godmode:G.core.DeveloperRuntime.godmode,greedisgood:G.core.DeveloperRuntime.greedisgood,devmode:G.core.DeveloperRuntime.devmode};G.core.DeveloperRuntime.reset();let results;try{results=G.debug.runFoundationTests();}finally{Object.assign(G.core.DeveloperRuntime,runtime);}this.message("RULE CHECKS",[results.filter(r=>r.pass).length+"/"+results.length+" PASS",...results.filter(r=>!r.pass).map(r=>r.name+": "+r.error)],()=>this.devMenu());}}],()=>this.devMenu())},
   {label:"DISABLE DEVMODE",run:()=>{G.core.DeveloperRuntime.devmode=false;this.close();}},{label:"CLOSE",run:()=>this.close()}
  ]);}
  battleTestResults(){const c=this.game.campaign,b=c.state.resolution.pendingBattleScenario;
   this.screen("DEVELOPER / TEST BATTLE RESULTS",[...['PLAYER','ZEON'].map(faction=>({label:"TEST "+faction+" WIN",run:()=>{c.applyBattleResult(G.campaign.PlaceholderBattleResolver.result(b,faction,"DEFEATED"));this.close();}})),...b.participants.filter(p=>p.squadId===b.attackingSquadId?b.context.attackerMoving:b.context.defenderMoving).map(p=>({label:p.faction+" RETREATS",run:()=>{c.applyBattleResult(G.campaign.PlaceholderBattleResolver.result(b,p.faction==="PLAYER"?"ZEON":"PLAYER","RETREATED"));this.close();}}))],()=>this.devMenu());
  }
  legacyTools(){
   // Existing campaign tools run in a private view owned by the developer overlay.
   const view=Object.assign(Object.create(G.states.CampaignMapState.prototype),this.game.campaignMap,{stack:[],mode:"map",debugEnabled:true,eventLog:[...this.game.campaignMap.eventLog]});
   view.resources=new G.ui.CampaignResourceUI(view);view.debugMenu();view.list.items=view.list.items.filter(f=>!["RUN RULE CHECKS","BATTLE FOUNDATION TEST","SPELL / PORTAL LAB"].includes(f.label)&&(!(this.game.authoredContent||G.data.AUTHORED_CONTENT)||f.label!=="LOAD TEST SCENARIO"));
   this.open({update:()=>{view.update();if(view.mode==="map")this.devMenu();},render:()=>view.render()});
  }
  files(back=()=>this.devMenu()){const doc=this.getDocument();this.screen("EDITOR FILES / "+(doc.dirty?"UNSAVED CHANGES":"WORKING COPY"),[
   {label:"SAVE WORKING COPY IN THIS BROWSER",run:()=>{const ok=doc.save();this.message(ok?"BROWSER WORKING COPY SAVED":"BROWSER SAVE FAILED",ok?doc.store.workingCopyNotice():[doc.store.error],()=>this.files(back));}},
   {label:"LOAD WORKING COPY FROM THIS BROWSER",run:()=>this.confirm("REPLACE EDITOR DRAFT FROM BROWSER?",()=>{doc.restore();this.files(back);},()=>this.files(back))},
   {label:"WORKING COPY STORAGE DETAILS",run:()=>{const saved=doc.store.read("editor.v1");this.message("WORKING COPY STORAGE",["TYPE: LOCALSTORAGE / KEY: "+doc.store.prefix+"editor.v1","PAGE: "+(window.location?.href||"UNAVAILABLE"),doc.store.error|| (saved?"STORED COPY PRESENT / EXPLICIT LOAD REQUIRED":"NO COPY AT THIS BROWSER / PAGE LOCATION"),...doc.store.workingCopyNotice().slice(2)],()=>this.files(back));}},
   {label:"RELOAD INSTALLED CONTENT INTO EDITOR",run:()=>this.confirm("DISCARD DRAFT / RELOAD INSTALLED SOURCE?",()=>{const source=new G.editor.EditorDocument(G.campaign.createDemo(),this.game.authoredContent||G.data.AUTHORED_CONTENT);doc.import(source.json());doc.dirty=false;this.files(back);},()=>this.files(back))},
   {label:"EXPORT PORTABLE BACKUP / ALL DATA",run:()=>G.editor.EditorFiles.download("shining-farce-editor.json",doc.portable())},
   {label:"EXPORT CAMPAIGN MAP / JSON + REFERENCED MAPS",run:()=>G.editor.EditorFiles.download("campaign-map.json",doc.portable("CAMPAIGN"))},
   {label:"EXPORT BATTLE MAP COLLECTION / JSON",run:()=>G.editor.EditorFiles.download("battle-maps.json",doc.portable("BATTLE_MAPS"))},
   {label:"BATTLE MAP FILES / EDIT / EXPORT",run:()=>this.mapFiles(back)},
   {label:"IMPORT AUTHORED DATA / JSON INTO EDITOR",run:()=>this.importFile(back)},
   {label:"EXPORT SHIPPING INDEX.HTML",run:()=>this.publishPage(back)},
   {label:"EXPORT SHIPPING PACKAGE / ZIP",run:()=>this.publish(back,doc=>{const files=G.editor.ShippingPage.files(doc);G.editor.EditorFiles.download("shining-farce-shipping-maps.zip",G.editor.EditorFiles.zip(files),"application/zip");this.shippingHelp(back);})},
   {label:"EXPORT SHIPPING DATA BLOCK / TXT",run:()=>this.publish(back,doc=>{G.editor.EditorFiles.download("shipping-data.txt",G.editor.ShippingPage.block(doc),"text/plain");this.message("DATA BLOCK DOWNLOAD REQUESTED",["OPEN SHIPPING-DATA.TXT IN NOTEPAD.","COPY ALL TEXT INTO THE AUTHORED MAP ASSETS BLOCK","OF YOUR EXISTING INDEX.HTML, REPLACING THAT BLOCK.","SAVE AND REOPEN INDEX.HTML. THIS IS INERT JSON.","NO SECURITY SETTINGS OR ORIGIN MARKS ARE CHANGED."],()=>this.files(back));})},
   {label:"HOW TO SHIP AUTHORED CONTENT",run:()=>this.shippingHelp(back)}
  ],back);}
  verifyScene(doc,done,back){
   const A=G.editor.BattleSceneAssets,base=doc.data;
   if(!A.externalEntries(base).length)return done(A.readiness(base,{availability:true}));
   const pending=this.screen("VERIFYING CURRENT PNG FILES",[{label:"LOCAL IMAGE LOADS / WAIT OR CANCEL"}],back);
   return A.verify(base).then(result=>{if(this.overlay!==pending)return;if(doc.data!==base)throw Error("EDITOR CHANGED DURING VERIFICATION; TRY AGAIN");return done(result);}).catch(error=>{if(this.overlay===pending)this.message("ASSET VERIFICATION FAILED",[error.message],back);});
  }
  publish(back,produce){const doc=this.getDocument();return this.verifyScene(doc,result=>{if(!result.valid){this.message("SHIPPING REFUSED",result.errors,()=>this.files(back));return;}return produce(doc);},()=>this.files(back));}
  publishPage(back){return this.publish(back,doc=>{G.editor.EditorFiles.download("index.html",G.editor.ShippingPage.page(doc),"text/html");this.shippingHelp(back);});}
  shippingHelp(back){this.message("INSTALL SHIPPING MAPS / MANUAL PLACEMENT",["1 KEEP A PORTABLE JSON BACKUP.","2 EXPORT SHIPPING INDEX.HTML (OR THE ZIP).","3 CLOSE THE GAME AND BACK UP YOUR PROJECT.","4 REPLACE ONLY THE PROJECT'S INDEX.HTML.","5 REOPEN INDEX.HTML IN THE COMPLETE PROJECT.","DOWNLOADS DO NOT INSTALL FILES AUTOMATICALLY.","NO DOWNLOADED JS FILES OR SCRIPT-LIST EDITS.","FOR ONE MAP OR A NEW MAP SET: REPUBLISH INDEX.HTML.","JSON BACKUPS ARE EDITOR DATA, NOT INSTALLED MAPS.","IF WINDOWS BLOCKS HTML, KEEP SECURITY ENABLED.","EXPORT SHIPPING DATA BLOCK / TXT INSTEAD; FOLLOW","ITS INSTRUCTIONS TO EDIT YOUR EXISTING LAUNCHER.","BROWSER SAVES DO NOT CHANGE PROJECT FILES."],()=>this.files(back));}
  importFile(back){const doc=this.getDocument(),done=()=>this.files(back),fail=e=>this.message("IMPORT REJECTED",[e.message,"CURRENT EDITOR DRAFT IS UNCHANGED."],done);G.editor.EditorFiles.import(text=>{try{const plan=doc.prepareImport(text);this.screen("CONFIRM IMPORT / "+plan.kind,[{label:"EDITOR ONLY / PROJECT FILES UNCHANGED"},{label:plan.kind==="DOCUMENT"?"REPLACES THE ENTIRE EDITOR DOCUMENT":plan.kind==="CAMPAIGN"?"REPLACES CAMPAIGN; MERGES INCLUDED MAPS":"MERGES BATTLE MAPS; KEEPS LOCATION REFERENCES"},...plan.conflicts.map(id=>({label:"REPLACE EXISTING MAP ID: "+id})),...G.editor.BattleSceneAssets.readiness(plan.data).errors.flatMap(error=>this.text.wrap("SCENE DRAFT: "+error,70).map(label=>({label}))),{label:"CANCEL / KEEP CURRENT DRAFT",run:done},{label:"CONFIRM IMPORT / REPLACE LISTED IDS",run:()=>{try{doc.applyImport(plan,true);done();}catch(e){fail(e);}}}],done);}catch(e){fail(e);}},fail,done);}
  mapFiles(back){const doc=this.getDocument(),done=()=>this.mapFiles(back);this.screen("BATTLE MAP FILES / STABLE IDS",[...Object.keys(doc.data.battleMaps).map(id=>({label:id+" / "+doc.data.battleMaps[id].name,run:()=>this.screen("BATTLE MAP FILE / "+id,[{label:"EDIT THIS BATTLE MAP",run:()=>this.open(new G.editor.MapEditorState(this,"battle",id))},{label:"EXPORT PORTABLE BATTLE MAP / JSON",run:()=>G.editor.EditorFiles.download(id+".json",doc.portable("BATTLE_MAP",id))},{label:"PUBLISH MAP CHANGES / INDEX.HTML",run:()=>this.publishPage(back)},{label:"DELETE UNREFERENCED BATTLE MAP",run:()=>this.confirm("DELETE THIS MAP FROM THE EDITOR DRAFT?",()=>{doc.deleteBattleMap(id);done();},done)}],done)})),...(!Object.keys(doc.data.battleMaps).length?[{label:"NO MAPS / CREATE FROM A LOCATION OR IMPORT JSON"}]:[])],()=>this.files(back));}
  controls(back=()=>this.close()){const sourceMenu=source=>{const show=()=>this.screen("CONTROLS / "+source.toUpperCase(),()=>Object.keys(this.input.profile[source]).map(action=>({label:action.toUpperCase()+" / "+this.input.profile[source][action].join(","),run:()=>{let captureScreen;const stop=()=>{this.input.capture=null;show();};captureScreen={update:()=>{},render:()=>{this.renderer.clear();this.ui.page(this.renderer.ctx,"ASSIGN "+action.toUpperCase(),["PRESS A "+(source==="keyboard"?"KEY":"CONTROLLER BUTTON"),"ESCAPE CANCELS CAPTURE"],0);}};this.input.capture=(from,code)=>{if(from==="keyboard"&&code==="Escape"){stop();return;}if(from!==source)return;this.input.capture=null;const apply=resolve=>{try{const r=this.input.remap(source,action,code,resolve);if(r.status==="CONFLICT")this.confirm("USED BY "+r.other.toUpperCase()+" / REASSIGN?",()=>apply(true),show);else if(r.saved===false)this.message("CONTROLS ACTIVE / NOT SAVED",[this.input.store.error],show);else show();}catch(e){this.message("ASSIGNMENT REJECTED",[e.message],show);}};apply(false);};this.open(captureScreen);}})),()=>this.controls(back));show();};this.screen("OPTIONS / CONTROLS",[{label:"DISPLAY PALETTE",type:"enum",values:G.config.DISPLAY_PALETTES.map(p=>p.id),get:()=>this.game.displayPalette.id,preview:id=>this.game.displayPalette.preview(id),set:id=>{if(!this.game.displayPalette.choose(id))this.message("DISPLAY ACTIVE / NOT SAVED",[this.game.displayPalette.notice],()=>this.controls(back));}},{label:"KEYBOARD ASSIGNMENTS",run:()=>sourceMenu("keyboard")},{label:"CONTROLLER BUTTON ASSIGNMENTS",run:()=>sourceMenu("buttons")},{label:"RESTORE DEFAULTS",run:()=>this.confirm("RESTORE ALL CONTROL DEFAULTS?",()=>{const ok=this.input.restoreDefaults();if(ok)this.controls(back);else this.message("DEFAULTS ACTIVE / NOT SAVED",[this.input.store.error],()=>this.controls(back));},()=>this.controls(back))},{label:"STICK: LEFT / DEAD ZONE 0.55",run:()=>{}},{label:"CLOSE",run:back}],back);}
 }
 G.editor.DeveloperShell=DeveloperShell;
}(window.GBTRPG));
