(function(G){
 "use strict";
 class DeveloperShell {
  constructor(game){this.game=game;for(const k of ["input","renderer","text","ui","assets"])this[k]=game[k];this.overlay=null;this.document=null;this.terminal=null;this.history=["GODMODE / GREEDISGOOD / DEVMODE"];}
  open(screen){this.overlay=screen;this.input.clear();}
  close(){this.overlay=null;this.input.textHandler=null;this.input.capture=null;this.input.clear();}
  screen(title,fields,back=()=>this.close()){const s=new G.editor.PropertyScreen(this,title,fields,back);this.open(s);return s;}
  message(title,lines,back){return this.screen(title,lines.map(label=>({label})),back);}
  confirm(title,run,back=()=>this.devMenu()){this.screen(title,[{label:"NO / CANCEL",run:back},{label:"YES / CONFIRM",run:()=>{run();}}],back);}
  editText(label,value,commit,previous){let text=String(value);const finish=()=>{this.input.textHandler=null;this.open(previous);};this.input.textHandler=e=>{try{if(e.code==="Escape"){finish();return;}if(e.code==="Enter"){commit(text);finish();return;}if(e.code==="Backspace")text=text.slice(0,-1);else if(e.key?.length===1&&text.length<512)text+=e.key;}catch(err){screen.error=err.message;}};const screen={update:()=>{if(this.input.consumeAction()==="cancel")finish();},render:()=>{this.renderer.clear();this.ui.page(this.renderer.ctx,label,[...this.text.wrap(text+"_",70),"KEYBOARD TEXT / ENTER COMMIT / ESC CANCEL",...(screen.error?[screen.error]:[])],0);}};this.open(screen);}
  toggleTerminal(){if(this.terminal){this.input.textHandler=this.terminal.previousHandler;this.terminal=null;this.input.clear();return;}this.terminal={line:"",previousHandler:this.input.textHandler};this.input.clear();this.input.textHandler=e=>{if(e.code==="Enter"){const line=this.terminal.line,wasDev=G.core.DeveloperRuntime.devmode;this.history.push("> "+line,G.core.DeveloperRuntime.execute(line));if(wasDev&&!G.core.DeveloperRuntime.devmode){this.overlay=null;this.terminal.previousHandler=null;this.input.capture=null;}this.history=this.history.slice(-24);this.terminal.line="";}else if(e.code==="Backspace")this.terminal.line=this.terminal.line.slice(0,-1);else if(e.code==="Escape")this.toggleTerminal();else if(e.key?.length===1&&this.terminal.line.length<120)this.terminal.line+=e.key;};}
  update(ms){const global=this.input.queue.findIndex(a=>a==="terminal"||a==="devmenu");if(global>=0){const [a]=this.input.queue.splice(global,1);if(a==="terminal")this.toggleTerminal();else if(!this.terminal&&G.core.DeveloperRuntime.devmode){if(this.overlay instanceof G.editor.MapEditorState)this.overlay.menu();else if(this.overlay)this.close();else this.devMenu();}}
   if(this.terminal){if(this.input.consumeAction()==="cancel")this.toggleTerminal();return true;}if(this.overlay){this.overlay.update(ms);return true;}return false;}
  render(){if(this.terminal){this.renderer.clear();this.ui.window(this.renderer.ctx,0,0,480,360);this.text.draw(this.renderer.ctx,"TERMINAL / KEYBOARD COMMAND ENTRY",8,8,76);this.text.draw(this.renderer.ctx,this.history.join("\n"),8,30,76);this.text.draw(this.renderer.ctx,"> "+this.terminal.line+"_",8,326,76);this.text.draw(this.renderer.ctx,"TOGGLE TERMINAL TO RETURN / ESC CLOSE",8,348,76);}else this.overlay?.render();}
  getDocument(){if(!this.document)this.document=new G.editor.EditorDocument(this.game.campaign,G.data.AUTHORED_CONTENT);return this.document;}
  devMenu(){if(!G.core.DeveloperRuntime.devmode)return;const campaign=this.game.states.current===this.game.campaignMap;this.screen("DEV MENU / "+(campaign?"CAMPAIGN":"RUNTIME"),[
   ...(campaign?[{label:"EDIT CAMPAIGN MAP",run:()=>this.open(new G.editor.MapEditorState(this,"terrain"))},{label:"EDIT LOCATIONS",run:()=>this.open(new G.editor.MapEditorState(this,"locations"))}]:[]),
   ...(this.game.states.current instanceof G.states.EndDayState&&this.game.campaign.state.resolution?.pendingBattleScenario?[{label:"TEST BATTLE RESULTS",run:()=>this.battleTestResults()}]:[]),
   {label:"EDITOR FILES / SAVE IMPORT EXPORT",run:()=>this.files()},
   {label:"GAME STATE",run:()=>this.screen("GAME STATE",[{label:"RESET CURRENT GAME",run:()=>this.confirm("RESET CURRENT RUNTIME?",()=>{this.game.resetCurrent();this.close();})},...(campaign?[{label:"CAMPAIGN RUNTIME TOOLS",run:()=>this.legacyTools()},{label:"TACTICAL MOVEMENT TEST",run:()=>{this.close();this.game.openTactical();}}]:[]),{label:"BATTLE FOUNDATION TEST",run:()=>{this.close();this.game.openBattleFoundation();}},{label:"SPELL / PORTAL LAB",run:()=>{this.close();this.game.openSpellLab();}},{label:"RUN RULE CHECKS",run:()=>{const runtime={godmode:G.core.DeveloperRuntime.godmode,greedisgood:G.core.DeveloperRuntime.greedisgood,devmode:G.core.DeveloperRuntime.devmode};G.core.DeveloperRuntime.reset();let results;try{results=G.debug.runFoundationTests();}finally{Object.assign(G.core.DeveloperRuntime,runtime);}this.message("RULE CHECKS",[results.filter(r=>r.pass).length+"/"+results.length+" PASS",...results.filter(r=>!r.pass).map(r=>r.name+": "+r.error)],()=>this.devMenu());}}],()=>this.devMenu())},
   {label:"DISABLE DEVMODE",run:()=>{G.core.DeveloperRuntime.devmode=false;this.close();}},{label:"CLOSE",run:()=>this.close()}
  ]);}
  battleTestResults(){const c=this.game.campaign,b=c.state.resolution.pendingBattleScenario;
   this.screen("DEVELOPER / TEST BATTLE RESULTS",[...['PLAYER','ZEON'].map(faction=>({label:"TEST "+faction+" WIN",run:()=>{c.applyBattleResult(G.campaign.PlaceholderBattleResolver.result(b,faction,"DEFEATED"));this.close();}})),...b.participants.filter(p=>p.squadId===b.attackingSquadId?b.context.attackerMoving:b.context.defenderMoving).map(p=>({label:p.faction+" RETREATS",run:()=>{c.applyBattleResult(G.campaign.PlaceholderBattleResolver.result(b,p.faction==="PLAYER"?"ZEON":"PLAYER","RETREATED"));this.close();}}))],()=>this.devMenu());
  }
  legacyTools(){
   // Existing campaign tools run in a private view owned by the developer overlay.
   const view=Object.assign(Object.create(G.states.CampaignMapState.prototype),this.game.campaignMap,{stack:[],mode:"map",debugEnabled:true,eventLog:[...this.game.campaignMap.eventLog]});
   view.resources=new G.ui.CampaignResourceUI(view);view.debugMenu();view.list.items=view.list.items.filter(f=>!["RUN RULE CHECKS","BATTLE FOUNDATION TEST","SPELL / PORTAL LAB"].includes(f.label)&&(!G.data.AUTHORED_CONTENT||f.label!=="LOAD TEST SCENARIO"));
   this.open({update:()=>{view.update();if(view.mode==="map")this.devMenu();},render:()=>view.render()});
  }
  files(back=()=>this.devMenu()){const doc=this.getDocument();this.screen("EDITOR FILES / "+(doc.dirty?"UNSAVED CHANGES":"WORKING COPY"),[
   {label:"SAVE WORKING COPY IN THIS BROWSER",run:()=>{const ok=doc.save();this.message("EDITOR SAVE",[ok?"WORKING COPY SAVED":doc.store.error,"EXPORT JSON FOR A PORTABLE BACKUP"],()=>this.files(back));}},
   {label:"RESTORE BROWSER WORKING COPY",run:()=>this.confirm("REPLACE CURRENT EDITOR DRAFT?",()=>{doc.restore();this.files(back);},()=>this.files(back))},
   {label:"EXPORT EDITOR BACKUP JSON",run:()=>G.editor.EditorFiles.download("shining-farce-editor.json",doc.json())},
   {label:"IMPORT EDITOR BACKUP JSON",run:()=>this.confirm("REPLACE CURRENT EDITOR DRAFT?",()=>G.editor.EditorFiles.import(text=>{try{doc.import(text);this.files(back);}catch(e){this.message("IMPORT REJECTED",[e.message],()=>this.files(back));}},e=>this.message("IMPORT REJECTED",[e.message],()=>this.files(back))),()=>this.files(back))},
   {label:"EXPORT SHIPPING AUTHORED-CONTENT.JS",run:()=>G.editor.EditorFiles.download("authored-content.js",doc.shipping(),"text/javascript")},
   {label:"HOW TO SHIP AUTHORED CONTENT",run:()=>this.message("SHIPPING WORKFLOW",["1 SAVE A JSON BACKUP.","2 VALIDATE EACH BATTLE MAP.","3 EXPORT SHIPPING AUTHORED-CONTENT.JS.","4 COPY THE DOWNLOAD INTO JS/DATA/.","5 REPLACE AUTHORED-CONTENT.JS THERE.","6 REOPEN INDEX.HTML FOR A NEW RUNTIME.","CAMPAIGN SAVES ARE NOT REWRITTEN.","BROWSER STORAGE MAY VARY UNDER FILE://."],()=>this.files(back))}
  ],back);}
  controls(back=()=>this.close()){const sourceMenu=source=>{const show=()=>this.screen("CONTROLS / "+source.toUpperCase(),()=>Object.keys(this.input.profile[source]).map(action=>({label:action.toUpperCase()+" / "+this.input.profile[source][action].join(","),run:()=>{let captureScreen;const stop=()=>{this.input.capture=null;show();};captureScreen={update:()=>{},render:()=>{this.renderer.clear();this.ui.page(this.renderer.ctx,"ASSIGN "+action.toUpperCase(),["PRESS A "+(source==="keyboard"?"KEY":"CONTROLLER BUTTON"),"ESCAPE CANCELS CAPTURE"],0);}};this.input.capture=(from,code)=>{if(from==="keyboard"&&code==="Escape"){stop();return;}if(from!==source)return;this.input.capture=null;const apply=resolve=>{try{const r=this.input.remap(source,action,code,resolve);if(r.status==="CONFLICT")this.confirm("USED BY "+r.other.toUpperCase()+" / REASSIGN?",()=>apply(true),show);else if(r.saved===false)this.message("CONTROLS ACTIVE / NOT SAVED",[this.input.store.error],show);else show();}catch(e){this.message("ASSIGNMENT REJECTED",[e.message],show);}};apply(false);};this.open(captureScreen);}})),()=>this.controls(back));show();};this.screen("OPTIONS / CONTROLS",[{label:"KEYBOARD ASSIGNMENTS",run:()=>sourceMenu("keyboard")},{label:"CONTROLLER BUTTON ASSIGNMENTS",run:()=>sourceMenu("buttons")},{label:"RESTORE DEFAULTS",run:()=>this.confirm("RESTORE ALL CONTROL DEFAULTS?",()=>{const ok=this.input.restoreDefaults();if(ok)this.controls(back);else this.message("DEFAULTS ACTIVE / NOT SAVED",[this.input.store.error],()=>this.controls(back));},()=>this.controls(back))},{label:"STICK: LEFT / DEAD ZONE 0.55",run:()=>{}},{label:"CLOSE",run:back}],back);}
 }
 G.editor.DeveloperShell=DeveloperShell;
}(window.GBTRPG));
