(function(G){
 "use strict";
 const V=G.campaign.Validation,L=G.editor.LocationModel,M=G.editor.MapAuthoring,B=G.editor.BattleMapAuthoring;
 class EditorDocument {
  constructor(campaign,data=null,store=new G.core.LocalStore()){this.campaign=campaign;this.store=store;const initial=data||{version:1,world:V.clone(campaign.definitions),visuals:V.clone(G.data.WORLD_VISUALS),battleMaps:{},nextId:1,entities:[]};if(!data)for(const l of Object.values(initial.world.locations))L.normalize(l,campaign.state.locations[l.id]?.controller);this.validate(initial);this.data=V.freeze(V.clone(initial));this.dirty=false;}
  validate(d){V.plainData(d);G.editor.BattleSceneAssets.shape(d.battleScene);V.assert(d&&typeof d==="object"&&!Array.isArray(d)&&d.battleMaps&&typeof d.battleMaps==="object"&&!Array.isArray(d.battleMaps),"editor document and Battle Map dictionary required");V.assert(d.version===1&&Number.isSafeInteger(d.nextId)&&d.nextId>=1,"unsupported editor document");V.definitions(d.world);const m=d.visuals;V.assert(m&&m.tiles&&Object.keys(m.tiles).length===Object.keys(G.editor.CAMPAIGN_TILES).length&&Object.entries(G.editor.CAMPAIGN_TILES).every(([key,t])=>m.tiles[key]===t.frame),"unsupported campaign tile atlas");V.assert(m.tileSize===16&&m.width>=30&&m.height>=30&&m.rows.length===m.height&&m.rows.every(r=>typeof r==="string"&&r.length===m.width&&[...r].every(k=>G.editor.CAMPAIGN_TILES[k])),"invalid campaign terrain/dimensions");const occupied=new Set();for(const l of Object.values(d.world.locations)){L.validate(l);const p={x:l.mapPosition.x/16,y:l.mapPosition.y/16},key=p.x+","+p.y;V.assert(M.inside(p,m.width,m.height)&&!occupied.has(key),"invalid or occupied location coordinate");occupied.add(key);V.assert(Array.isArray(l.battleMaps)&&l.battleMaps.every(id=>V.validId(id)&&d.battleMaps[id]),"missing static map reference");}V.assert(Array.isArray(d.entities),"missing positional metadata");for(const p of d.entities)V.assert(M.inside(p,m.width,m.height),"invalid map entity coordinate");for(const [id,map]of Object.entries(d.battleMaps)){V.assert(id===map.id&&V.validId(id),"invalid map identity");G.systems.BattleTerrainSystem.validate(map);B.shape(map);for(const row of map.tiles)for(const t of row)M.validateTile(t);}return true;}
  command(fn){const draft=V.clone(this.data),result=fn(draft);this.validate(draft);this.data=V.freeze(draft);this.dirty=true;return result;}
  id(d,prefix){let id;do{id=prefix+d.nextId++;}while(d.world.locations[id]||d.world.routes[id]||d.battleMaps[id]||d.battleScene?.animations[id]||d.battleScene?.units[id]||Object.values(d.battleMaps).some(m=>m.specialDeployments.some(s=>s.id===id)));return id;}
  at(x,y){return Object.values(this.data.world.locations).find(l=>l.mapPosition.x===x*16&&l.mapPosition.y===y*16);}
  paint(x,y,key){return this.command(d=>{V.assert(G.editor.CAMPAIGN_TILES[key]&&M.inside({x,y},d.visuals.width,d.visuals.height),"invalid terrain paint");const row=[...d.visuals.rows[y]];row[x]=key;d.visuals.rows[y]=row.join("");});}
  addLocation(x,y,copy=null){return this.command(d=>{V.assert(!Object.values(d.world.locations).some(l=>l.mapPosition.x===x*16&&l.mapPosition.y===y*16),"location tile occupied");const id=this.id(d,"location"),l=copy?V.clone(copy):{id,name:"NEW LOCATION",polityId:"authored",mapPosition:{x:0,y:0},locationType:"WILDERNESS",economy:{dailyIncomeG:0,shops:{}}};if(!d.world.polities[l.polityId])d.world.polities[l.polityId]={id:l.polityId,name:"UNAFFILIATED",category:"AUTHORING",locationIds:[],politics:{}};l.id=id;l.mapPosition={x:x*16,y:y*16};L.normalize(l);d.world.locations[id]=l;d.world.polities[l.polityId].locationIds.push(id);return id;});}
  moveLocation(id,x,y){return this.command(d=>{V.assert(d.world.locations[id],"unknown location");d.world.locations[id].mapPosition={x:x*16,y:y*16};});}
  protectedLocations(){const s=this.campaign.state,ids=new Set();for(const q of Object.values(s.squads))ids.add(q.currentLocationId);for(const u of Object.values(s.units))if(u.unassignedLocationId)ids.add(u.unassignedLocationId);for(const w of Object.values(s.shipments))ids.add(w.currentLocationId);for(const i of Object.values(s.itemInstances))if(i.place.type==="LOCATION")ids.add(i.place.id);for(const q of G.data.DEMO_CAMPAIGN.squads)ids.add(q.currentLocationId);return ids;}
  deleteLocation(id,confirmed=false){V.assert(confirmed,"confirm location deletion");V.assert(!this.protectedLocations().has(id),"location is referenced by runtime or starting entities");return this.command(d=>{V.assert(d.world.locations[id],"unknown location");delete d.world.locations[id];for(const [rid,r]of Object.entries(d.world.routes))if([r.locationAId,r.locationBId].includes(id))delete d.world.routes[rid];for(const p of Object.values(d.world.polities)){p.locationIds=p.locationIds.filter(x=>x!==id);if(p.capitalLocationId===id)delete p.capitalLocationId;if(p.petitionLocationId===id)delete p.petitionLocationId;}});}
  connect(a,b){return this.command(d=>{V.assert(a!==b&&d.world.locations[a]&&d.world.locations[b],"choose another location");const route=Object.values(d.world.routes).find(r=>[r.locationAId,r.locationBId].includes(a)&&[r.locationAId,r.locationBId].includes(b));if(route){delete d.world.routes[route.id];return false;}const id=this.id(d,"route");d.world.routes[id]={id,locationAId:a,locationBId:b};return true;});}
  location(id,fn){return this.command(d=>{V.assert(d.world.locations[id],"unknown location");fn(d.world.locations[id]);});}
  defaultTier(id,tier){return this.location(id,l=>{l.settlement.defaultTier=tier;for(const shop of Object.values(l.settlement.shops))shop.tier=tier;});}
  resize(edge,amount){return this.command(d=>{const m=d.visuals,points=Object.values(d.world.locations).map(l=>({x:l.mapPosition.x/16,y:l.mapPosition.y/16}));points.push(...d.entities);const runtime=G.ui.MapPresentation.derive(this.campaign);for(const obj of runtime){const original=this.campaign.definitions.locations[obj.locationId],current=d.world.locations[obj.locationId];if(current)points.push({x:(current.mapPosition.x+obj.worldX-original.mapPosition.x)/16,y:(current.mapPosition.y+obj.worldY-original.mapPosition.y)/16});}
    const r=M.resize({width:m.width,height:m.height,tiles:m.rows.map(row=>[...row])},edge,amount,points,"w");for(const l of Object.values(d.world.locations)){l.mapPosition.x+=r.dx*16;l.mapPosition.y+=r.dy*16;}for(const p of d.entities){p.x+=r.dx;p.y+=r.dy;}m.width=r.width;m.height=r.height;m.rows=r.tiles.map(row=>row.join(""));return{dx:r.dx,dy:r.dy};});}
  createBattleMap(locationId,width,height,conditions){return this.command(d=>{V.assert(d.world.locations[locationId],"unknown location");const id=this.id(d,"battleMap");d.battleMaps[id]=B.create(id,width,height,conditions);d.world.locations[locationId].battleMaps.push(id);return id;});}
  deleteBattleMap(id){return this.command(d=>{V.assert(Object.hasOwn(d.battleMaps,id),"unknown Battle Map");V.assert(!Object.values(d.world.locations).some(l=>l.battleMaps.includes(id)),"remove all location references before deleting this Battle Map");delete d.battleMaps[id];});}
  battle(id,fn){return this.command(d=>{V.assert(d.battleMaps[id],"unknown Battle Map");fn(d.battleMaps[id]);});}
  paintBattle(id,x,y,value){M.validateTile(value);return this.battle(id,map=>{V.assert(M.inside({x,y},map.width,map.height),"invalid paint coordinate");map.tiles[y][x]=V.clone(value);});}
  spot(id,side,group,x,y){return this.battle(id,map=>{V.assert(map.deployment[side]&&["FRONT","BACK"].includes(group)&&M.inside({x,y},map.width,map.height),"invalid deployment spot");const a=map.deployment[side].positions[group],i=a.findIndex(p=>p.x===x&&p.y===y);if(i>=0)a.splice(i,1);else{V.assert(!B.points(map).some(p=>p.x===x&&p.y===y),"deployment spot occupied");V.assert(G.systems.BattleTerrainSystem.definition(map,x,y)?.traversable,"deployment terrain invalid or unresolved");a.push({x,y});}});}
  addSpecial(id,spec,x,y){return this.command(d=>{const m=d.battleMaps[id],copy={...V.clone(spec),id:this.id(d,"special"),x,y};B.special(copy);V.assert(M.inside(copy,m.width,m.height)&&!B.points(m).some(p=>p.x===x&&p.y===y),"special tile occupied or out of bounds");V.assert(G.systems.BattleTerrainSystem.canOccupy(m,copy.unit,x,y),"special terrain invalid");m.specialDeployments.push(copy);return copy.id;});}
  resizeBattle(id,edge,amount){return this.command(d=>d.battleMaps[id]=B.resize(d.battleMaps[id],edge,amount));}
  save(){const ok=this.store.write("editor.v1",this.data);if(ok)this.dirty=false;return ok;}
  restore(){const saved=this.store.read("editor.v1");V.assert(saved,this.store.error||this.store.missingWorkingCopy());this.validate(saved);this.data=V.freeze(V.clone(saved));this.dirty=false;}
  prepareImport(text){return G.editor.AuthoredFiles.prepareImport(this,text);}
  applyImport(plan,replaceMaps=false){V.assert(plan.base===this.data,"editor changed while import was pending; choose the file again");V.assert(!plan.conflicts.length||replaceMaps,"Battle Map IDs already exist: "+plan.conflicts.join(", ")+"; confirm replacement");this.validate(plan.data);this.data=V.freeze(V.clone(plan.data));this.dirty=true;}
  import(text,replaceMaps=false){this.applyImport(this.prepareImport(text),replaceMaps);}
  portable(kind="DOCUMENT",id=null){return G.editor.AuthoredFiles.portable(this.data,kind,id);}
  shippingFiles(){return G.editor.AuthoredFiles.packageFiles(this);}
  json(){return JSON.stringify(this.data,null,2);}
  shipping(){G.editor.AuthoredFiles.ready(this);for(const map of Object.values(this.data.battleMaps)){const r=B.validate(map);V.assert(r.valid,map.id+": "+r.errors.join("; "));}return"// Authored in Shining Farce. Replace js/data/authored-content.js with this file.\nwindow.GBTRPG.data.AUTHORED_CONTENT = "+JSON.stringify(this.data,null,2)+";\n";}
 }
 G.editor.EditorDocument=EditorDocument;
}(window.GBTRPG));
