(function(G){
 "use strict";
 G.editor=G.editor||{};
 const V=G.campaign.Validation,categories=["CONSUMABLE","WEAPON","ARMOR","ACCESSORY"];
 const appearances={capital:{spriteId:"capitalMarker",frame:0,size:32},village:{spriteId:"locationMarkers",frame:0,size:16},sign:{spriteId:"locationMarkers",frame:1,size:16},fort:{spriteId:"locationMarkers",frame:2,size:16},shrine:{spriteId:"locationMarkers",frame:3,size:16}};
 function normalize(l,controller="NEUTRAL"){
  if(!l.settlement){const e=l.economy||{},types=e.recruitment?.types||[];l.settlement={enabled:!["CROSSROADS","WILDERNESS"].includes(l.locationType),type:({CAPITAL:"Castle",FORTRESS:"Fort",PORT:"Town",VILLAGE:"Village",SHRINE:"Village"})[l.locationType]||"Village",allegiance:controller,defaultTier:1,shops:Object.fromEntries(categories.map(k=>[k,{enabled:(e.shops?.[k]||0)>0,tier:e.shops?.[k]||1}])),recruitment:{races:[...new Set(types.map(id=>G.data.UNIT_TYPES[id].raceId))],classes:[...new Set(types.map(id=>G.data.UNIT_TYPES[id].classId))]},income:e.dailyIncomeG||0};}
  l.appearanceId=l.appearanceId||({CAPITAL:"capital",CROSSROADS:"sign",FORTRESS:"fort",SHRINE:"shrine"})[l.locationType]||"village";l.battleMaps=l.battleMaps||[];l.questAssociations=l.questAssociations||[];return l;
 }
 function effective(l){const s=l.settlement;if(!s)return null;return s.enabled?V.clone(s):{enabled:false,type:"Wilderness",allegiance:null,shops:{},recruitment:{races:[],classes:[]},income:0};}
 function validate(l){V.assert(typeof l.name==="string"&&l.name.trim().length>0&&l.name.length<=80,"location name required (80 characters maximum)");const s=l.settlement;V.assert(s&&typeof s.enabled==="boolean"&&["Village","Town","City","Fort","Castle"].includes(s.type),"invalid settlement type");V.assert(["PLAYER","ZEON","NEUTRAL"].includes(s.allegiance),"invalid settlement allegiance");V.assert(Number.isSafeInteger(s.income)&&s.income>=0&&Number.isSafeInteger(s.defaultTier)&&s.defaultTier>=1,"invalid income/tier");for(const k of categories)V.assert(typeof s.shops[k]?.enabled==="boolean"&&Number.isSafeInteger(s.shops[k].tier)&&s.shops[k].tier>=1,"invalid shop tier");for(const [key,defs]of [["races",G.data.RACES],["classes",G.data.CLASSES]])V.assert(Array.isArray(s.recruitment[key])&&new Set(s.recruitment[key]).size===s.recruitment[key].length&&s.recruitment[key].every(id=>defs[id]),"invalid recruitment selection");V.assert(appearances[l.appearanceId],"invalid location appearance");V.assert(Array.isArray(l.questAssociations)&&l.questAssociations.every(V.validId),"invalid quest associations");}
 function compile(l){const out=V.clone(l),e=effective(out);if(!e)return out;out.locationType=e.enabled?e.type.toUpperCase():"WILDERNESS";out.economy={...out.economy,dailyIncomeG:e.income,shops:Object.fromEntries(categories.filter(k=>e.shops[k]?.enabled).map(k=>[k,e.shops[k].tier]))};if(!e.enabled)delete out.economy.recruitment;else if(out.economy.recruitment){out.economy.recruitment.types=out.economy.recruitment.types.filter(id=>e.recruitment.races.includes(G.data.UNIT_TYPES[id]?.raceId)&&e.recruitment.classes.includes(G.data.UNIT_TYPES[id]?.classId));if(!out.economy.recruitment.types.length)delete out.economy.recruitment;}return out;}
 G.editor.LocationModel={normalize,effective,validate,compile,categories,appearances};
}(window.GBTRPG));
