(function(G){
 "use strict";
 const V=G.campaign.Validation,L=G.editor.LocationModel,B=G.editor.BattleMapAuthoring;
 class MapEditorState {
  constructor(host,mode,mapId=null){Object.assign(this,{host,mode,mapId});this.doc=host.getDocument();this.cursor={x:0,y:0};this.tool=null;this.elapsed=0;this.error=null;this.camera=new G.rendering.WorldCamera(480,480);this.board=new G.rendering.BattleMapRenderer(host);}
  back(){if(this.mode==="battle"&&!this.doc.data.battleMaps[this.mapId])return this.host.mapFiles(()=>this.host.devMenu());this.clamp();this.host.open(this);}
  show(title,fields){return this.host.screen(title,fields,()=>this.back());}
  map(){return this.mode==="battle"?this.doc.data.battleMaps[this.mapId]:this.doc.data.visuals;}
  menu(){this.show(this.mode.toUpperCase()+" EDITOR",[
   ...(this.mode!=="locations"?[{label:"CHOOSE TILE",run:()=>this.tiles()},{label:"COPY EXISTING TILE",run:()=>{this.tool={type:"paint",value:this.mode==="battle"?V.clone(this.map().tiles[this.cursor.y][this.cursor.x]):this.map().rows[this.cursor.y][this.cursor.x]};this.back();}}]:[]),
   {label:"CLEAR ACTIVE TOOL",run:()=>{this.tool=null;this.connectId=null;this.back();}},
   {label:"RESIZE MAP",run:()=>this.resizeMenu()},
   ...(this.mode==="battle"?[{label:"TERRAIN PRESENTATION / UNDER CURSOR",run:()=>{const tile=G.editor.MapAuthoring.tile(this.map().tiles[this.cursor.y][this.cursor.x]);new G.editor.AssetBrowser(this.host).terrain(tile.terrainId,()=>this.back());}},{label:"MAP PROPERTIES",run:()=>this.battleProperties()},{label:"FRONT / BACK DEPLOYMENT",run:()=>this.deploymentMenu()},{label:"SPECIAL DEPLOYMENT",run:()=>this.specialMenu()},{label:"VALIDATE BATTLE MAP",run:()=>{const r=B.validate(this.map());this.host.message(r.valid?"MAP VALID":"MAP INVALID",r.valid?["READY FOR INITIALIZATION WITH AN APPROACH PROVIDER"]:r.errors,()=>this.back());}},{label:"PREVIEW NORMAL BATTLE MAP",run:()=>this.preview()}]:[]),
   {label:"SAVE / IMPORT / EXPORT",run:()=>this.host.files(()=>this.back())},
   {label:"EXIT EDITOR / KEEP WORKING DRAFT",run:()=>this.host.devMenu()}
  ]);}
  tiles(){const battle=this.mode==="battle",catalog=battle?G.editor.BATTLE_TILES:G.editor.CAMPAIGN_TILES,ids=Object.keys(catalog),variants={};let index=0;const picker={update:()=>{const a=this.host.input.consumeAction(),id=ids[index],count=catalog[id].variants?.length||1;if(a==="cancel")return this.back();if(["up","down"].includes(a))index=(index+(a==="up"?-1:1)+ids.length)%ids.length;if(a==="select"||a==="start")variants[id]=((variants[id]||0)+(a==="select"?1:-1)+count)%count;if(a==="confirm"){this.tool={type:"paint",value:battle?{terrainId:id,variantId:catalog[id].variants[variants[id]||0].id}:id};this.back();}},render:()=>{this.host.renderer.clear();const list=new G.ui.SelectableList(ids.map(id=>({label:catalog[id].name.toUpperCase()+(battle?" / "+((variants[id]||0)+1)+" OF "+catalog[id].variants.length:"" )})),22);list.index=index;list.offset=Math.max(0,index-21);this.host.ui.list(this.host.renderer.ctx,"TILES / Q NEXT VARIANT / P PREVIOUS",list,"ACCEPT CHOOSE / CANCEL BACK");}};this.host.open(picker);}
  resizeMenu(){let edge="NORTH",amount=1;this.show("RESIZE / POSITIVE ADD / NEGATIVE REMOVE",[{label:"EDGE",type:"enum",values:["NORTH","SOUTH","EAST","WEST"],get:()=>edge,set:v=>edge=v},{label:"ROWS / COLUMNS",type:"number",min:-Math.max(this.map().width,this.map().height),get:()=>amount,set:v=>amount=v},{label:"APPLY RESIZE",run:()=>{const shift=G.editor.MapAuthoring.shift(this.map().width,this.map().height,edge,amount);if(this.mode==="battle")this.doc.resizeBattle(this.mapId,edge,amount);else this.doc.resize(edge,amount);this.cursor.x+=shift.dx;this.cursor.y+=shift.dy;this.clamp();this.back();}}]);}
  context(){if(this.mode==="battle"){const special=this.map().specialDeployments.find(p=>p.x===this.cursor.x&&p.y===this.cursor.y);if(special)return this.show("SPECIAL / "+special.unit.name,[{label:"EDIT",run:()=>this.specialProperties(V.clone(special),special.id)},{label:"DELETE",run:()=>this.host.confirm("DELETE SPECIAL DEPLOYMENT?",()=>{this.doc.battle(this.mapId,m=>m.specialDeployments=m.specialDeployments.filter(s=>s.id!==special.id));this.back();},()=>this.back())},{label:"TERRAIN / MAP TOOLS",run:()=>this.menu()}]);return this.menu();}if(this.mode==="terrain")return this.menu();const l=this.doc.at(this.cursor.x,this.cursor.y);if(!l)return this.show("EMPTY LOCATION TILE",[{label:"CREATE LOCATION",run:()=>{this.tool={type:"create"};this.back();}},{label:"EDITOR TOOLS",run:()=>this.menu()}]);this.show(l.name,[{label:"COPY",run:()=>{this.tool={type:"copy",location:V.clone(l)};this.back();}},{label:"EDIT",run:()=>this.location(l.id)},{label:"MOVE",run:()=>{this.tool={type:"move",id:l.id};this.back();}},{label:"DELETE",run:()=>this.host.confirm("DELETE LOCATION AND ALL ITS ROUTES?",()=>{this.doc.deleteLocation(l.id,true);this.back();},()=>this.back())},{label:"EDITOR TOOLS",run:()=>this.menu()}]);}
  location(id){const get=()=>this.doc.data.world.locations[id],update=fn=>this.doc.location(id,fn),field=(label,type,getter,setter,extra={})=>({label,type,get:()=>getter(get()),set:v=>update(l=>setter(l,v)),...extra});this.show("LOCATION / "+id,()=>[
   field("NAME","text",l=>l.name,(l,v)=>l.name=v),field("SETTLEMENT","toggle",l=>l.settlement.enabled,(l,v)=>l.settlement.enabled=v),
   ...(get().settlement.enabled?[field("SETTLEMENT TYPE","enum",l=>l.settlement.type,(l,v)=>l.settlement.type=v,{values:["Village","Town","City","Fort","Castle"]}),field("FACTION ALLEGIANCE","enum",l=>l.settlement.allegiance,(l,v)=>l.settlement.allegiance=v,{values:["PLAYER","ZEON","NEUTRAL"]}),{label:"SHOPS",run:()=>this.shopProperties(id)},{label:"RECRUITMENT",run:()=>this.recruitment(id)},field("INCOME G","number",l=>l.settlement.income,(l,v)=>l.settlement.income=v)]:[{label:"WILDERNESS / SETTLEMENT CONFIGURATION RETAINED"}]),
   field("APPEARANCE","enum",l=>l.appearanceId,(l,v)=>l.appearanceId=v,{values:Object.keys(L.appearances)}),field("QUEST ASSOCIATIONS (COMMA SEPARATED)","text",l=>l.questAssociations.join(","),(l,v)=>l.questAssociations=v.split(",").map(s=>s.trim()).filter(Boolean)),
   {label:"BATTLE MAPS",run:()=>this.battleMaps(id)},{label:"CONNECT / DISCONNECT LOCATIONS",run:()=>{this.connectId=id;this.tool=null;this.back();}},{label:"BACK TO LOCATION EDITOR",run:()=>this.back()}
  ]);}
  shopProperties(id){const l=()=>this.doc.data.world.locations[id];this.host.screen("SETTLEMENT SHOPS",()=>[...L.categories.map(k=>({label:k+" SHOP",type:"toggle",get:()=>l().settlement.shops[k].enabled,set:v=>this.doc.location(id,l=>l.settlement.shops[k].enabled=v)})),{label:"DEFAULT / SHARED TIER",type:"number",min:1,get:()=>l().settlement.defaultTier,set:v=>this.doc.defaultTier(id,v)},{label:"INDIVIDUAL TIERS",run:()=>this.host.screen("INDIVIDUAL SHOP TIERS",L.categories.map(k=>({label:k,type:"number",min:1,get:()=>l().settlement.shops[k].tier,set:v=>this.doc.location(id,l=>l.settlement.shops[k].tier=v)})),()=>this.shopProperties(id))}],()=>this.location(id));}
  recruitment(id){this.host.screen("RECRUITMENT / LEVEL FORMULA IS NOT AUTHORED",[{label:"ALLOWED RACES",run:()=>select("races",G.data.RACES)},{label:"ALLOWED CLASSES",run:()=>select("classes",G.data.CLASSES)}],()=>this.location(id));const select=(key,defs)=>this.host.screen("RECRUITMENT "+key.toUpperCase(),Object.keys(defs).map(value=>({label:defs[value].name||value,type:"toggle",get:()=>this.doc.data.world.locations[id].settlement.recruitment[key].includes(value),set:yes=>this.doc.location(id,l=>{const a=l.settlement.recruitment[key];if(yes)a.push(value);else a.splice(a.indexOf(value),1);})})),()=>this.recruitment(id));}
  battleMaps(id){this.host.screen("STATIC BATTLE MAPS",()=>[...this.doc.data.world.locations[id].battleMaps.map(mapId=>({label:this.doc.data.battleMaps[mapId].name,run:()=>this.host.open(new MapEditorState(this.host,"battle",mapId))})),{label:"ASSOCIATE / REMOVE EXISTING MAP REFERENCES",run:()=>this.mapReferences(id)},{label:"CREATE NEW BATTLE MAP",run:()=>{let width=30,height=30,controller="ANY";this.host.screen("NEW BATTLE MAP",[{label:"WIDTH",type:"number",min:30,get:()=>width,set:v=>width=v},{label:"HEIGHT",type:"number",min:30,get:()=>height,set:v=>height=v},{label:"CONTROLLING FACTION",type:"enum",values:["ANY","PLAYER","ZEON","NEUTRAL","WILDERNESS"],get:()=>controller,set:v=>controller=v},{label:"CREATE / FILL OCEAN",run:()=>{const mapId=this.doc.createBattleMap(id,width,height,{controller:controller==="ANY"?null:controller,storyKeys:[]});this.host.open(new MapEditorState(this.host,"battle",mapId));}}],()=>this.battleMaps(id));}}],()=>this.location(id));}
  mapReferences(id){const ids=Object.keys(this.doc.data.battleMaps);this.host.screen("MAP REFERENCES / "+id,ids.length?ids.map(mapId=>({label:mapId+" / "+this.doc.data.battleMaps[mapId].name,type:"toggle",get:()=>this.doc.data.world.locations[id].battleMaps.includes(mapId),set:yes=>this.doc.location(id,l=>{if(yes){if(!l.battleMaps.includes(mapId))l.battleMaps.push(mapId);}else l.battleMaps=l.battleMaps.filter(key=>key!==mapId);})})):[{label:"NO MAPS / CREATE OR IMPORT A BATTLE MAP FIRST"}],()=>this.battleMaps(id));}
  battleProperties(){const set=fn=>this.doc.battle(this.mapId,fn);this.show("BATTLE MAP / "+this.mapId,[{label:"NAME",type:"text",get:()=>this.map().name,set:v=>set(m=>m.name=v)},{label:"CONTROLLING FACTION",type:"enum",values:["ANY","PLAYER","ZEON","NEUTRAL","WILDERNESS"],get:()=>this.map().conditions.controller||"ANY",set:v=>set(m=>m.conditions.controller=v==="ANY"?null:v)},{label:"REQUIRED STORY KEYS (COMMA SEPARATED)",type:"text",get:()=>this.map().conditions.storyKeys.join(","),set:v=>set(m=>m.conditions.storyKeys=v.split(",").map(x=>x.trim()).filter(Boolean))},{label:"APPROACH AXIS",type:"enum",values:["NORTH / SOUTH","EAST / WEST"],get:()=>this.map().approaches.join(" / "),set:v=>set(m=>m.approaches=v.split(" / "))}]);}
  deploymentMenu(){let side=this.map().approaches[0],group="FRONT";this.show("INDIVIDUAL DEPLOYMENT SPOTS",[{label:"SIDE",type:"enum",values:this.map().approaches,get:()=>side,set:v=>side=v},{label:"GROUP",type:"enum",values:["FRONT","BACK"],get:()=>group,set:v=>group=v},{label:"PLACE / REMOVE SPOTS",run:()=>{this.tool={type:"spot",side,group};this.back();}}]);}
  specialMenu(){this.show("SPECIAL UNIT / COPY FULL CHARACTER",Object.values(this.host.game.campaign.state.units).map(unit=>({label:unit.name+" / "+unit.id,run:()=>{const equipment=Object.values(G.campaign.InventorySystem.equipmentDefinitions(this.host.game.campaign.state,unit.id)).map(i=>i.id);this.specialProperties({id:"draftSpecial",x:this.cursor.x,y:this.cursor.y,faction:unit.faction,unit:V.clone(unit),equipment});}})));}
  specialProperties(spec,existingId=null){const u=spec.unit,rebuild=(raceId=u.raceId,currentClassId=u.currentClassId,characterLevel=u.characterLevel)=>Object.assign(u,G.campaign.CharacterGrowthSystem.simulateRecruitGrowth({raceId,currentClassId,characterLevel,seed:u.growthRngState}));const save=()=>{B.special(spec);if(existingId){this.doc.battle(this.mapId,m=>m.specialDeployments[m.specialDeployments.findIndex(s=>s.id===existingId)]=V.clone(spec));}else this.tool={type:"special",spec};this.back();};const show=()=>this.show("SPECIAL / FULL UNIT SNAPSHOT",[
   {label:"IDENTITY / "+u.id},{label:"NAME",type:"text",get:()=>u.name,set:v=>u.name=v},{label:"FACTION",type:"enum",values:Object.keys(G.data.COMBAT_FACTIONS),get:()=>spec.faction,set:v=>spec.faction=v},
   {label:"CLASS (REBUILDS STATS)",type:"enum",values:Object.keys(G.data.CLASSES),get:()=>u.currentClassId,set:v=>rebuild(u.raceId,v)},
   {label:"RACE (REBUILDS STATS)",type:"enum",values:Object.keys(G.data.RACES),get:()=>u.raceId,set:v=>rebuild(v)},
   {label:"CHARACTER LEVEL (REBUILDS STATS)",type:"number",min:1,max:G.config.CHARACTER_STATS.levelCap,get:()=>u.characterLevel,set:v=>rebuild(u.raceId,u.currentClassId,v)},
   {label:"CLASS LEVEL",type:"number",min:1,max:10,get:()=>G.campaign.ClassProgressionSystem.progress(u,u.currentClassId).classLevel,set:v=>{const cp=G.config.CLASSES.thresholds[v-1];u.classProgress[u.currentClassId]={classLevel:v,lifetimeCP:cp,currentCP:cp,entryGrantCP:0};u.learnedAbilityIds=u.learnedAbilityIds.filter(id=>G.data.ABILITIES[id].classId!==u.currentClassId||G.data.ABILITIES[id].level<=v);for(const key of ["reactionId","supportId","movementId"])if(!u.learnedAbilityIds.includes(u.abilityLoadout[key]))u.abilityLoadout[key]=null;}},
   {label:"EQUIPMENT",run:()=>this.host.screen("SPECIAL EQUIPMENT",Object.values(G.data.ITEMS).filter(i=>i.equipmentSlot).map(i=>({label:i.name,type:"toggle",get:()=>spec.equipment.includes(i.id),set:yes=>{if(yes)spec.equipment.push(i.id);else spec.equipment=spec.equipment.filter(id=>id!==i.id);}})),show)},
   {label:existingId?"SAVE SPECIAL DEFINITION":"ACTIVATE SPECIAL PLACEMENT TOOL",run:save}
  ]);show();}
  preview(){const map=this.map(),state={units:{},positions:{},portals:{},turns:{},timeline:{ct:{}},controlledUnitId:null,presentation:{phase:"MAP"}};const preview={update:()=>{const a=this.host.input.consumeAction();if(a==="cancel")return this.back();this.move(a);},render:()=>{this.board.draw(state,map,this.cursor,[]);this.host.text.draw(this.host.renderer.ctx,"AUTHORED MAP PREVIEW / CANCEL RETURN",8,348,75);}};this.host.open(preview);}
  clamp(){const m=this.map();this.cursor.x=Math.max(0,Math.min(m.width-1,this.cursor.x));this.cursor.y=Math.max(0,Math.min(m.height-1,this.cursor.y));}
  move(action){const d={up:[0,-1],right:[1,0],down:[0,1],left:[-1,0]}[action];if(d){this.cursor.x+=d[0];this.cursor.y+=d[1];this.clamp();}}
  update(ms=0){this.elapsed+=ms;const a=this.host.input.consumeAction();try{if(this.error){if(a)this.error=null;return;}this.move(a);if(a==="menu")return this.menu();if(a==="cancel"){if(this.connectId){this.connectId=null;return;}return this.context();}if(a!=="confirm")return;const {x,y}=this.cursor,t=this.tool;if(this.connectId){const target=this.doc.at(x,y);V.assert(target,"select another location");this.doc.connect(this.connectId,target.id);return;}if(!t)return;if(t.type==="paint"){if(this.mode==="battle")this.doc.paintBattle(this.mapId,x,y,t.value);else this.doc.paint(x,y,t.value);}if(t.type==="create"){const id=this.doc.addLocation(x,y);this.location(id);}if(t.type==="copy")this.doc.addLocation(x,y,t.location);if(t.type==="move"){this.doc.moveLocation(t.id,x,y);this.tool=null;}if(t.type==="spot")this.doc.spot(this.mapId,t.side,t.group,x,y);if(t.type==="special")this.doc.addSpecial(this.mapId,t.spec,x,y);}catch(e){this.error=e.message;}}
  render(){const {renderer,text,ui}=this.host,c=renderer.ctx,m=this.map();renderer.clear();let point;
   if(this.mode==="battle"){this.board.draw({units:{},positions:{},portals:{},turns:{},timeline:{ct:{}},controlledUnitId:null,presentation:{phase:"MAP"}},m,this.cursor,[]);point=p=>({x:p.x*16-this.board.camera.x,y:p.y*16-this.board.camera.y+40});c.save();c.beginPath();c.rect(0,40,352,288);c.clip();for(const side of m.approaches)for(const group of ["FRONT","BACK"])for(const p of m.deployment[side].positions[group]){const q=point(p);c.fillStyle=G.config.PALETTE.background;c.fillRect(q.x+3,q.y+3,10,10);text.draw(c,group[0],q.x+5,q.y+4,1);}for(const p of m.specialDeployments){const q=point(p);c.drawImage(this.host.assets.getImage(G.data.UNIT_TYPES[p.unit.typeId]?.strategicSpriteId||"unitMage"),q.x,q.y);text.draw(c,"S",q.x+5,q.y+4,1);}c.restore();}
   else{const d=this.doc.data.world,s=V.clone(this.host.game.campaign.state);s.locations=Object.fromEntries(Object.keys(d.locations).map(id=>[id,s.locations[id]||{controller:d.locations[id].settlement.allegiance,stationedSquadIds:{PLAYER:null,ZEON:null}}]));s.routes=Object.fromEntries(Object.keys(d.routes).map(id=>[id,{available:true,blocked:false}]));const projection={definitions:d,state:s},objects=G.ui.MapPresentation.derive(projection);this.camera.worldWidth=m.width*16;this.camera.worldHeight=m.height*16;this.camera.follow(this.cursor.x*16,this.cursor.y*16);this.host.game.campaignMap.worldRenderer.draw(c,d,s,{terrain:m,camera:this.camera,cursor:{x:this.cursor.x*16,y:this.cursor.y*16},objects,selected:null});point=p=>this.camera.worldToScreen(p.x*16,p.y*16);if(this.connectId&&Math.floor(this.elapsed/500)%2===0){const ids=[this.connectId,...Object.values(d.routes).filter(r=>[r.locationAId,r.locationBId].includes(this.connectId)).flatMap(r=>[r.locationAId,r.locationBId])];for(const id of new Set(ids)){const p=d.locations[id].mapPosition,q=this.camera.worldToScreen(p.x,p.y);c.strokeStyle=G.config.PALETTE.darkest;c.strokeRect(q.x+.5,q.y+.5,15,15);}}}
   const q=point(this.cursor);c.strokeStyle=G.config.PALETTE.darkest;c.strokeRect(q.x+2.5,q.y+2.5,11,11);ui.window(c,0,0,480,16);text.draw(c,this.mode.toUpperCase()+" EDITOR / "+(this.connectId?"CONNECT":this.tool?.type.toUpperCase()||"NO TOOL"),6,4,75);ui.window(c,0,328,480,32);text.draw(c,"ACCEPT APPLY / CANCEL CONTEXT / MENU TOOLS",6,334,75);text.draw(c,"DRAFT "+(this.doc.dirty?"UNSAVED":"SAVED")+" / "+m.width+"X"+m.height+" / "+this.cursor.x+","+this.cursor.y,6,346,75);if(this.error){ui.window(c,8,110,464,100);text.draw(c,text.wrap(this.error,73).join("\n"),14,120,73);}
  }
 }
 G.editor.MapEditorState=MapEditorState;
}(window.GBTRPG));
