(function(G){
 "use strict";
 class SpellLabState {
  constructor(dependencies){Object.assign(this,dependencies);const fixture=G.data.SpellLabScenario.create();this.balance=fixture.balance;this.illegalTiles=[];this.battle=new G.states.BattleState(fixture.scenario);this.battle.terrain=this.options();this.board=new G.rendering.BattleRenderer(this);this.id="labWizard";this.battle.startTurn(this.id);this.cursor={...this.battle.state.positions[this.id]};this.mode="map";this.elapsed=0;this.interaction=null;this.ends=[];}
  show(title,items){this.title=title;this.list=new G.ui.SelectableList(items,12);this.mode="list";}
  options(){return{balance:this.balance,rounding:Math.ceil,inBounds:(x,y)=>x>=0&&y>=0&&x<12&&y<10,occupiable:(x,y)=>!this.illegalTiles.some(p=>p.x===x&&p.y===y),prayerDecision:()=>false};}
  animate(){this.battle.playAnimation({frames:3,durations:[180,180,180],loop:false},frame=>{this.renderer.clear();this.ui.page(this.renderer.ctx,"BATTLE EFFECT",["RESOLVING ACTION","FRAME "+(frame+1),"ANIMATION FINISHES BEFORE MAP"],0);});this.mode="map";}
  menu(){if(this.battle.state.pendingCounter)return this.counterChoice();const b=this.battle,s=b.state,u=s.units[this.id],alive=G.systems.BattleStatusSystem.active(u);if(u.tactical.escapeRequired){this.show("ESCAPE REQUIRED",G.systems.FlyingSystem.destinations(s,this.id,this.options()).map(p=>({label:"ESCAPE TO "+p.x+","+p.y,run:()=>{b.escape(this.id,p,this.options());this.cursor={...p};this.mode="map";}})));return;}this.show("DEBUG / "+u.name,[
   ...(u.tactical.escapeRequired?G.systems.FlyingSystem.destinations(s,this.id,this.options()).map(p=>({label:"ESCAPE TO "+p.x+","+p.y,run:()=>{b.escape(this.id,p,this.options());this.cursor={...p};this.mode="map";}})):[]),
   ...(alive&&!u.tactical.escapeRequired?[{label:"MAGIC",run:()=>this.families()},{label:"MOVE TO CURSOR",run:()=>{const p=s.positions[this.id],steps=[];for(let x=p.x;x!==this.cursor.x;x+=Math.sign(this.cursor.x-p.x))steps.push([Math.sign(this.cursor.x-p.x),0]);for(let y=p.y;y!==this.cursor.y;y+=Math.sign(this.cursor.y-p.y))steps.push([0,Math.sign(this.cursor.y-p.y)]);b.move(this.id,steps,{...this.options(),canEnter:this.options().occupiable});this.interaction={active:G.systems.PortalSystem.availability(b.state,this.id).allowed,unitId:this.id};this.mode="map";}}]:[]),
   ...(G.systems.PortalSystem.availability(s,this.id).allowed?[{label:"ENTER PORTAL",run:()=>{b.enterPortal(this.id);this.cursor={...b.state.positions[this.id]};this.mode="map";}}]:[]),
   ...(alive?[{label:"DEBUG SPELL COUNTER",run:()=>this.counterDemo()},{label:"DEBUG FLY ESCAPE",run:()=>this.flyDemo(false)},{label:"DEBUG FLY STRANDED",run:()=>this.flyDemo(true)}]:[]),
   {label:"END / NEXT OWN TURN",run:()=>{b.endTurn(this.id);if(!b.state.presentation.pendingWinner&&!["DEAD","AWOL"].includes(b.state.units[this.id].tactical.life))b.startTurn(this.id);this.mode="map";}},
   {label:"DEBUG DAMAGE CURSOR UNIT",run:()=>{const target=G.systems.PortalSystem.occupant(b.state,this.cursor);G.campaign.Validation.assert(target,"select an occupied tile");b.damage(target.id,100,{rounding:Math.ceil,prayerDecision:()=>false});this.animate();}},
   {label:"DEBUG SECONDARY MAGE",run:()=>this.secondary("mage")},{label:"DEBUG SECONDARY CLERIC",run:()=>this.secondary("cleric")},
   {label:"EXIT SPELL LAB",run:()=>this.onReturn()}
  ]);}
  counterDemo(){const b=this.battle,s=b.state,u=s.units[this.id];G.campaign.Validation.assert(u.faction==="PLAYER","player selection demo only");b.command(w=>G.campaign.AbilityLoadoutSystem.set(w.units[this.id],"reactionId","spellCounter"));const attacker=Object.values(s.units).find(x=>x.faction!==u.faction&&G.systems.BattleStatusSystem.active(x));G.campaign.Validation.assert(attacker,"enemy required");b.command(w=>{w.positions[attacker.id]={x:w.positions[this.id].x+1,y:w.positions[this.id].y};});b.resolveCounters(this.id,attacker.id,{...this.options(),attackId:"labAttack"+b.state.counterRecords.length,canCounter:true,roll:()=>0,spellEligible:()=>true});this.counterChoice();}
  counterChoice(){const p=this.battle.state.pendingCounter;this.show("SPELL COUNTER / CHOOSE LV1",p.eligibleSpellIds.map(id=>({label:G.data.SPELLS[id].name,run:()=>{this.battle.chooseCounter(id,this.options());this.animate();}})));}
  flyDemo(stranded){const b=this.battle,p=b.state.positions[this.id];this.illegalTiles=stranded?G.systems.TargetingSystem.diamond(p,2).filter(q=>Math.max(Math.abs(q.x-p.x),Math.abs(q.y-p.y))<=1):[{...p}];b.startTurn(this.id);b.cast(this.id,"fly",null,p,this.options());this.animate();}
  secondary(id){this.battle.command(s=>G.campaign.AbilityLoadoutSystem.set(s.units[this.id],"secondaryClassId",id));this.mode="map";}
  families(){const s=this.battle.state,group=G.systems.ActionCommandSystem.categories(s.units[this.id],s.turns[this.id]).find(g=>g.command==="MAGIC");this.show("MAGIC",(group?.families||[]).map(f=>({label:f.name,run:()=>this.show(f.name,f.levels.map(e=>({label:e.name+" / "+e.owningClassId.toUpperCase(),run:()=>this.methods(e.abilityId)})))})));}
  methods(id){this.spellId=id;const u=this.battle.state.units[this.id],spell=G.systems.MagicSystem.definition(id,this.balance),options=G.systems.SpellMenuSystem.castingOptions(u,{abilityId:id},()=>G.systems.MagicSystem.methods(u,spell));if(!options.length)return this.target(null);this.show("CASTING METHOD",options.map(o=>({label:o.name,run:()=>this.target(o.id)})));}
  target(method){this.method=method;this.ends=[];this.mode="target";}
  confirmTarget(){if(G.data.SPELLS[this.spellId].effect==="PORTAL"){this.ends.push({...this.cursor});if(this.ends.length<2)return;this.battle.cast(this.id,this.spellId,this.method,this.ends,this.options());}else this.battle.cast(this.id,this.spellId,this.method,{...this.cursor},this.options());this.animate();}
  update(ms=0){this.elapsed+=ms;this.battle.update(ms);const action=this.input.consumeAction();if(this.battle.state.presentation.phase==="ANIMATION")return;
   try{if(this.battle.state.presentation.phase==="BANNER"){if(action==="cancel"||action==="confirm")this.onReturn();return;}if(this.mode==="error"){if(action){if(this.battle.state.pendingCounter)this.counterChoice();else this.mode="map";}return;}
    if(this.mode==="list"){if(action==="up"||action==="down")this.list.move(action==="up"?-1:1);if(action==="confirm")this.list.selected?.run();if(action==="cancel"&&!this.battle.state.pendingCounter)this.mode="map";return;}
    const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[action];if(d){this.cursor.x=Math.max(0,Math.min(11,this.cursor.x+d[0]));this.cursor.y=Math.max(0,Math.min(9,this.cursor.y+d[1]));}
    if(action==="select"&&this.mode==="map"){const ids=Object.keys(this.battle.state.positions);this.id=ids[(ids.indexOf(this.id)+1)%ids.length];this.battle.command(s=>s.controlledUnitId=this.id);this.cursor={...this.battle.state.positions[this.id]};this.interaction=null;}
    if(action==="confirm")this.mode==="target"?this.confirmTarget():this.menu();if(action==="cancel"){if(this.mode==="target")this.mode="map";else this.onReturn();}
   }catch(e){this.error=e.message;this.mode="error";}
  }
  render(){const b=this.battle;if(b.state.presentation.phase==="ANIMATION"){b.cutIn?.render();return;}if(this.mode==="list"){this.renderer.clear();this.ui.list(this.renderer.ctx,this.title,this.list,b.state.pendingCounter?"Z CHOOSE COUNTER SPELL":"Z OK  X BACK");return;}if(this.mode==="error"){this.renderer.clear();this.ui.page(this.renderer.ctx,"COMMAND REJECTED",this.text.wrap(this.error,48),0);return;}
   const targeting=this.mode==="target"?G.systems.MagicSystem.resolve(b.state.units[this.id],this.spellId,this.method,this.options()):null;
   this.board.draw(b.state,this.cursor,this.interaction,this.elapsed,targeting?{rangeTiles:G.systems.TargetingSystem.targetTiles(b.state.positions[this.id],targeting.castingRange,this.options().inBounds),effectTiles:G.systems.TargetingSystem.affectedTiles(this.cursor,targeting.effectRadius)}:null,this.illegalTiles);if(this.mode==="target"){const cast=G.systems.MagicSystem.resolve(b.state.units[this.id],this.spellId,this.method,this.options());this.text.draw(this.renderer.ctx,"TARGET RANGE "+cast.castingRange+" RADIUS "+cast.effectRadius+(cast.effect==="PORTAL"?" END "+(this.ends.length+1):""),8,218,50);}
   if(b.state.presentation.phase==="MAP_RETURN")b.mapRendered();
  }
 }
 G.states.SpellLabState=SpellLabState;
}(window.GBTRPG));
