(function (G) {
  "use strict";
  G.config.CAMPAIGN = Object.freeze({ maxSquadUnits: 12, initialDay: 1, schemaVersion: 8 });
  G.config.RESOURCES = Object.freeze({ recruitIntervalDays: 7, shopPriceMultiplier: 1, personalCapacity: 4 });
  G.campaign.Phases = Object.freeze(["PLANNING", "ORDER_LOCK", "MOVEMENT_INTENT", "COLLISION_DETECTION", "RESOLUTION", "WORLD_UPDATE", "DAY_ADVANCE"]);
  G.campaign.Faction = Object.freeze({ PLAYER: "PLAYER", ZEON: "ZEON" });
  G.campaign.Controller = Object.freeze({ NEUTRAL: "NEUTRAL", PLAYER: "PLAYER", ZEON: "ZEON" });
  G.campaign.Allegiance = Object.freeze({ NEUTRAL: "NEUTRAL", PLAYER: "PLAYER" });
  G.campaign.Events = Object.freeze(Object.fromEntries([
    "AWOL_RETURNED", "AWOL_RETURN_UNRESOLVED", "TREASURY_CHANGED", "LOCATION_INCOME_COLLECTED", "ITEM_PURCHASED", "ITEM_ASSIGNED", "ITEM_EQUIPPED", "ITEM_RELEASED",
    "SHIPMENT_CREATED", "SHIPMENT_REROUTED", "SHIPMENT_INTERCEPTED", "SHIPMENT_DELIVERED", "TRAVELER_MOVED", "TRAVELER_ORDER_QUEUED", "TRAVELER_ORDER_CANCELLED", "UNIT_INTERCEPTED", "RECRUIT_POOL_REFRESHED", "UNIT_RECRUITED", "CHARACTER_LEVEL_CHANGED", "CLASS_CHANGED", "ABILITY_PURCHASED", "ABILITY_LOADOUT_CHANGED", "DEBUG_PROGRESSION_CHANGED",
    "DAY_ADVANCED", "LOCATION_CONTROL_CHANGED", "POLITY_JOINED", "SQUAD_CREATED",
    "SQUAD_DISMISSED", "SQUAD_STATIONED", "SQUAD_MOVED", "SQUAD_MEMBERS_CHANGED",
    "ROUTE_AVAILABILITY_CHANGED", "ORDER_QUEUED", "ORDER_CANCELLED", "ORDERS_LOCKED",
    "MOVEMENT_INTENT_CREATED", "MOVEMENT_CONFLICT_DETECTED", "BATTLE_REQUESTED",
    "BATTLE_RESULT_APPLIED", "SQUAD_DEFEATED", "END_DAY_RESOLUTION_STARTED",
    "END_DAY_RESOLUTION_COMPLETED", "CAMPAIGN_PHASE_CHANGED", "WORLD_UPDATED"
  ].map(name => [name, name])));
}(window.GBTRPG));
