(function(G){
 "use strict";
 const E=G.editor,V=G.campaign.Validation,F=E.AuthoredFiles;
 // Shared with the optional offline asset-installation verifier.
 G.debug.authoringPersistenceFixture=function(){
  const doc=new E.EditorDocument(G.campaign.createDemo());
  doc.command(d=>{
   d.format="legacy metadata field";d.notes={author:"Map designer",nested:["keep",{value:3}]};d.entities.push({id:"anchor",x:1,y:1,extra:"keep"});d.world.locations.granseal.questAssociations=["storyGate"];
   for(const [id,controller]of [["mapA","PLAYER"],["mapB","ZEON"]]){
    const m=E.BattleMapAuthoring.create(id,31,30,{controller,storyKeys:["storyGate"]});
    m.name="Valley / "+id;m.tiles=m.tiles.map(row=>row.map(()=>"grassland"));
    const variant=E.BATTLE_TILES.grassland.variants.at(-1).id;m.tiles[5][7]={terrainId:"grassland",variantId:variant};
    for(const side of m.approaches)for(const group of ["FRONT","BACK"])m.deployment[side].positions[group]=Array.from({length:6},(_,i)=>({x:2+i*3,y:(side==="NORTH"?2:25)+(group==="FRONT"?1:0)}));
    const unit=V.clone(doc.campaign.state.units.sara),equipment=Object.values(G.campaign.InventorySystem.equipmentDefinitions(doc.campaign.state,unit.id)).map(i=>i.id);
    m.specialDeployments=[{id:"visitor",x:20,y:20,faction:"WILDERNESS",unit,equipment,annotation:{value:"retain full snapshot"}}];m.requiredPoints=[{x:21,y:20,purpose:"protected"}];m.metadata=JSON.parse('{"__proto__":{"retained":true},"note":"quotes \\\" / Unicode 雪 / ${data} / </script>"}');
    d.battleMaps[id]=m;
   }
   d.world.locations.granseal.battleMaps=["mapB","mapA"];d.nextId=42;
  });return doc;
 };
 G.debug.runAuthoringPersistenceTests=function(){
  const results=[],test=(name,fn)=>{try{fn();results.push({name:"AUTHORING "+name,pass:true});}catch(e){results.push({name:"AUTHORING "+name,pass:false,error:e.message});}},check=(value,message="assertion failed")=>{if(!value)throw Error(message);},same=(a,b)=>check(F.json(a)===F.json(b),"semantic data differs"),reject=fn=>{let error;try{fn();}catch(e){error=e;}check(error,"expected rejection");return error;};
  const fresh=()=>new E.EditorDocument(G.campaign.createDemo()),fixture=G.debug.authoringPersistenceFixture;
  const memory=()=>{const data={};return{data,getItem:key=>data[key]||null,setItem:(key,value)=>data[key]=value};};
  const registry=d=>{const r=new E.AuthoredRegistry();r.registerCampaign(F.campaignAsset(d.data));for(const m of Object.values(d.data.battleMaps))r.registerBattle(m);return r;};
  const atomic=(d,text)=>{const before=d.data,dirty=d.dirty;reject(()=>d.import(text,true));check(d.data===before&&d.dirty===dirty,"failed import changed draft");};
  const shell=d=>{const game={campaign:d.campaign,input:new G.core.Input(null,new G.core.LocalStore("test.",null)),text:{wrap:s=>[s]},states:{},campaignMap:{},assets:{},renderer:{},ui:{}};const h=new E.DeveloperShell(game);h.document=d;return h;};
  const choose=(h,label)=>{const f=h.overlay.items().find(f=>f.label===label);check(f,"missing option "+label);f.run();};
  test("LEGACY V1 RAW BACKUP IMPORT",()=>{const a=fixture(),b=fresh();b.import(a.json());same(b.data,a.data);check(b.data.version===1);});
  test("FULL PORTABLE BACKUP ROUND TRIP",()=>{const a=fixture(),b=fresh();b.import(a.portable());same(b.data,a.data);check(b.validate(b.data));});
  test("CAMPAIGN ROUND TRIP INCLUDES REFERENCES AND DEPENDENCIES",()=>{const a=fixture(),b=fresh();b.import(a.portable("CAMPAIGN"));same(b.data,a.data);});
  test("CAMPAIGN IMPORT RETAINS UNREFERENCED DESTINATION MAPS",()=>{const a=fixture(),b=fresh(),id=b.createBattleMap("granseal",30,30,{controller:null,storyKeys:[]});b.import(a.portable("CAMPAIGN"));check(b.data.battleMaps[id]);same(b.data.world,a.data.world);});
  test("INDIVIDUAL MAP PRESERVES ALL FIELDS",()=>{const a=fixture(),b=fresh(),world=b.data.world;b.import(a.portable("BATTLE_MAP","mapA"));same(b.data.battleMaps.mapA,a.data.battleMaps.mapA);same(b.data.world,world);check(Object.keys(b.data.battleMaps).length===1);});
  test("COLLECTION ROUND TRIP PRESERVES MULTIPLE MAP IDS",()=>{const a=fixture(),b=fresh();b.import(a.portable("BATTLE_MAPS"));same(b.data.battleMaps,a.data.battleMaps);});
  test("LOCATION SELECTION SEMANTICS SURVIVE ROUND TRIP",()=>{const a=fixture(),b=fresh();b.import(a.portable());for(const [controller,id]of [["PLAYER","mapA"],["ZEON","mapB"]])check(E.AuthoredContent.select(b.data.world.locations.granseal,b.data.battleMaps,{controller,story:{storyGate:true}}).id===id);check(E.AuthoredContent.select(b.data.world.locations.granseal,b.data.battleMaps,{controller:"PLAYER"}).status==="NO_APPLICABLE_STATIC_MAP");});
  test("COLLISION REQUIRES EXPLICIT REPLACEMENT",()=>{const a=fixture(),b=fixture(),before=b.data;reject(()=>b.import(a.portable("BATTLE_MAP","mapA")));check(b.data===before);a.battle("mapA",m=>m.name="REPLACED");b.import(a.portable("BATTLE_MAP","mapA"),true);check(b.data.battleMaps.mapA.name==="REPLACED");same(b.data.world,before.world);});
  test("CAMPAIGN DEPENDENCY COLLISIONS LISTED",()=>{const d=fixture(),plan=d.prepareImport(d.portable("CAMPAIGN"));same(plan.conflicts,["mapA","mapB"]);});
  test("STALE IMPORT PLAN REFUSED",()=>{const d=fixture(),plan=d.prepareImport(d.portable());d.paint(0,0,"f");const before=d.data;reject(()=>d.applyImport(plan,true));check(d.data===before);});
  test("NEXT ID SURVIVES FULL BACKUP",()=>{const a=fixture(),b=fresh();b.import(a.portable());check(b.createBattleMap("granseal",30,30,{controller:null,storyKeys:[]})==="battleMap42");});
  test("EQUIVALENT OBJECT ORDERS EXPORT IDENTICALLY",()=>{const a=fixture(),reverse=x=>Array.isArray(x)?x.map(reverse):x&&typeof x==="object"?Object.fromEntries(Object.entries(x).reverse().map(([k,v])=>[k,reverse(v)])):x,b=new E.EditorDocument(a.campaign,reverse(a.data));for(const kind of ["DOCUMENT","CAMPAIGN","BATTLE_MAPS","BATTLE_MAP"])check(a.portable(kind,"mapA")===b.portable(kind,"mapA"));same(a.shippingFiles(),b.shippingFiles());});
  test("LEGACY BROWSER KEY RESTORES V1 DATA",()=>{const a=fixture(),s=memory(),b=fresh();s.setItem("shining-farce.editor.v1",a.json());b.store=new G.core.LocalStore("shining-farce.",s);b.restore();same(b.data,a.data);check(!b.dirty);});
  test("BROWSER SAVE CHANGES ONLY EDITOR KEY",()=>{const d=fixture(),s=memory(),r=registry(d),shipping=F.json(r.assemble(d.campaign)),campaign=F.json(d.campaign.snapshot());s.data["shining-farce.campaign"]="KEEP";d.store=new G.core.LocalStore("shining-farce.",s);d.battle("mapA",m=>m.name="LOCAL DRAFT");check(d.save());same(Object.keys(s.data).sort(),["shining-farce.campaign","shining-farce.editor.v1"]);check(s.data["shining-farce.campaign"]==="KEEP"&&F.json(r.assemble(d.campaign))===shipping&&F.json(d.campaign.snapshot())===campaign);});
  test("FAILED BROWSER SAVE RETAINS DIRTY DRAFT",()=>{const d=fixture(),before=d.data;d.store=new G.core.LocalStore("x.",{setItem(){throw Error("quota denied");}});check(!d.save()&&d.dirty&&d.data===before&&d.store.error==="quota denied");});
  test("FAILED BROWSER RESTORE RETAINS DRAFT",()=>{const d=fixture(),before=d.data;d.store=new G.core.LocalStore("x.",{getItem(){throw Error("access denied");}});check(reject(()=>d.restore()).message.includes("access denied")&&d.data===before&&d.dirty);});
  test("CORRUPT BROWSER PAYLOAD REFUSED ATOMICALLY",()=>{const d=fixture(),before=d.data;d.store=new G.core.LocalStore("x.",{getItem:()=>'{"version":99}'});reject(()=>d.restore());check(d.data===before);});
  test("INCOMPLETE DRAFT SAVES AND EXPORTS BUT CANNOT SHIP",()=>{const a=fresh();a.createBattleMap("granseal",30,30,{controller:null,storyKeys:[]});a.store=new G.core.LocalStore("x.",memory());check(a.save());const b=fresh();b.import(a.portable());same(a.data,b.data);reject(()=>b.shippingFiles());reject(()=>F.battleScript(Object.values(b.data.battleMaps)[0]));});
  for(const [name,change]of [
   ["UNSUPPORTED EDITOR VERSION",d=>d.version=2],["MISSING FIELD",d=>delete d.entities],["DANGLING MAP REFERENCE",d=>d.world.locations.granseal.battleMaps.push("absent")],["INVALID CAMPAIGN ROUTE",d=>Object.values(d.world.routes)[0].locationAId="absent"],["INVALID TERRAIN",d=>d.battleMaps.mapA.tiles[0][0]="unknown"],["INVALID VARIANT",d=>d.battleMaps.mapA.tiles[0][0]={terrainId:"grassland",variantId:"unknown"}],["INCOMPLETE SPECIAL DEFINITION",d=>delete d.battleMaps.mapA.specialDeployments[0].unit.currentClassId]
  ])test(name+" IMPORT IS ATOMIC",()=>{const d=fixture(),bad=V.clone(d.data);change(bad);atomic(d,JSON.stringify(bad));});
  test("MALFORMED JSON AND JAVASCRIPT REFUSED",()=>{const d=fixture();for(const text of ["{bad", "window.GBTRPG.data.AUTHORED_CONTENT = {};", "null", "[]"])atomic(d,text);});
  test("ARRAY CANNOT REPLACE BATTLE MAP DICTIONARY",()=>{const d=fresh(),bad=V.clone(d.data);bad.battleMaps=[];atomic(d,JSON.stringify(bad));});
  for(const [name,change]of [["VERSION",p=>p.version=2],["FORMAT",p=>p.format="OTHER"],["KIND",p=>p.kind="UNKNOWN"],["MISSING MAPS",p=>delete p.maps],["DUPLICATE MAP IDS",p=>p.maps.push(V.clone(p.maps[0]))]])test("PORTABLE "+name+" REJECTED",()=>{const d=fixture(),p=JSON.parse(d.portable("BATTLE_MAPS"));change(p);atomic(d,JSON.stringify(p));});
  test("CAMPAIGN DEPENDENCY MISSING REFUSED",()=>{const d=fixture(),p=JSON.parse(d.portable("CAMPAIGN"));p.maps.pop();atomic(d,JSON.stringify(p));});
  test("CAMPAIGN ASSET VERSION AND DUPLICATE INDEX REFUSED",()=>{const d=fixture();for(const change of [p=>p.campaign.version=2,p=>p.campaign.battleMapIds.push("mapA")]){const p=JSON.parse(d.portable("CAMPAIGN"));change(p);atomic(d,JSON.stringify(p));}});
  test("INDIVIDUAL FILE CANNOT CONTAIN TWO MAPS",()=>{const d=fixture(),p=JSON.parse(d.portable("BATTLE_MAPS"));p.kind="BATTLE_MAP";atomic(d,JSON.stringify(p));});
  test("SPLIT REGISTRY ASSEMBLES COMPLETE SHIPPING DOCUMENT",()=>{const d=fixture();same(registry(d).assemble(d.campaign),d.data);});
  test("REGISTRATION ORDER DOES NOT CHANGE ASSEMBLY",()=>{const d=fixture(),r=new E.AuthoredRegistry();r.registerBattle(d.data.battleMaps.mapB);r.registerBattle(d.data.battleMaps.mapA);r.registerCampaign(F.campaignAsset(d.data));same(r.assemble(d.campaign),registry(d).assemble(d.campaign));});
  test("DUPLICATE REGISTRATION LATCHES STARTUP FAILURE",()=>{const d=fixture(),r=registry(d);reject(()=>r.registerBattle(d.data.battleMaps.mapA));reject(()=>r.assemble(d.campaign));});
  test("DUPLICATE CAMPAIGN REGISTRATION REFUSED",()=>{const d=fixture(),r=registry(d);reject(()=>r.registerCampaign(F.campaignAsset(d.data)));reject(()=>r.assemble(d.campaign));});
  test("MALFORMED REGISTRATION LATCHES STARTUP FAILURE",()=>{const d=fixture(),r=registry(d),map=V.clone(d.data.battleMaps.mapA);delete map.tiles;reject(()=>r.registerBattle(map));reject(()=>r.assemble(d.campaign));});
  test("MISSING BATTLE SCRIPT FAILS COMPLETE ASSEMBLY",()=>{const d=fixture(),r=new E.AuthoredRegistry();r.registerCampaign(F.campaignAsset(d.data));r.registerBattle(d.data.battleMaps.mapA);reject(()=>r.assemble(d.campaign));});
  test("EXTRA UNINDEXED BATTLE SCRIPT REFUSED",()=>{const d=fixture(),r=registry(d),m=V.clone(d.data.battleMaps.mapA);m.id="extra";r.registerBattle(m);reject(()=>r.assemble(d.campaign));});
  test("MISSING CAMPAIGN SCRIPT FAILS EVEN WITHOUT MAPS",()=>{const r=new E.AuthoredRegistry();reject(()=>r.assemble(G.campaign.createDemo(),null,true));r.useDemo();check(r.assemble(G.campaign.createDemo(),null,true)===null);});
  test("EMPTY SPLIT REGISTRY ACCEPTS LEGACY MONOLITH",()=>{const d=fixture();same(new E.AuthoredRegistry().assemble(d.campaign,d.data,true),d.data);});
  test("MALFORMED LEGACY INPUT CANNOT SILENTLY FALL BACK",()=>{const r=new E.AuthoredRegistry();r.useDemo();for(const value of [false,0,"",[],{version:99}])reject(()=>r.assemble(G.campaign.createDemo(),value,true));});
  test("MIXED LEGACY AND SPLIT CONTENT REFUSED",()=>{const d=fixture();reject(()=>registry(d).assemble(d.campaign,d.data));});
  test("INCOMPLETE REGISTERED MAP CANNOT INITIALIZE",()=>{const d=fresh();d.createBattleMap("granseal",30,30,{controller:null,storyKeys:[]});reject(()=>registry(d).assemble(d.campaign));});
  test("SHIPPING RETAINS CAPACITY COLLISION AND SPECIAL CHECKS",()=>{for(const change of [m=>m.deployment.NORTH.positions.FRONT.pop(),m=>m.deployment.NORTH.positions.BACK[0]=m.deployment.NORTH.positions.FRONT[0],m=>m.specialDeployments.push(V.clone(m.specialDeployments[0]))]){const d=fixture();d.battle("mapA",change);reject(()=>d.shippingFiles());}});
  test("NORMAL GAME INITIALIZES SPLIT CONTENT AND EDITOR SOURCE",()=>{const previous={registry:G.data.AUTHORED_MAPS,legacy:G.data.AUTHORED_CONTENT,visuals:G.data.WORLD_VISUALS},runtime={...G.core.DeveloperRuntime};try{const d=fixture();d.addLocation(0,0);d.resize("SOUTH",1);G.data.AUTHORED_MAPS=registry(d);G.data.AUTHORED_CONTENT=null;const game=new G.core.Game({},{});game.resetCurrent();same(game.battleProviders.staticMaps,d.data.battleMaps);same(game.campaign.definitions,E.AuthoredContent.definitions(d.data));same(G.data.WORLD_VISUALS,d.data.visuals);same(new E.DeveloperShell(game).getDocument().data,d.data);check(game.campaign.state.schemaVersion===8);}finally{G.data.AUTHORED_MAPS=previous.registry;G.data.AUTHORED_CONTENT=previous.legacy;G.data.WORLD_VISUALS=previous.visuals;Object.assign(G.core.DeveloperRuntime,runtime);}});
  test("WINDOWS ASSET FILENAMES ARE DISTINCT AND SAFE",()=>{const ids=["MapA","mapA","mapa","map_41","map-41","CON"],paths=ids.map(F.battlePath);check(new Set(paths.map(p=>p.toLowerCase())).size===ids.length);for(const id of ["../map","a/b","__proto__"])reject(()=>F.battlePath(id));});
  test("ZIP OUTPUT IS DETERMINISTIC AND HAS AN END DIRECTORY",()=>{const d=fixture(),a=E.EditorFiles.zip(d.shippingFiles()),b=E.EditorFiles.zip(d.shippingFiles());check(a.length===b.length&&a.every((v,i)=>v===b[i]));check(new DataView(a.buffer).getUint32(a.length-22,true)===0x06054b50);});
  test("ZIP REFUSES DUPLICATE OR TRAVERSAL PATHS",()=>{for(const files of [[{path:"../x",text:""}],[{path:"a",text:""},{path:"a",text:""}]])reject(()=>E.EditorFiles.zip(files));});
  test("FILE PICKER CANCELLATION LEAVES DOCUMENT UNCHANGED",()=>{const d=fixture(),before=d.data,events={};let cancelled=false;const dom={createElement:()=>({addEventListener:(key,fn)=>events[key]=fn,click(){}})};E.EditorFiles.import(()=>{throw Error("unexpected import");},()=>{throw Error("unexpected error");},()=>cancelled=true,dom);events.cancel();check(cancelled&&d.data===before);});
  test("UI COLLISION CANCEL THEN CONFIRM PRESERVES REFERENCES",()=>{const d=fixture(),h=shell(d),before=d.data,original=E.EditorFiles.import;try{const replacement=fixture();replacement.battle("mapA",m=>m.name="UPDATED");E.EditorFiles.import=onText=>onText(replacement.portable("BATTLE_MAP","mapA"));h.importFile(()=>{});check(h.overlay.items().some(f=>f.label==="REPLACE EXISTING MAP ID: mapA"));choose(h,"CANCEL / KEEP CURRENT DRAFT");check(d.data===before);h.importFile(()=>{});choose(h,"CONFIRM IMPORT / REPLACE LISTED IDS");check(d.data.battleMaps.mapA.name==="UPDATED");same(d.data.world,before.world);}finally{E.EditorFiles.import=original;}});
  test("UI INVALID IMPORT REPORTS FAILURE WITHOUT REPLACEMENT",()=>{const d=fixture(),h=shell(d),before=d.data,original=E.EditorFiles.import;try{E.EditorFiles.import=onText=>onText("{bad");h.importFile(()=>{});check(h.overlay.title==="IMPORT REJECTED"&&d.data===before);}finally{E.EditorFiles.import=original;}});
  test("UI INCOMPLETE SHIPPING EXPORT DOES NOT DOWNLOAD",()=>{const d=fresh(),h=shell(d),original=E.EditorFiles.download;let downloads=0;try{d.createBattleMap("granseal",30,30,{controller:null,storyKeys:[]});E.EditorFiles.download=()=>downloads++;h.files(()=>{});h.overlay.index=h.overlay.items().findIndex(f=>f.label==="EXPORT SHIPPING PACKAGE / ZIP");h.input.enqueueAction("confirm");h.overlay.update();check(downloads===0&&h.overlay.error);}finally{E.EditorFiles.download=original;}});
  test("UI BROWSER SAVE REPORTS LOCAL SCOPE",()=>{const d=fixture(),h=shell(d);d.store=new G.core.LocalStore("x.",memory());h.files(()=>{});choose(h,"SAVE WORKING COPY IN THIS BROWSER");check(h.overlay.title==="BROWSER WORKING COPY SAVED"&&h.overlay.items().some(f=>f.label==="PROJECT / SHIPPING FILES ARE UNCHANGED."));});
  test("UI RELOADS INSTALLED SOURCE ONLY AFTER CONFIRMATION",()=>{const d=fixture(),h=shell(d),source=d.data;h.game.authoredContent=source;d.battle("mapA",m=>m.name="DRAFT");h.files(()=>{});choose(h,"RELOAD INSTALLED CONTENT INTO EDITOR");check(d.data.battleMaps.mapA.name==="DRAFT");choose(h,"YES / CONFIRM");same(d.data,source);check(!d.dirty);});
  test("IMPORTED MAP CAN BE ASSOCIATED AND DETACHED",()=>{const d=fresh(),h=shell(d);d.import(fixture().portable("BATTLE_MAP","mapA"));const editor=new E.MapEditorState(h,"locations");editor.battleMaps("granseal");choose(h,"ASSOCIATE / REMOVE EXISTING MAP REFERENCES");const field=h.overlay.items()[0];field.set(true);check(d.data.world.locations.granseal.battleMaps.includes("mapA"));field.set(false);check(!d.data.world.locations.granseal.battleMaps.includes("mapA")&&d.data.battleMaps.mapA);});
  return results;
 };
}(window.GBTRPG));
