(function(G){
  "use strict";
  G.debug.runClassFoundationTests=function(){
    const out=[],V=G.campaign.Validation,F=G.campaign.CharacterGrowthSystem,P=G.campaign.ClassProgressionSystem,L=G.campaign.AbilityLoadoutSystem,A=G.campaign.AbilityLearningSystem,I=G.campaign.InventorySystem,T=G.systems.TurnSystem;
    const check=(x,m="assertion failed")=>{if(!x)throw Error(m);},same=(a,b)=>check(JSON.stringify(a)===JSON.stringify(b),"values differ"),copy=V.clone;
    const reject=fn=>{let caught=false;try{fn();}catch(e){caught=true;}check(caught,"expected rejection");};
    const test=(name,fn)=>{try{fn();out.push({name,pass:true});}catch(e){out.push({name,pass:false,error:e.message});}};
    function unit(classId="fighter",raceId="HUMAN",id="mc",faction="PLAYER"){return{id,name:id,typeId:"swordsman",faction,status:"ACTIVE",unassignedLocationId:null,...F.simulateRecruitGrowth({raceId,currentClassId:classId,characterLevel:3,seed:321})};}
    function learn(u,id){const a=G.data.ABILITIES[id],p=P.progress(u,a.classId);P.earn(u,a.classId,Math.max(0,G.config.CLASSES.thresholds[a.level-1]-p.lifetimeCP));if(!u.learnedAbilityIds.includes(id))u.learnedAbilityIds.push(id);return u;}
    function load(u,id){learn(u,id);L.set(u,{SUPPORT:"supportId",REACTION:"reactionId",MOVEMENT:"movementId"}[G.data.ABILITIES[id].category],id);return u;}
    function campaign(u=unit()){const c=G.campaign.createDemo(),s=c.snapshot();s.units.mc=u;return new G.campaign.Campaign(c.definitions,s);}
    function fixtures(fn){const old=G.data.ITEMS;G.data.ITEMS={...old};
      const def=(id,slot,kind,weight,family=null,atk=null)=>({id,name:id,category:slot==="armor"?"ARMOR":kind==="SHIELD"?"SHIELD":"WEAPON",equipmentSlot:slot,equipmentKind:kind,weight,weaponFamily:family,weaponAttack:atk,modifiers:{},priceG:1,shopTier:1});
      Object.assign(G.data.ITEMS,{testSword:def("testSword","weapon","MELEE","MEDIUM","SWORD",10),testHeavy:def("testHeavy","weapon","MELEE","HEAVY","AXE",20),testBow:def("testBow","weapon","RANGED","LIGHT","BOW",6),testArmor:def("testArmor","armor",null,"HEAVY"),testShield:def("testShield","offHand","SHIELD",null)});
      try{return fn();}finally{G.data.ITEMS=old;}
    }
    function item(w,id,definitionId,owner,state="PERSONAL"){w.itemInstances[id]={id,definitionId,ownerFaction:w.units[owner].faction,state,place:{type:"UNIT",id:owner},assignedUnitId:null};return id;}
    function world(){const a=unit("thief","HUMAN","actor"),b=unit("knight","HUMAN","target","ZEON");for(const id of ["stealItem","stealAccessory","stealOffHand","stealWeapon","stealArmor"])learn(a,id);return{units:{actor:a,target:b},itemInstances:{}};}
    test("CLASS DATA HAS EIGHT CONCRETE DISCIPLINES",()=>same(Object.values(G.data.CLASSES).filter(c=>c.playable).map(c=>c.id),["fighter","knight","thief","archer","alchemist","mage","cleric","wizard"]));
    test("FINALIZED GROWTH AND DEFAULT COSTS ARE CONFIGURED",()=>{same(G.data.CLASSES.fighter.growth,{str:1});same(G.data.CLASSES.knight.growth,{str:1,con:1});same(G.data.CLASSES.thief.growth,{agi:1});for(const a of Object.values(G.data.ABILITIES))check(G.campaign.AbilityCostSystem.cost(a)>0);});
    test("CP THRESHOLDS AND CAP",()=>{G.config.CLASSES.thresholds.forEach((n,i)=>{check(P.level(n)===i+1);if(n>0)check(P.level(n-1)===i);});check(P.level(99999)===10);});
    test("CP EARNING INCREASES BOTH BALANCES",()=>{const u=unit();P.earn(u,"fighter",105);same(u.classProgress.fighter,{lifetimeCP:105,currentCP:105,classLevel:2,entryGrantCP:0});});
    test("MAX CLASS LEVEL STILL EARNS CURRENT CP",()=>{const u=unit();P.earn(u,"fighter",2700);P.earn(u,"fighter",100);check(u.classProgress.fighter.currentCP===2800&&u.classProgress.fighter.classLevel===10);});
    test("PURCHASE SPENDS ONLY CURRENT CP",()=>{const a=G.data.ABILITIES.powerAttack,old=a.costCP;try{a.costCP=70;const u=unit();P.earn(u,"fighter",250);A.purchase(u,a.id);same(u.classProgress.fighter,{lifetimeCP:250,currentCP:180,classLevel:3,entryGrantCP:0});}finally{if(old===undefined)delete a.costCP;else a.costCP=old;}});
    test("EXPLICIT UNRESOLVED COST CANNOT MEAN FREE",()=>{const a=G.data.ABILITIES.powerAttack;try{a.costCP=null;const u=unit();P.earn(u,"fighter",1000);check(A.eligibility(u,"powerAttack").reason==="PURCHASE COST UNRESOLVED");reject(()=>A.purchase(u,"powerAttack"));}finally{delete a.costCP;}});
    test("CLASS LEVEL DOES NOT GRANT ABILITIES",()=>{const u=unit();P.earn(u,"fighter",2700);same(u.learnedAbilityIds,[]);same(L.actions(u),[]);});
    test("PRIMARY ACTION CP ALL TO CURRENT CLASS",()=>{const u=learn(unit(),"powerAttack");same(P.attribution(u,"powerAttack",7),{fighter:7});});
    test("SECONDARY CP SPLIT AND ODD CURRENT PREFERENCE",()=>{const u=learn(unit(),"stealItem");L.set(u,"secondaryClassId","thief");same(P.attribution(u,"stealItem",7),{fighter:4,thief:3});same(P.attribution(u,"stealItem",8),{fighter:4,thief:4});});
    test("REACTION OR SUPPORT INFLUENCE EARNS NO CP",()=>{const u=load(learn(unit(),"stealItem"),"guard");L.set(u,"secondaryClassId","thief");const before=P.progress(u,"knight").lifetimeCP;const r=P.awardAction(u,{executionId:"passive-influence",legal:true,executed:true,abilityId:"stealItem",triggeredBy:"guard",successful:true,meaningful:true},{calculate:()=>7});same(r.recipients,{fighter:4,thief:3});check(P.progress(u,"knight").lifetimeCP===before);for(const id of ["guard","movePlusOne","strengthTraining"])same(P.attribution(u,id,7),{});});
    test("CP CALCULATOR DECIDES EXECUTED FAILURE AWARD",()=>{const u=learn(unit(),"powerAttack");let seen;const receipt={executionId:"miss",abilityId:"powerAttack",legal:true,executed:true,successful:false};const result=P.awardAction(u,receipt,{calculate:r=>{seen=r;return 5;}});check(seen.successful===false&&result.recipients.fighter===5);check(P.awardAction(u,receipt).status==="UNRESOLVED_FORMULA");});
    test("NO GENERIC BATTLE COMPLETION CP",()=>{const u=unit(),before=copy(u);P.awardAction(u,{event:"BATTLE_COMPLETED",successful:true,meaningful:true},{calculate:()=>100});same(u,before);});
    test("KNIGHT REQUIRES THIS CHARACTER FIGHTER THREE",()=>{const u=unit();P.earn(u,"fighter",249);check(!P.availability(u,"knight").allowed);P.earn(u,"fighter",1);check(P.availability(u,"knight").allowed);check(!P.availability(unit(),"knight").allowed);});
    test("MULTIPLE PREREQUISITES COMPOSE",()=>{const u=unit();P.earn(u,"knight",700);check(!P.prerequisites(u,G.data.CLASS_PREREQUISITE_EXAMPLES.paladin).every(r=>r.met));P.earn(u,"cleric",700);check(P.prerequisites(u,G.data.CLASS_PREREQUISITE_EXAMPLES.paladin).every(r=>r.met));});
    test("RECRUIT CLASS INDEPENDENT OF RECLASS UNLOCK",()=>{const c=campaign(unit("knight"));check(c.state.units.mc.currentClassId==="knight"&&!P.availability(c.state.units.mc,"knight").allowed);});
    test("CLASS CHANGE PRESERVES GROWTH LEARNING AND DAY",()=>{const u=learn(unit(),"powerAttack"),c=campaign(u),before=copy(c.state.units.mc);c.changeClass("mc","thief");check(c.state.day===1&&c.state.units.mc.currentClassId==="thief");same(c.state.units.mc.basePrimary,before.basePrimary);same(c.state.units.mc.learnedAbilityIds,before.learnedAbilityIds);});
    test("PRIMARY FOLLOWS CLASS SECONDARY PURCHASED ONLY",()=>{const u=learn(unit(),"powerAttack");learn(u,"stealItem");L.set(u,"secondaryClassId","thief");same(L.actions(u).map(a=>a.id),["powerAttack","stealItem"]);u.currentClassId="knight";same(L.actions(u).map(a=>a.id),["stealItem"]);});
    test("LOADOUT CATEGORY AND ONE SLOT ENFORCED",()=>{const u=learn(learn(unit(),"counter"),"guard");L.set(u,"reactionId","counter");L.set(u,"reactionId","guard");check(u.abilityLoadout.reactionId==="guard");reject(()=>L.set(u,"supportId","counter"));reject(()=>L.set(u,"primaryClassId","thief"));reject(()=>L.set(u,"movementId","fleetFooted"));reject(()=>L.set(u,"secondaryClassId","fighter"));reject(()=>L.set(u,"secondaryClassId","constructor"));});
    test("SUPPORT GROWTH AFFECTS ONLY FUTURE EVENTS",()=>{const a=G.data.ABILITIES.strengthTraining,old=a.effect.bonus;try{a.effect.bonus=3;const u=load(unit(),"strengthTraining"),before=copy(u.basePrimary),plain=copy(u);L.set(plain,"supportId",null);same(u.basePrimary,before);F.advanceLevel(u);F.advanceLevel(plain);check(u.basePrimary.str===plain.basePrimary.str+3);same(u.growthRngState,plain.growthRngState);}finally{a.effect.bonus=old;}});
    test("UNRESOLVED GROWTH SUPPORT REPORTS NO INVENTED BONUS",()=>{const u=load(unit(),"strengthTraining");same(G.campaign.AbilityModifierSystem.growth(u),{});check(G.data.ABILITIES.strengthTraining.implementation==="DEFERRED");});
    test("CLASS EQUIPMENT FAMILY AND WEIGHT SEPARATE",()=>fixtures(()=>{const e=G.campaign.EquipmentEligibility;check(e.allows(unit(),G.data.ITEMS.testSword)&&!e.allows(unit(),G.data.ITEMS.testHeavy));check(e.allows(unit("knight"),G.data.ITEMS.testHeavy)&&e.allows(unit("knight"),G.data.ITEMS.testShield));check(e.allows(unit("thief"),G.data.ITEMS.testBow)&&!e.allows(unit(),G.data.ITEMS.testBow));}));
    test("SUPPORT GRANTS DO NOT BYPASS RACIAL PROHIBITIONS",()=>fixtures(()=>{const e=G.campaign.EquipmentEligibility,u=load(unit("thief"),"heavyWeaponTraining");check(e.allows(u,G.data.ITEMS.testHeavy));u.raceId="BEASTMAN";check(!e.allows(u,G.data.ITEMS.testHeavy));check(e.allows(u,G.data.ITEMS.charm));}));
    test("TWO HANDED DOUBLES WEAPON ATK ONLY",()=>fixtures(()=>{const u=load(unit("knight"),"twoHanded"),before=copy(u.basePrimary),s=G.campaign.CharacterStatsSystem.deriveStats(u,[G.data.ITEMS.testSword]);check(s.weaponAttack===20&&s.str===u.basePrimary.str);same(u.basePrimary,before);check(!G.campaign.EquipmentEligibility.allows(u,G.data.ITEMS.testShield));}));
    test("OFF HAND AND TWO HANDED LOADOUT RECONCILE SAFELY",()=>fixtures(()=>{const u=learn(unit("knight"),"twoHanded"),c=campaign(u),s=c.snapshot();item(s,"testA","testSword","mc","EQUIPPED");item(s,"testB","testShield","mc","EQUIPPED");const loaded=new G.campaign.Campaign(c.definitions,s);loaded.setAbilityLoadout("mc","supportId","twoHanded");check(loaded.state.itemInstances.testB.state==="PERSONAL"&&loaded.state.itemInstances.testA.state==="EQUIPPED");}));
    test("CLASS CHANGE RETAINS NOW ILLEGAL GEAR",()=>fixtures(()=>{const c=campaign(unit("knight")),s=c.snapshot();item(s,"testA","testHeavy","mc","EQUIPPED");const loaded=new G.campaign.Campaign(c.definitions,s);loaded.changeClass("mc","thief");check(loaded.state.itemInstances.testA.state==="PERSONAL"&&loaded.state.itemInstances.testA.place.id==="mc");}));
    test("EQUIPPED ITEMS DO NOT USE CARRIED CAPACITY",()=>fixtures(()=>{const w=world();item(w,"s","testShield","target","EQUIPPED");check(I.personal(w,"target").length===0&&I.capacity(w,"target")===4);}));
    test("DEEP POCKETS REMOVAL PRESERVES OVERFLOW",()=>{const c=campaign(load(unit("thief"),"deepPockets"));for(let n=0;n<5;n++)c.assignItem(c.purchase("granseal","herb"),"mc");check(I.capacity(c.state,"mc")===5);c.setAbilityLoadout("mc","supportId",null);check(I.personal(c.state,"mc").length===5&&!I.canAcquire(c.state,"mc"));const before=copy(c.state),id=c.purchase("granseal","herb");reject(()=>c.assignItem(id,"mc"));check(I.personal(c.state,"mc").length===5);check(new G.campaign.Campaign(c.definitions,c.snapshot()).state.units.mc.abilityLoadout.supportId===null);});
    for(const [a,b]of [["ATTACK","MAGIC"],["ATTACK","STEAL"],["STEAL","EQUIP"]])test("MAJOR ACTION EXCLUDES "+a+" THEN "+b,()=>{const t=T.start(5);T.consume(t,a);reject(()=>T.consume(t,b));check(t.remainingMov===5&&!t.ended);});
    test("ALCHEMIST ITEM EXCEPTION HOOK",()=>{const t=T.start(5),policy={itemOutsideMajor:true};T.consume(t,"ITEM",null,policy);T.consume(t,"ATTACK",null,policy);T.consume(t,"ITEM",null,policy);reject(()=>T.consume(t,"MAGIC",null,policy));});
    test("SKILLS ORDER AND ACTION MAJOR DISTINCTION",()=>{const u=learn(learn(unit(),"powerAttack"),"protect");L.set(u,"secondaryClassId","knight");const t=T.start(5);same(G.systems.ActionCommandSystem.categories(u,t).map(c=>c.command),["ATTACK","SKILLS","ITEM","EQUIP","TRADE","END TURN"]);check(!T.consumesMajor("SKILLS",G.data.ABILITIES.protect));check(T.consumesMajor("SKILLS",G.data.ABILITIES.powerAttack));});
    test("STEAL CATEGORY ONLY WITH PURCHASED AVAILABLE ACTION",()=>{const u=unit("thief");check(!G.systems.ActionCommandSystem.categories(u,T.start(5)).some(c=>c.command==="STEAL"));learn(u,"stealItem");check(G.systems.ActionCommandSystem.categories(u,T.start(5)).some(c=>c.command==="STEAL"));});
    test("TACTICAL EQUIP CHANGES ONE ITEM PER MAJOR ACTION",()=>fixtures(()=>{const w=world(),t=T.start(7);item(w,"a","testSword","target");item(w,"b","testShield","target");G.systems.TacticalEquipmentSystem.change(w,"target","a",false,t);check(w.itemInstances.a.state==="EQUIPPED"&&w.itemInstances.b.state==="PERSONAL");reject(()=>G.systems.TacticalEquipmentSystem.change(w,"target","b",false,t));check(t.remainingMov===7);}));
    test("TACTICAL UNEQUIP RETAINS ITEM WITH FULL INVENTORY",()=>fixtures(()=>{const w=world();for(let n=0;n<4;n++)item(w,"i"+n,"herb","target");item(w,"s","testSword","target","EQUIPPED");G.systems.TacticalEquipmentSystem.change(w,"target","s",true,T.start(5));check(I.personal(w,"target").length===5&&w.itemInstances.s.place.id==="target");}));
    test("STEAL TARGET CATEGORIES ARE EXACT",()=>fixtures(()=>{const w=world(),t=T.start(5),pairs=[["stealItem","herb","PERSONAL"],["stealAccessory","charm","EQUIPPED"],["stealOffHand","testShield","EQUIPPED"],["stealWeapon","testSword","EQUIPPED"],["stealArmor","testArmor","EQUIPPED"]];for(const [a,d,state]of pairs)item(w,a,d,"target",state);for(const [a]of pairs)for(const [b]of pairs)check(G.systems.StealSystem.eligibility(w,"actor","target",a,b,t).allowed===(a===b));}));
    test("FULL INVENTORY DISABLES ORDINARY STEAL",()=>{const w=world();for(let n=0;n<4;n++)item(w,"i"+n,"herb","actor");item(w,"v","charm","target","EQUIPPED");check(!G.systems.StealSystem.eligibility(w,"actor","target","stealAccessory","v",T.start(5)).allowed);});
    test("DISARM RETAINS VICTIM OWNERSHIP EVEN IN OVERFLOW",()=>fixtures(()=>{const w=world();load(w.units.actor,"disarm");for(const owner of ["actor","target"])for(let n=0;n<4;n++)item(w,owner+n,"herb",owner);item(w,"s","testSword","target","EQUIPPED");const t=T.start(5),r=G.systems.StealSystem.resolveOutcome(w,"actor","target","stealWeapon","s",t,true);check(r.outcome==="DISARMED"&&r.damage===0&&!r.doubleAttack&&t.majorUsed);check(w.itemInstances.s.ownerFaction==="ZEON"&&w.itemInstances.s.place.id==="target"&&I.personal(w,"target").length===5);G.systems.TacticalEquipmentSystem.change(w,"target","s",false,T.start(5));check(w.itemInstances.s.state==="EQUIPPED");}));
    test("SUCCESSFUL STEAL TRANSFERS SAME PHYSICAL COPY",()=>{const w=world();item(w,"s","charm","target","EQUIPPED");const r=G.systems.StealSystem.resolveOutcome(w,"actor","target","stealAccessory","s",T.start(5),true);check(r.outcome==="STOLEN"&&r.damage===0&&!r.doubleAttack&&w.itemInstances.s.ownerFaction==="PLAYER"&&w.itemInstances.s.place.id==="actor"&&Object.keys(w.itemInstances).length===1);});
    test("FAILED STEAL CONSUMES ACTION WITHOUT DAMAGE OR TRANSFER",()=>{const w=world();item(w,"s","herb","target");const before=copy(w),t=T.start(5);const r=G.systems.StealSystem.resolveOutcome(w,"actor","target","stealItem","s",t,false);same(w,before);check(t.majorUsed&&!r.meaningful&&r.damage===0);});
    test("STEAL FORMULA UNRESOLVED FAST HANDS MODIFIES HOOK",()=>{const u=load(unit("thief"),"fastHands");check(G.systems.StealSystem.probability({actor:u}).probability===null);check(G.systems.StealSystem.probability({actor:u},()=>0.3).probability===0.6);});
    test("STEAL STORY RESTRICTION HOOK",()=>{const w=world();item(w,"s","herb","target");check(!G.systems.StealSystem.eligibility(w,"actor","target","stealItem","s",T.start(5),{itemEligible:()=>false}).allowed);});
    test("DOUBLE ATTACK UNRESOLVED AND UNIVERSAL CAP",()=>{const ctx={attacker:unit(),defender:unit(),command:"ATTACK",attackKind:"NORMAL"};check(G.systems.DoubleAttackSystem.probability(ctx).probability===null);check(G.systems.DoubleAttackSystem.probability(ctx,()=>0.99).probability===0.9);});
    test("FLURRY CENTRAL MODIFIER RESPECTS CAP",()=>{const ctx={attacker:load(unit("thief"),"flurry"),command:"ATTACK",attackKind:"NORMAL"};check(G.systems.DoubleAttackSystem.probability(ctx,()=>0.2).status==="UNRESOLVED_MODIFIER");check(G.systems.DoubleAttackSystem.probability(ctx,()=>0.2,n=>n+0.8).probability===0.9);});
    test("STEAL COUNTER AND SECOND ATTACK ARE NOT DOUBLE ELIGIBLE",()=>{for(const c of [{command:"STEAL",attackKind:"NORMAL",abilityId:"stealItem"},{command:"ATTACK",attackKind:"COUNTER"},{command:"ATTACK",attackKind:"SECOND"},{command:"SKILLS",attackKind:"NORMAL",abilityId:"feint"}])check(G.systems.DoubleAttackSystem.probability({attacker:unit(),...c},()=>0.8).probability===0);});
    test("THIEF MOV AND MOVE PLUS ONE COMPOSE",()=>{const u=unit("thief"),before=G.data.RACES.HUMAN.mov;check(G.campaign.CharacterStatsSystem.deriveStats(u).mov===7);load(u,"movePlusOne");check(G.campaign.CharacterStatsSystem.deriveStats(u).mov===8&&G.data.RACES.HUMAN.mov===before);});
    const open={canEnter:()=>true};
    test("MOVEMENT DOES NOT CONSUME MAJOR OR END TURN",()=>{const u=unit(),t=T.start(5),p={x:0,y:0};G.systems.TacticalMovementRules.traverse(u,p,t,[[1,0],[1,0]],open);check(!t.majorUsed&&t.remainingMov===3);T.consume(t,"ATTACK");G.systems.TacticalMovementRules.traverse(u,p,t,[[-1,0],[-1,0]],open);check(t.tilesMoved===4&&t.remainingMov===1&&!t.ended);});
    test("SKIRMISHER USES TRAVERSED TILES AT TURN END",()=>{const u=load(unit(),"skirmisher"),t=T.start(5),p={x:0,y:0};G.systems.TacticalMovementRules.traverse(u,p,t,[[1,0],[1,0],[-1,0],[-1,0]],open);T.end(t);const effects=G.systems.AbilityEffectHooks.endTurn(u,t);check(p.x===0&&effects.length===1&&effects[0].status==="UNRESOLVED_MODIFIER");});
    test("FLEET FOOTED ORTHOGONAL STAIRCASE DISCOUNT",()=>{const u=load(unit("thief"),"fleetFooted"),t=T.start(2),p={x:0,y:0};G.systems.TacticalMovementRules.traverse(u,p,t,[[1,0],[0,1],[1,0],[0,1]],open);check(t.remainingMov===0&&t.tilesMoved===4&&p.x===2&&p.y===2);});
    test("FLEET FOOTED STRAIGHT PATH NO MOV BONUS",()=>{const u=load(unit("thief"),"fleetFooted"),t=T.start(2),p={x:0,y:0};G.systems.TacticalMovementRules.traverse(u,p,t,[[1,0],[1,0]],open);check(t.remainingMov===0&&G.campaign.CharacterStatsSystem.deriveStats(u).mov===7);});
    test("FLEET FOOTED CANNOT CUT BLOCKED CORNER",()=>{const u=load(unit("thief"),"fleetFooted"),t=T.start(5),p={x:0,y:0},before=copy(t);reject(()=>G.systems.TacticalMovementRules.traverse(u,p,t,[[1,0],[0,1]],{canEnter:(x,y)=>!(x===1&&y===0)}));same(t,before);same(p,{x:0,y:0});reject(()=>G.systems.TacticalMovementRules.traverse(u,p,t,[[1,1]],open));});
    test("ALLY PASS THROUGH NOT OCCUPIED ENDPOINT",()=>{const u=unit(),t=T.start(5),p={x:0,y:0},ctx={...open,occupant:(x,y)=>x===1?{id:"ally",faction:"PLAYER"}:null};reject(()=>G.systems.TacticalMovementRules.traverse(u,p,t,[[1,0]],ctx));G.systems.TacticalMovementRules.traverse(u,p,t,[[1,0],[1,0]],ctx);check(p.x===2);});
    test("FLEET FOOTED NEVER PASSES ENEMIES",()=>{const u=load(unit(),"fleetFooted"),t=T.start(5);reject(()=>G.systems.TacticalMovementRules.traverse(u,{x:0,y:0},t,[[1,0],[0,1]],{...open,occupant:x=>x===1?{id:"enemy",faction:"ZEON"}:null}));});
    test("INDOMITABLE EXACT CEIL BOUNDARIES",()=>{const u=load(unit("knight"),"indomitable"),h=G.systems.AbilityEffectHooks;check(h.damage(u,9,83,42)===0&&h.damage(u,9,83,43)===43&&h.damage(u,10,83,42)===42);});
    test("STEADFAST ONLY BLOCKS ENEMY DISPLACEMENT",()=>{const u=load(unit("knight"),"steadfast"),h=G.systems.AbilityEffectHooks;check(!h.displacementAllowed(u,"ZEON")&&h.displacementAllowed(u,"PLAYER"));});
    test("FRIENDLY OFFENSIVE AREA IMMUNITY ONLY",()=>{const u=load(unit(),"battlefieldAwareness"),h=G.systems.AbilityEffectHooks;check(!h.magicAffected(u,{sourceFaction:"PLAYER",offensive:true,area:true}));check(h.magicAffected(u,{sourceFaction:"ZEON",offensive:true,area:true}));});
    test("CHIVALRY DYNAMIC DIAGONAL AURA",()=>{const u=load(unit("knight"),"chivalry"),h=G.systems.AbilityEffectHooks;check(h.auraDefense(u,{x:0,y:0},{x:1,y:1,faction:"PLAYER"},40)===2&&h.auraDefense(u,{x:0,y:0},{x:2,y:0,faction:"PLAYER"},40)===0);});
    test("ABILITY METADATA PRESERVES DISTINCT CRUSHING OPERATIONS",()=>{const a=G.data.ABILITIES;check(a.crushingBlow.effect.operations.length===2&&a.crushingBlow.effect.operations[0].operation==="ADD_TARGET_FULL_DEF_TO_DAMAGE");check(a.shieldBash.effect.stunChance===0.75&&a.cover.effect.chance===0.5&&a.thrust.effect.ignoreDefenseFraction===0.8);check(a.spearTechnique.name==="SPEAR TECHNIQUE");});
    test("DEFERRED POSITION AND REACTION RULES EXPLICIT",()=>{const a=G.data.ABILITIES;check(a.protect.majorAction===false&&a.holdTheLine.majorAction===false&&a.holdTheLine.effect.cancelOnAnySourceMovement);check(a.slipAway.effect.allowDecline&&a.slipAway.effect.aiDecisionHook&&a.slipAway.effect.movCost===0);check(G.systems.AbilityEffectHooks.executionStatus("protect")==="EFFECT_NOT_IMPLEMENTED");});
    test("SCHEMA FOUR MIGRATES CP AND SAFE LOADOUT DEFAULTS",()=>{const c=G.campaign.createDemo(),s=c.snapshot();s.schemaVersion=4;for(const u of [...Object.values(s.units),...Object.values(s.recruitPools).flat()]){delete u.learnedAbilityIds;delete u.abilityLoadout;}s.units.mc.classProgress={fighter:{cp:333,classLevel:3}};const n=new G.campaign.Campaign(c.definitions,s);check(n.state.schemaVersion===8);same(n.state.units.mc.classProgress.fighter,{lifetimeCP:333,currentCP:333,classLevel:3,entryGrantCP:0});same(n.state.units.mc.abilityLoadout,L.defaults());same(n.state.units.mc.basePrimary,s.units.mc.basePrimary);});
    test("LEGACY INDEPENDENT CLASS LEVEL CONSERVATIVELY PRESERVED",()=>{const c=G.campaign.createDemo(),s=c.snapshot();s.schemaVersion=4;s.units.mc.classProgress={fighter:{cp:91,classLevel:7}};const n=new G.campaign.Campaign(c.definitions,s);check(n.state.units.mc.classProgress.fighter.lifetimeCP===1350&&n.state.units.mc.classProgress.fighter.currentCP===1350&&n.state.units.mc.classProgress.fighter.classLevel===7);});
    test("NEW PROGRESSION LOADOUT ROUND TRIP",()=>{const c=campaign(load(learn(unit(),"stealItem"),"movePlusOne"));c.setAbilityLoadout("mc","secondaryClassId","thief");same(new G.campaign.Campaign(c.definitions,c.snapshot()).state,c.state);});
    test("INVALID CP LOADOUT AND DERIVED CLASS LEVEL REJECT",()=>{for(const mutate of [u=>u.classProgress.fighter={lifetimeCP:1,currentCP:2,classLevel:1,entryGrantCP:0},u=>u.classProgress.fighter={lifetimeCP:2700,currentCP:2,classLevel:9,entryGrantCP:0},u=>u.abilityLoadout.supportId="flurry",u=>u.abilityLoadout.primaryClassId="fighter"]){const u=unit();mutate(u);reject(()=>campaign(u));}});
    test("ACTIVE SCHEMA FOUR REJECTED WITHOUT RESET",()=>{const c=campaign();c.startEndDay();const s=c.snapshot();s.schemaVersion=4;const before=copy(s);reject(()=>new G.campaign.Campaign(c.definitions,s));same(s,before);});
    test("CP NEGATIVE OVERFLOW AND PURCHASE DUPLICATE REJECT",()=>{const u=unit();reject(()=>P.earn(u,"fighter",-1));P.earn(u,"fighter",Number.MAX_SAFE_INTEGER);const before=copy(u);reject(()=>P.earn(u,"fighter",1));same(u,before);const a=G.data.ABILITIES.powerAttack,old=a.costCP;try{a.costCP=1;A.purchase(u,a.id);reject(()=>A.purchase(u,a.id));}finally{if(old===undefined)delete a.costCP;else a.costCP=old;}});
    function scenario(w){return{participants:["PLAYER","ZEON"].map(faction=>({faction,units:Object.values(w.units).filter(u=>u.faction===faction).map(u=>({...copy(u),stats:I.stats(w,u.id),possessions:Object.values(w.itemInstances).filter(i=>i.place.type==="UNIT"&&i.place.id===u.id).map(i=>({instance:copy(i),definition:copy(G.data.ITEMS[i.definitionId])}))}))}))};}
    test("DETACHED BATTLE STEAL AND CP DO NOT MUTATE CAMPAIGN SNAPSHOT",()=>{const w=world();item(w,"s","charm","target","EQUIPPED");const snap=V.freeze(scenario(w)),before=copy(snap),b=new G.states.BattleState(snap),old=P.progress(w.units.actor,"thief").lifetimeCP;const result=b.resolveSteal("actor","target","stealAccessory","s",true,{}, {calculate:()=>7});check(result.cp.recipients.thief===7&&b.state.units.actor.classProgress.thief.lifetimeCP===old+7);check(b.state.itemInstances.s.place.id==="actor");same(snap,before);});
    test("BATTLE RULE COMMAND FAILURE IS ATOMIC",()=>{const w=world();item(w,"s","charm","target","EQUIPPED");const b=new G.states.BattleState(scenario(w)),before=copy(b.state);reject(()=>b.resolveSteal("actor","target","stealAccessory","s",true,{}, {calculate:()=>-1}));same(b.state,before);});
    test("EXECUTED ACTION CP RECEIPT CANNOT REPLAY",()=>{const b=new G.states.BattleState(scenario(world())),execution={executionId:"action1",legal:true,executed:true,abilityId:"stealItem",successful:true,meaningful:true};b.resolveActionCP("actor",execution,{calculate:()=>7});const before=copy(b.state);reject(()=>b.resolveActionCP("actor",execution,{calculate:()=>7}));same(b.state,before);});
    test("TACTICAL PATH ADAPTER REUSES EXISTING TERRAIN LEGALITY",()=>{const mover=new G.systems.MovementSystem(new G.systems.TerrainSystem({0:{passable:true},1:{passable:false}})),map={width:2,height:2,tiles:[[0,1],[0,0]]},u=load(unit(),"fleetFooted"),t=T.start(2),p={x:0,y:0};reject(()=>mover.tryTacticalPath(u,map,p,t,[[1,0],[0,1]]));mover.tryTacticalPath(u,map,p,t,[[0,1],[1,0]]);check(p.x===1&&p.y===1&&t.remainingMov===1);});
    test("CLASS MANAGEMENT LOCKED DURING END DAY",()=>{const c=campaign();c.startEndDay();const before=copy(c.state);reject(()=>c.changeClass("mc","thief"));reject(()=>c.setAbilityLoadout("mc","secondaryClassId","thief"));reject(()=>c.grantClassCPForInspection("mc","fighter",100));same(c.state,before);});
    return out;
  };
}(window.GBTRPG));
