(function(G){
 "use strict";
 G.debug.runDeploymentOceanTests=function(){
  const out=[],V=G.campaign.Validation,D=G.systems.DeploymentSystem,B=G.editor.BattleMapAuthoring,T=G.systems.BattleTerrainSystem,P=G.systems.PathfindingSystem;
  const check=(value,message="assertion failed")=>{if(!value)throw Error(message);},same=(a,b)=>check(JSON.stringify(a)===JSON.stringify(b),"values differ"),reject=fn=>{let error;try{fn();}catch(e){error=e;}check(error,"expected rejection");return error;};
  const test=(name,fn)=>{try{fn();out.push({name:"P8A "+name,pass:true});}catch(e){out.push({name:"P8A "+name,pass:false,error:e.message});}};
  const key=p=>p.x+","+p.y;
  function fixture(front=7,back=1){
   const f=G.data.BattleFoundationFixture.create(),template=f.scenario.participants[0].units[0];f.map=B.create("overflowFixture");f.map.tiles=f.map.tiles.map(row=>row.map(()=>"grassland"));
   for(const side of f.map.approaches)for(const category of ["FRONT","BACK"])f.map.deployment[side].positions[category]=Array.from({length:6},(_,n)=>({x:2+n*3,y:(side==="NORTH"?1:24)+(category==="FRONT"?3:0)+(n%2)}));
   f.overrides={labEnemy:"BACK"};f.scenario.participants[0].units=Array.from({length:front+back},(_,n)=>{const id="ordinary"+n;f.overrides[id]=n<front?"FRONT":"BACK";return{...V.clone(template),id};});
   return f;
  }
  const assign=f=>D.assign(f.map,f.scenario.participants,f.orientation,f.overrides,77);
  function prepare(f){return G.systems.BattleInitializationSystem.prepare({...f.scenario,locationId:"town"},{locations:{town:{id:"town",battleMaps:[f.map.id]}},routes:{}},{staticMaps:{[f.map.id]:f.map},orientation:()=>f.orientation,designations:f.overrides,seed:77});}
  const inPool=(f,p,category)=>f.map.deployment.NORTH.positions[category].some(q=>key(q)===key(p));
  function special(){return{id:"oceanVisitor",x:20,y:15,faction:"WILDERNESS",unit:V.clone(G.campaign.createDemo().state.units.sara),equipment:[]};}
  function moving(flying=false){const f=G.data.SpellLabScenario.create(),b=new G.states.BattleState(f.scenario),map=B.create("oceanMovement");map.tiles[10][10]="grassland";map.tiles[10][12]="grassland";b.command(s=>{s.positions.labWizard={x:10,y:10};s.turns.labWizard=G.systems.TurnSystem.start(4);if(flying)G.systems.FlyingSystem.grant(s.units.labWizard,{id:"FLYING"},"labCleric");});return{map,b,id:"labWizard"};}
  const context=m=>T.context(m.map,m.b.state.units[m.id],m.b.state);
  for(const [front,back]of [[1,1],[6,2],[7,1],[1,7],[7,5],[5,7],[12,0],[0,12],[6,6]])test("PREFERENCE AND OVERFLOW "+front+" FRONT / "+back+" BACK",()=>{
   const f=fixture(front,back),r=assign(f);check(B.validate(f.map).valid);const units=f.scenario.participants[0].units,fs=units.slice(0,front),bs=units.slice(front);
   check(fs.filter(u=>inPool(f,r.positions[u.id],"FRONT")).length===Math.min(front,6));check(bs.filter(u=>inPool(f,r.positions[u.id],"BACK")).length===Math.min(back,6));
   check(new Set(Object.values(r.positions).map(key)).size===front+back+2);check(Object.keys(r.positions).length===front+back+2);
   for(const u of units)check(inPool(f,r.positions[u.id],"FRONT")||inPool(f,r.positions[u.id],"BACK"));
  });
  test("BACK PREFERENCE RESERVED BEFORE FRONT OVERFLOW",()=>{const f=fixture(),r=assign(f);check(inPool(f,r.positions.ordinary7,"BACK"));check(inPool(f,r.positions.ordinary6,"BACK"));check(key(r.positions.ordinary7)!==key(r.positions.ordinary6));});
  test("NORMAL INITIALIZATION ACCEPTS EXHAUSTED PREFERRED CATEGORY",()=>{for(const counts of [[7,1],[1,7],[12,0],[0,12]]){const f=fixture(...counts),r=prepare(f);check(r.status==="READY");check(Object.keys(r.scenario.positions).length===counts[0]+counts[1]+2);}});
  test("DETERMINISTIC SEEDED OVERFLOW DOES NOT MUTATE INPUTS",()=>{const f=fixture(7,5),before=V.clone(f),r=assign(f);same(assign(f),r);same(f,before);check(r.rngState!==77);});
  test("EXTRA AUTHORED PREFERRED SPOT PREVENTS OVERFLOW",()=>{const f=fixture(7,1);f.map.deployment.NORTH.positions.FRONT.push({x:21,y:8});const r=assign(f);for(const u of f.scenario.participants[0].units.slice(0,7))check(inPool(f,r.positions[u.id],"FRONT"));});
  test("TOTAL VALID CAPACITY FAILURE IS ATOMIC",()=>{const f=fixture(7,5),original=G.data.RACES;f.map.deployment.NORTH.positions.BACK.forEach(p=>f.map.tiles[p.y][p.x]="forest");try{G.data.RACES={...original,HUMAN:{...original.HUMAN,terrainOverrides:{forest:{traversable:false}}}};const before=V.clone(f);check(B.validate(f.map).valid);check(reject(()=>prepare(f)).message.includes("total valid deployment capacity"));same(f,before);}finally{G.data.RACES=original;}});
  for(const category of ["FRONT","BACK"])test("FEWER THAN SIX "+category+" SPOTS STILL REJECTED",()=>{const f=fixture(1,1);f.map.deployment.NORTH.positions[category].pop();check(!B.validate(f.map).valid);check(prepare(f).status==="INVALID_AUTHORED_BATTLE_MAP");reject(()=>assign(f));});
  test("MISSING COMBINED AUTHORED CAPACITY DOES NOT INVENT POSITIONS",()=>{const f=fixture(7,5),before=V.clone(f.scenario);f.map.deployment.NORTH.positions.BACK.length=5;reject(()=>assign(f));same(f.scenario,before);});
  test("NONCONTIGUOUS UNEVEN AUTHORED COORDINATES REMAIN INTACT",()=>{const f=fixture(),before=V.clone(f.map.deployment),r=prepare(f);check(r.status==="READY");same(f.map.deployment,before);same(r.deployment.rows.PLAYER,before.NORTH.positions);});
  for(const conflict of ["CATEGORIES","SIDES","SPECIAL","SPECIALS"])test("START COLLISION "+conflict+" REJECTED BEFORE ASSIGNMENT",()=>{const f=fixture();if(conflict==="CATEGORIES")f.map.deployment.NORTH.positions.BACK[0]=V.clone(f.map.deployment.NORTH.positions.FRONT[0]);if(conflict==="SIDES")f.map.deployment.SOUTH.positions.BACK[0]=V.clone(f.map.deployment.NORTH.positions.FRONT[0]);if(conflict==="SPECIAL")f.map.specialDeployments=[{...special(),...f.map.deployment.NORTH.positions.BACK[5]}];if(conflict==="SPECIALS")f.map.specialDeployments=[special(),{...special(),id:"anotherSpecial"}];check(!B.validate(f.map).valid);reject(()=>assign(f));check(prepare(f).status==="INVALID_AUTHORED_BATTLE_MAP");});
  test("SPECIAL IS ADDITIONAL AND KEEPS ITS EXPLICIT COORDINATE",()=>{const f=fixture(12,0),s=special();f.map.specialDeployments=[s];const r=prepare(f);check(r.status==="READY"&&r.scenario.participants.length===2&&r.scenario.specialUnits.length===1);const id=r.scenario.specialUnits[0].id;same(r.scenario.positions[id],{x:s.x,y:s.y});check(Object.keys(r.scenario.positions).length===15);check(!Object.values(r.deployment.positions).some(p=>key(p)===key(s)));});
  test("SPECIAL CANNOT PROVIDE MISSING ORDINARY CAPACITY",()=>{const f=fixture(12,0);f.map.deployment.NORTH.positions.BACK.pop();f.map.specialDeployments=[special()];reject(()=>assign(f));check(prepare(f).status==="INVALID_AUTHORED_BATTLE_MAP");});
  test("OCEAN AUTHORITATIVE IDENTITY AND FUTURE OVERRIDE BOUNDARY",()=>{const d=G.data.BATTLE_TERRAIN.ocean;check(d.category==="IMPASSABLE"&&!d.traversable&&d.ruleStatus==="AUTHORITATIVE");check(G.editor.CAMPAIGN_TILES.w.terrainId==="ocean");check(Object.values(G.data.RACES).every(r=>!r.terrainOverrides?.ocean));});
  test("ORDINARY OCEAN TRANSIT FAILS ATOMICALLY",()=>{const m=moving(),before=m.b.state;reject(()=>m.b.move(m.id,[[1,0],[1,0]],context(m)));same(m.b.state,before);});
  test("ORDINARY OCEAN DESTINATION AND OCCUPANCY REJECTED",()=>{const m=moving();check(!context(m).canEnter(11,10)&&!context(m).occupiable(11,10));check(!T.canOccupy(m.map,m.b.state.units[m.id],11,10));reject(()=>m.b.move(m.id,[[1,0]],context(m)));});
  test("ORDINARY OCEAN DEPLOYMENT REJECTED BY MAP AND INITIALIZATION",()=>{const f=fixture(),p=f.map.deployment.NORTH.positions.FRONT[0];f.map.tiles[p.y][p.x]="ocean";check(!B.validate(f.map).valid);reject(()=>assign(f));check(prepare(f).status==="INVALID_AUTHORED_BATTLE_MAP");});
  test("ORDINARY SPECIAL CANNOT OCCUPY OCEAN",()=>{const f=fixture(),s=special();f.map.tiles[s.y][s.x]="ocean";f.map.specialDeployments=[s];check(!B.validate(f.map).valid);reject(()=>B.instantiate(f.map));check(prepare(f).status==="INVALID_AUTHORED_BATTLE_MAP");});
  test("FLYING OCEAN TRANSIT COSTS ONE PER TILE",()=>{const m=moving(true);check(T.canOccupy(m.map,m.b.state.units[m.id],11,10));m.b.move(m.id,[[1,0],[1,0]],context(m));same(m.b.state.positions[m.id],{x:12,y:10});check(m.b.state.turns[m.id].movSpent===2&&m.b.state.turns[m.id].remainingMov===2);});
  test("FLYING MAY END ON OCEAN",()=>{const m=moving(true);m.b.move(m.id,[[1,0]],context(m));same(m.b.state.positions[m.id],{x:11,y:10});check(m.b.state.turns[m.id].movSpent===1);});
  test("FLYING OCEAN DOES NOT BYPASS BOUNDS OR OCCUPANCY",()=>{const m=moving(true);check(!T.canOccupy(m.map,m.b.state.units[m.id],-1,0));m.b.command(s=>s.positions.labEnemy={x:11,y:10});reject(()=>m.b.move(m.id,[[1,0]],context(m)));m.b.command(s=>s.positions[m.id]={x:0,y:0});reject(()=>m.b.move(m.id,[[-1,0]],context(m)));});
  test("ORDINARY PATHFINDING CANNOT TRANSIT OR END ON OCEAN",()=>{const m=moving(),before=V.clone(m.b.state);for(const x of [11,12]){check(P.find(m.b.state,m.id,{x,y:10},context(m))===null);check(P.plan(m.b.state,m.id,{x,y:10},(s,id)=>T.context(m.map,s.units[id],s))===null);}same(m.b.state,before);});
  test("FLYING PATHFINDING USES OCEAN AT ONE MOV PER TILE",()=>{const m=moving(true),before=V.clone(m.b.state);same(P.find(m.b.state,m.id,{x:12,y:10},context(m)),[[1,0],[1,0]]);const plan=P.plan(m.b.state,m.id,{x:12,y:10},(s,id)=>T.context(m.map,s.units[id],s));check(plan.remainingMov===2);same(m.b.state,before);});
  test("FLY EXPIRATION ON OCEAN REQUIRES EXISTING ESCAPE",()=>{const m=moving(true);m.b.move(m.id,[[1,0]],context(m));m.b.expireStatus(m.id,"FLYING",context(m));check(m.b.state.units[m.id].tactical.escapeRequired);m.b.escape(m.id,{x:10,y:10},context(m));check(!m.b.state.units[m.id].tactical.escapeRequired);});
  test("FLY EXPIRATION WITHOUT LEGAL SHORE PRESERVES AWOL RULE",()=>{const m=moving(true);m.b.command(s=>s.positions[m.id]={x:20,y:20});m.b.expireStatus(m.id,"FLYING",context(m));check(m.b.state.units[m.id].tactical.life==="AWOL"&&!m.b.state.positions[m.id]);});
  test("LEGITIMATELY FLYING SPECIAL MAY INITIALIZE ON OCEAN",()=>{const f=fixture(),s=special(),original=G.data.RACES;try{G.data.RACES={...original,[s.unit.raceId]:{...original[s.unit.raceId],capabilities:["FLYING"]}};f.map.tiles[s.y][s.x]="ocean";f.map.specialDeployments=[s];check(B.validate(f.map).valid);const r=prepare(f);check(r.status==="READY");const u=r.scenario.specialUnits[0];same(r.scenario.positions[u.id],{x:s.x,y:s.y});check(G.systems.FlyingSystem.sources(u).length>0);}finally{G.data.RACES=original;}});
  for(const edge of ["NORTH","SOUTH","EAST","WEST"])test("CAMPAIGN AND BATTLE "+edge+" EXPANSION STILL FILLS OCEAN",()=>{const doc=new G.editor.EditorDocument(G.campaign.createDemo()),map=B.create("expansion"),expanded=B.resize(map,edge,1);doc.resize(edge,1);const v=doc.data.visuals;check(map.tiles.flat().every(t=>t==="ocean")&&expanded.tiles.flat().every(t=>t==="ocean"));check(edge==="NORTH"?v.rows[0]==="w".repeat(v.width):edge==="SOUTH"?v.rows.at(-1)==="w".repeat(v.width):v.rows.every(row=>row[edge==="WEST"?0:v.width-1]==="w"));});
  test("CAMPAIGN GRAPH ROUTES REMAIN INDEPENDENT OF DECORATIVE OCEAN",()=>{const c=G.campaign.createDemo(),before=c.findPath("granseal","grove"),doc=new G.editor.EditorDocument(c);const p=c.definitions.locations.granseal.mapPosition;doc.paint(p.x/16,p.y/16,"w");same(c.findPath("granseal","grove"),before);check(!G.data.BATTLE_TERRAIN[G.editor.CAMPAIGN_TILES.w.terrainId].traversable);});
  return out;
 };
}(window.GBTRPG));
