(function(G){
  "use strict";
  G.debug.runProgressionConsolidationTests=function(){
    const out=[],V=G.campaign.Validation,P=G.campaign.ClassProgressionSystem,F=G.campaign.CharacterGrowthSystem,L=G.campaign.AbilityLoadoutSystem,I=G.campaign.InventorySystem,J=G.systems.ItemSystem,T=G.systems.TurnSystem,E=G.campaign.EquipmentEligibility,R=G.systems.AbilityRequirementSystem,C=G.campaign.AbilityCostSystem,H=G.systems.AbilityEffectHooks;
    const check=(v,m="assertion failed")=>{if(!v)throw Error(m);},same=(a,b)=>check(JSON.stringify(a)===JSON.stringify(b),"values differ"),copy=V.clone,reject=fn=>{let caught=false;try{fn();}catch(e){caught=true;}check(caught,"expected rejection");};
    const test=(name,fn)=>{try{fn();out.push({name:"P5 "+name,pass:true});}catch(e){out.push({name:"P5 "+name,pass:false,error:e.message});}};
    const unit=(c="fighter",id="actor",level=1)=>({id,name:id,typeId:"swordsman",faction:"PLAYER",status:"ACTIVE",unassignedLocationId:null,...F.simulateRecruitGrowth({raceId:"HUMAN",currentClassId:c,characterLevel:level,seed:731})});
    function learn(u,id){const a=G.data.ABILITIES[id];P.earn(u,a.classId,Math.max(0,G.config.CLASSES.thresholds[a.level-1]-P.progress(u,a.classId).lifetimeCP));if(!u.learnedAbilityIds.includes(id))u.learnedAbilityIds.push(id);return u;}
    function load(u,id){learn(u,id);L.set(u,{SUPPORT:"supportId",MOVEMENT:"movementId",REACTION:"reactionId"}[G.data.ABILITIES[id].category],id);return u;}
    const receipt=(extra={})=>({executionId:"testExecution",legal:true,executed:true,cancelled:false,command:"ATTACK",successful:true,...extra});
    const world=(u=unit("alchemist"))=>({units:{actor:u,target:unit("fighter","target")},itemInstances:{}});
    function item(w,id,def="herb",owner="actor",state="PERSONAL"){w.itemInstances[id]={id,definitionId:def,ownerFaction:w.units[owner].faction,state,place:{type:"UNIT",id:owner},assignedUnitId:null};return id;}
    const effect=id=>G.data.ABILITIES[id].effect;
    const context=(...ids)=>({effects:ids.map(effect)});
    function fixtures(fn){const old=G.data.ITEMS;G.data.ITEMS={...old};const gear=(id,slot,kind,weight,family,tags=[])=>({id,name:id,category:slot==="armor"?"ARMOR":"WEAPON",equipmentSlot:slot,equipmentKind:kind,weight,weaponFamily:family,armorFamily:slot==="armor"?family:null,tags,modifiers:{},priceG:1,shopTier:1});
      Object.assign(G.data.ITEMS,{p5bow:gear("p5bow","weapon","RANGED","LIGHT","BOW"),p5heavy:gear("p5heavy","weapon","RANGED","HEAVY","BOW"),p5knife:gear("p5knife","weapon","MELEE","LIGHT","SWORD",["SHORT","STABBING"]),p5wand:gear("p5wand","weapon","MAGICAL","LIGHT","WAND"),p5robe:gear("p5robe","armor",null,"LIGHT","ROBE")});
      for(const [id,hp,mp]of [["p5small",6,0],["p5large",18,0],["p5huge",40,0],["p5mixed",7,5]])G.data.ITEMS[id]={id,name:id,category:"CONSUMABLE",restoration:{hp,mp},priceG:1,shopTier:1};
      G.data.ITEMS.p5buff={id:"p5buff",name:"test buff",category:"CONSUMABLE",temporaryStatBuff:{stats:["str","dex"],duration:2},priceG:1,shopTier:1};
      try{return fn();}finally{G.data.ITEMS=old;}}
    const curve=[100,125,150,175,200,225,250,275,300,350];
    curve.forEach((cost,n)=>test("LEVEL "+(n+1)+" DEFAULT PRICE",()=>check(C.cost({level:n+1})===cost)));
    test("EXPLICIT PRICE OVERRIDE AND UNRESOLVED",()=>{check(C.cost({level:4,costCP:93})===93&&C.cost({level:4,costCP:null})===null);});
    test("STANDARD PURCHASE PERMANENT AND NOT LIFETIME SPENDING",()=>{const u=unit();P.earn(u,"fighter",100);G.campaign.AbilityLearningSystem.purchase(u,"powerAttack");check(u.classProgress.fighter.currentCP===0&&u.classProgress.fighter.lifetimeCP===100&&u.learnedAbilityIds.includes("powerAttack"));reject(()=>G.campaign.AbilityLearningSystem.purchase(u,"powerAttack"));});
    test("CURRENT CP AND CLASS LEVEL EACH GATE PURCHASE",()=>{const u=unit();check(G.campaign.AbilityLearningSystem.eligibility(u,"powerAttack").reason==="INSUFFICIENT CURRENT CP");check(G.campaign.AbilityLearningSystem.eligibility(u,"feint").reason.startsWith("REQUIRES CLASS LV"));});
    for(const command of ["ATTACK","ITEM","EQUIP","TRADE"])test(command+" UNIVERSAL CP STAYS CURRENT",()=>{const u=load(unit(),"quickItems");L.set(u,"secondaryClassId","alchemist");const before=P.progress(u,"alchemist").lifetimeCP;const r=P.awardAction(u,receipt({command}),{calculate:()=>9});same(r.recipients,{fighter:9});check(P.progress(u,"alchemist").lifetimeCP===before);});
    for(const flags of [{legal:false},{executed:false},{cancelled:true},{executionId:null}])test("INVALID EXECUTION DOES NOT CALL CP CALCULATOR "+JSON.stringify(flags),()=>{const u=unit(),before=copy(u);P.awardAction(u,receipt(flags),{calculate:()=>{throw Error("must not call");}});same(u,before);});
    test("MAGIC AND STEAL ARE NOT UNIVERSAL CP CATEGORIES",()=>{const u=unit();for(const command of ["MAGIC","STEAL","SKILLS"])same(P.awardAction(u,receipt({command}),{calculate:()=>10}).recipients,{});});
    test("SPOOFED OWNER CANNOT REDIRECT PRIMARY CP",()=>{const u=learn(unit(),"powerAttack");const r=P.awardAction(u,receipt({abilityId:"powerAttack",owningClassId:"thief",accessSource:"SECONDARY"}),{calculate:()=>7});same(r.recipients,{fighter:7});check(r.receipt.owningClassId==="fighter");});
    test("SECONDARY FAILURES REACH CALCULATOR WITH OWNER",()=>{const u=learn(unit(),"stealItem");L.set(u,"secondaryClassId","thief");let seen;const r=P.awardAction(u,receipt({abilityId:"stealItem",successful:false}),{calculate:r=>{seen=r;return 7;}});same(r.recipients,{fighter:4,thief:3});check(!seen.successful&&seen.owningClassId==="thief"&&seen.accessSource==="SECONDARY");});
    test("ALL FIVE CLASSES HAVE NO INITIAL FREE CP",()=>{for(const c of ["fighter","knight","thief","archer","alchemist"]){check(G.data.CLASSES[c].initialCurrentCPGrant===null);same(unit(c).classProgress[c],{lifetimeCP:0,currentCP:0,classLevel:1,entryGrantCP:0});}});
    test("OPTIONAL GRANT ONLY CURRENT ONCE THROUGH SAVE AND RECLASS",()=>{const d=G.data.CLASSES.archer,old=d.initialCurrentCPGrant;try{d.initialCurrentCPGrant=100;const c=G.campaign.createDemo();c.changeClass("mc","archer");c.purchaseAbility("mc","aimedShot");c.changeClass("mc","thief");const n=new G.campaign.Campaign(c.definitions,c.snapshot());n.changeClass("mc","archer");same(n.state.units.mc.classProgress.archer,{lifetimeCP:0,currentCP:0,classLevel:1,entryGrantCP:100});check(n.state.units.mc.learnedAbilityIds.includes("aimedShot"));}finally{d.initialCurrentCPGrant=old;}});
    test("OPTIONAL GRANT NOT CHARACTER GROWTH OR CLASS LEVEL",()=>{const d=G.data.CLASSES.archer;try{d.initialCurrentCPGrant=350;const u=unit("archer");check(u.classProgress.archer.classLevel===1&&u.classProgress.archer.lifetimeCP===0&&u.characterLevel===1);G.campaign.CharacterValidation.progression(u);}finally{d.initialCurrentCPGrant=null;}});
    test("MISSING CURRENT CLASS GRANT MARKER REJECTED",()=>{const u=unit();delete u.classProgress.fighter;reject(()=>G.campaign.CharacterValidation.progression(u));});
    test("SECONDARY FIRST ACCESS IS ONCE ONLY",()=>{const c=G.campaign.createDemo(),d=G.data.CLASSES.archer;try{d.initialCurrentCPGrant=100;c.setAbilityLoadout("mc","secondaryClassId","archer");c.setAbilityLoadout("mc","secondaryClassId",null);c.setAbilityLoadout("mc","secondaryClassId","archer");check(c.state.units.mc.classProgress.archer.currentCP===100);}finally{d.initialCurrentCPGrant=null;}});
    function oldSave(s){s.schemaVersion=5;function walk(x){if(!x||typeof x!=="object")return;if(x.classProgress)for(const p of Object.values(x.classProgress))delete p.entryGrantCP;Object.values(x).forEach(walk);}walk(s);return s;}
    test("SCHEMA FIVE NO HISTORICAL FREE GRANTS",()=>{const c=G.campaign.createDemo();c.changeClass("mc","archer");c.grantClassCPForInspection("mc","archer",500);c.purchaseAbility("mc","aimedShot");const old=oldSave(c.snapshot()),before=copy(old),d=G.data.CLASSES.archer;try{d.initialCurrentCPGrant=100;const n=new G.campaign.Campaign(c.definitions,old);check(n.state.units.mc.classProgress.archer.currentCP===400&&n.state.units.mc.classProgress.archer.entryGrantCP===0);same(n.state.units.mc.learnedAbilityIds,c.state.units.mc.learnedAbilityIds);same(n.state.units.mc.basePrimary,c.state.units.mc.basePrimary);same(old,before);same(new G.campaign.Campaign(n.definitions,n.snapshot()).state,n.state);}finally{d.initialCurrentCPGrant=null;}});
    test("SCHEMA FIVE PRESERVES EVERY ACTIVE PHASE AND BATTLE QUEUE",()=>{const c=G.campaign.createDemo();c.loadDevelopmentScenario("multiple");c.startEndDay();let phases=0,battles=0;while(c.state.phase!=="PLANNING"){const old=oldSave(c.snapshot()),n=new G.campaign.Campaign(c.definitions,old);same(n.state,c.state);phases++;const pending=c.state.resolution.pendingBattleScenario;if(pending){c.applyBattleResult(G.campaign.PlaceholderBattleResolver.result(pending,"PLAYER"));battles++;}else c.stepResolution();check(phases<25);}check(battles===2);same(new G.campaign.Campaign(c.definitions,oldSave(c.snapshot())).state,c.state);});
    for(const [id,bonus]of Object.entries({fighter:{str:1},knight:{str:1,con:1},thief:{agi:1},archer:{dex:1},alchemist:{wis:1}}))test(id.toUpperCase()+" GROWTH ADDS AT N MINUS ONE EVENTS",()=>{const plain=F.simulateRecruitGrowth({raceId:"HUMAN",currentClassId:id,characterLevel:8,seed:731},{getGrowth:()=>({})}),u=unit(id,"actor",8);for(const k of G.config.CHARACTER_STATS.primaryKeys)check(u.basePrimary[k]===plain.basePrimary[k]+7*(bonus[k]||0));same(u.growthRngState,plain.growthRngState);});
    test("CLASS CHANGE DOES NOT RECALCULATE PAST BONUSES",()=>{const c=G.campaign.createDemo(),before=copy(c.state.units.mc);c.changeClass("mc","archer");same(c.state.units.mc.basePrimary,before.basePrimary);same(c.state.units.mc.growthRngState,before.growthRngState);});
    test("ARCHER UNLOCK AND MOV",()=>{check(P.availability(unit(),"archer").allowed&&G.campaign.ClassGrowthProvider.getMovementModifier("archer")===0);});
    test("ARCHER PERMISSIONS AND HEAVY BOW TRAINING",()=>fixtures(()=>{const u=unit("archer");check(E.allows(u,G.data.ITEMS.p5bow)&&!E.allows(u,G.data.ITEMS.p5heavy));load(u,"bowTraining");check(E.allows(u,G.data.ITEMS.p5heavy));u.raceId="BEASTMAN";check(!E.allows(u,G.data.ITEMS.p5heavy));}));
    test("ARCHER ACTIONS SHARE BOW REQUIREMENT",()=>fixtures(()=>{const u=unit("archer");for(const a of Object.values(G.data.ABILITIES).filter(a=>a.classId==="archer"&&a.category==="ACTION")){learn(u,a.id);check(!R.action(u,a.id,[]).allowed&&R.action(u,a.id,[G.data.ITEMS.p5bow]).allowed&&!R.action(u,a.id,[G.data.ITEMS.p5knife]).allowed);}}));
    test("SECONDARY ARCHER NEEDS LEGAL EQUIPPED BOW",()=>fixtures(()=>{const u=learn(unit("alchemist"),"aimedShot");L.set(u,"secondaryClassId","archer");check(!R.action(u,"aimedShot",[]).allowed);check(R.action(u,"aimedShot",[G.data.ITEMS.p5bow]).allowed);check(!R.action(u,"aimedShot",[G.data.ITEMS.p5heavy]).allowed);}));
    test("BACKSTAB REQUIRES GENERIC SHORT STABBING TAGS",()=>fixtures(()=>{const u=learn(unit("thief"),"backstab");check(R.action(u,"backstab",[G.data.ITEMS.p5knife]).allowed);check(!R.action(u,"backstab",[{...G.data.ITEMS.p5knife,tags:["SHORT"]}]).allowed);}));
    test("BOW REQUIREMENT SHOWN IN GROUP AVAILABILITY",()=>{const u=learn(unit("archer"),"aimedShot"),group=G.systems.ActionCommandSystem.categories(u,T.start(5)).find(c=>c.command==="SKILLS");check(!group.allowed&&!group.abilities[0].allowed);});
    test("COVERING FIRE PRE ATTACK NO SELF NO CAP NO DOUBLE",()=>fixtures(()=>{const u=load(unit("archer"),"coveringFire"),enemy={id:"enemy",faction:"ZEON"},ally={id:"ally",faction:"PLAYER"},bow=[G.data.ITEMS.p5bow],ctx={legalTarget:()=>true};for(let n=0;n<3;n++){const q=H.coveringFire(u,enemy,ally,bow,ctx);check(q.status==="QUALIFYING"&&q.chance===null&&q.timing==="BEFORE_ENEMY_ATTACK"&&q.activationLimit===null&&!q.isCounterattack&&!q.doubleAttackEligible);}check(H.coveringFire(u,enemy,u,bow,ctx).status==="INELIGIBLE");check(H.coveringFire(u,enemy,ally,[],ctx).status==="INELIGIBLE");check(H.coveringFire(u,enemy,ally,bow,{legalTarget:()=>false}).status==="INELIGIBLE");check(!H.pendingAttackAfterReaction(false).resolvePendingAttack&&H.pendingAttackAfterReaction(true).resolvePendingAttack);}));
    test("ARCHER HAS NO SUREFOOTED AND NO FREE FIRING MOVE",()=>{check(!G.data.CLASSES.archer.abilityIds.some(id=>id.toLowerCase()==="surefooted"));check(effect("firingPosition").movCost===null&&effect("firingPosition").timing===null&&effect("firingPosition").rangeBonus===1);});
    test("ALCHEMIST PERMISSIONS EXPLICITLY PROVISIONAL",()=>{check(G.data.CLASSES.alchemist.equipmentStatus==="PROVISIONAL"&&P.availability(unit(),"alchemist").allowed);});
    test("QUICK ITEMS ONLY EQUIPPED SUPPORT",()=>{const u=learn(unit("alchemist"),"quickItems");check(!G.campaign.AbilityModifierSystem.actionPolicy(u).itemOutsideMajor);L.set(u,"supportId","quickItems");check(G.campaign.AbilityModifierSystem.actionPolicy(u).itemOutsideMajor);});
    for(const command of ["ATTACK","MAGIC","STEAL"])test("QUICK ITEMS PLUS "+command,()=>{const u=load(unit(),"quickItems"),policy=G.campaign.AbilityModifierSystem.actionPolicy(u),t=T.start(5);T.consume(t,"ITEM",null,policy);T.consume(t,command,null,policy);T.consume(t,"ITEM",null,policy);check(t.majorUsed&&t.remainingMov===5);for(const c of ["ATTACK","MAGIC","STEAL","EQUIP"])check(!T.availability(t,c,null,policy).allowed);check(!T.availability(t,"SKILLS",G.data.ABILITIES.tossItem,policy).allowed);});
    for(const source of ["TOSS_ITEM","FORAGE_USE","FORAGE_THROW"])test(source+" BYPASSES CONSERVATION",()=>{const u=load(unit(),"conservation"),r=J.consumption(u,G.data.ITEMS.herb,source,{decide:()=>{throw Error("must bypass");}});check(r.consumed&&!r.preserved);});
    test("STORED FORAGE LATER ALLOWS CONSERVATION",()=>{const u=load(unit(),"conservation"),w=world(u),choice=J.forageChoice(w,"actor","STORE");check(choice.source==="ITEM"&&choice.table===null&&choice.canStore);check(J.consumption(u,G.data.ITEMS.herb,choice.source,{decide:()=>true}).preserved);});
    test("CONSERVATION UNKNOWN RETURNS NO MUTATION PLAN",()=>{const w=world(load(unit(),"conservation"));item(w,"h");const before=copy(w);check(J.plan(w,"actor","target","h").status==="UNRESOLVED_CONSERVATION");same(w,before);});
    test("POTENT HP TWO MP CEIL ONE QUARTER BONUS",()=>fixtures(()=>same(J.restoration(load(unit(),"potentRemedies"),G.data.ITEMS.p5mixed),{hp:14,mp:7})));
    test("EMERGENCY STRICT THRESHOLD AND QUALIFYING DAMAGE",()=>{const w=world(load(unit(),"emergencyMedicine"));item(w,"h");check(J.emergency(w,"actor",60,100,true).status==="INELIGIBLE");check(J.emergency(w,"actor",59,100,false).status==="INELIGIBLE");check(J.emergency(w,"actor",59,100,true).activationChance===1);});
    test("EMERGENCY STRONGEST WITHOUT OVERHEAL",()=>fixtures(()=>{const w=world(load(unit(),"emergencyMedicine"));item(w,"s","p5small");item(w,"l","p5large");item(w,"h","p5huge");check(J.emergency(w,"actor",20,50,true).itemId==="l");check(J.emergency(w,"actor",2,5,true).status==="NO_NONOVERHEALING_ITEM");}));
    test("EMERGENCY POTENT APPLIED BEFORE SELECTION",()=>fixtures(()=>{const w=world(load(load(unit(),"emergencyMedicine"),"potentRemedies"));item(w,"s","p5small");item(w,"l","p5large");const r=J.emergency(w,"actor",20,50,true);check(r.itemId==="s"&&r.healing===12);}));
    test("EMERGENCY ITEM CAN BE PRESERVED",()=>{const w=world(load(load(unit(),"emergencyMedicine"),"conservation"));item(w,"h");const selection=J.emergency(w,"actor",20,50,true),plan=J.plan(w,"actor","actor",selection.itemId,"EMERGENCY_MEDICINE",{decide:()=>true});J.commit(w,plan);check(plan.preserved&&!!w.itemInstances.h);});
    test("CATALYZE ONLY ACTUAL CONSUMPTION NO GROWTH EVENT",()=>fixtures(()=>{const w=world(load(unit(),"catalyze"));item(w,"b","p5buff");const before=copy(w.units.actor),p=J.plan(w,"actor","actor","b","ITEM",{decide:()=>true,chooseStat:()=>"dex"});J.commit(w,p);check(!w.itemInstances.b&&w.units.actor.basePrimary.dex===before.basePrimary.dex+1);check(w.units.actor.characterLevel===before.characterLevel&&w.units.actor.growthRngState===before.growthRngState);same(w.units.actor.classProgress,before.classProgress);}));
    test("PRESERVED BUFF SKIPS CATALYZE PERMANENT ROLL",()=>fixtures(()=>{const u=load(unit(),"catalyze"),calls=[],r=J.consumption(u,G.data.ITEMS.p5buff,"ITEM",{...context("conservation"),decide:k=>{calls.push(k);return true;}});same(calls,["conservation"]);check(r.permanentStat===null&&r.preserved);}));
    test("CATALYZE HEALING ITEM INELIGIBLE",()=>{check(J.consumption(load(unit(),"catalyze"),G.data.ITEMS.herb,"ITEM",{decide:()=>{throw Error("no buff roll");}}).permanentStat===null);});
    test("CATALYZE UNDEFINED CHANCE AND DURATION STAY NULL",()=>fixtures(()=>{check(effect("catalyze").chance===null&&effect("catalyze").durationExtension===null);check(J.consumption(load(unit(),"catalyze"),G.data.ITEMS.p5buff).status==="UNRESOLVED_CATALYZE");}));
    const statuses=[{id:"poison",negative:true,removable:true},{id:"slow",negative:true,removable:true},{id:"story",negative:true,removable:false},{id:"buff",negative:false,removable:true}];
    test("PURIFY REMOVES ONE ELIGIBLE STATUS ONLY",()=>{const u=load(unit(),"purifyingMedicine");check(J.purification(u,G.data.ITEMS.herb,statuses).status==="UNRESOLVED_PURIFICATION");same(J.purification(u,G.data.ITEMS.herb,statuses,{decide:()=>true,chooseStatus:()=>"slow"}).removeIds,["slow"]);});
    test("PANACEA ONLY CURATIVE AND REMOVABLE NEGATIVE",()=>{same(J.panacea({curative:true},statuses),["poison","slow"]);reject(()=>J.panacea(G.data.ITEMS.herb,statuses));});
    test("REFINE UNRESOLVED DOES NOT CONSUME INPUTS",()=>{const w=world();item(w,"a");item(w,"b");const before=copy(w);check(J.refinePlan(w,"actor","a","b").status==="UNRESOLVED_REFINE");same(w,before);reject(()=>J.refinePlan(w,"actor","a","a"));});
    test("REFINE RESOLVED FIXTURE TWO IDENTICAL TO ONE STRONGER",()=>fixtures(()=>{const w=world();item(w,"a","p5small");item(w,"b","p5small");item(w,"c","p5large");reject(()=>J.refinePlan(w,"actor","a","c",()=>({definitionId:"p5huge"})));const plan=J.refinePlan(w,"actor","a","b",()=>({definitionId:"p5large"})),id=J.commitRefine(w,plan);check(!w.itemInstances.a&&!w.itemInstances.b&&w.itemInstances[id].definitionId==="p5large"&&w.itemInstances[id].place.id==="actor");}));
    test("DEEP SATCHEL SAFE OVERFLOW ON UNEQUIP",()=>{const w=world(load(unit(),"deepSatchel"));for(let n=0;n<5;n++)item(w,"i"+n);check(I.capacity(w,"actor")===5);L.set(w.units.actor,"supportId",null);check(I.personal(w,"actor").length===5&&!I.canAcquire(w,"actor"));});
    const positions={actor:{x:0,y:0},target:{x:1,y:0}},Trade=G.systems.TradeSystem;
    for(const [a,b]of [["a","b"],["a",null],[null,"b"],[null,null]])test("TRADE SLOT CASE "+a+" / "+b,()=>{const w=world(),t=T.start(5);if(a)item(w,a);if(b)item(w,b,"herb","target");const count=Object.keys(w.itemInstances).length,r=Trade.execute(w,"actor","target",a,b,positions,t,{tradeMajorAction:true});check(Object.keys(w.itemInstances).length===count);if(!a&&!b)check(r.status==="NO_TRANSACTION"&&!t.majorUsed);else{check(t.majorUsed);if(a)check(w.itemInstances[a].place.id==="target"&&w.itemInstances[a].state==="PERSONAL");if(b)check(w.itemInstances[b].place.id==="actor");}});
    test("SUCCESSFUL TRADE DEFAULT IS MINOR",()=>{const w=world(),t=T.start(5);item(w,"a");Trade.execute(w,"actor","target","a",null,positions,t);check(w.itemInstances.a.place.id==="target"&&!t.majorUsed&&t.remainingMov===5);});
    test("TRADE ONLY ADJACENT FRIENDLY AND CARRIED",()=>{const w=world(),t=T.start(5);item(w,"a","herb","actor","EQUIPPED");reject(()=>Trade.plan(w,"actor","target","a",null,positions,t));w.units.target.faction="ZEON";reject(()=>Trade.plan(w,"actor","target",null,null,positions,t));w.units.target.faction="PLAYER";reject(()=>Trade.plan(w,"actor","target",null,null,{...positions,target:{x:3,y:0}},t));});
    test("TRADE FULL INVENTORY CANNOT TAKE INTO EMPTY SLOT",()=>{const w=world(),t=T.start(5);for(let n=0;n<4;n++)item(w,"i"+n);item(w,"b","herb","target");reject(()=>Trade.execute(w,"actor","target",null,"b",positions,t,{tradeMajorAction:false}));check(Trade.execute(w,"actor","target","i0","b",positions,t,{tradeMajorAction:false}).status==="TRADED");});
    test("EMPTY TRADE AFTER MAJOR DOES NOT SPEND ANOTHER ACTION",()=>{const w=world(),t=T.start(5);T.consume(t,"ATTACK");const before=copy(t);check(Trade.execute(w,"actor","target",null,null,positions,t).status==="NO_TRANSACTION");same(t,before);});
    const Hidden=G.systems.HiddenItemSystem,hidden=[{id:"cache",definitionId:"herb",x:3,y:-2}],distance=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
    test("SCROUNGER POSITION AND METRIC MUST BE SUPPLIED",()=>{const u=load(unit(),"scrounger");check(Hidden.query(u,null,hidden).status==="UNRESOLVED_POSITION");check(Hidden.query(u,{x:0,y:0},hidden).status==="UNRESOLVED_DISTANCE");});
    test("SCROUNGER FIVE TILE NOTICE MAJOR ACTION MOV COST UNRESOLVED",()=>{const u=load(unit(),"scrounger"),r=Hidden.query(u,{x:0,y:0},hidden,{distance});check(r.notify&&r.direction==="NE"&&r.movCost===null&&r.majorAction===true&&r.fullInventoryPolicy===null);check(!Hidden.query(u,{x:-1,y:0},hidden,{distance}).notify);});
    test("SCROUNGER ON TILE AND TIES REMAIN EXPLICIT",()=>{const u=load(unit(),"scrounger"),before=copy(hidden);check(Hidden.query(u,{x:3,y:-2},hidden,{distance}).status==="ON_ITEM");check(Hidden.query(u,{x:0,y:0},[...hidden,{id:"other",definitionId:"herb",x:0,y:1}],{distance}).status==="UNRESOLVED_ITEM_SELECTION");same(hidden,before);});
    test("HIDDEN ITEM IDS MUST BE UNIQUE",()=>reject(()=>Hidden.initialize([...hidden,...hidden])));
    function spells(fn){const old=G.data.ABILITIES;G.data.ABILITIES={...old};for(const [id,cl,family,level,pre]of [["p5blaze1","archer","BLAZE",1,[]],["p5blaze2","archer","BLAZE",2,["p5blaze1"]],["p5heal1","alchemist","HEAL",1,[]]])G.data.ABILITIES[id]={id,classId:cl,level,category:"ACTION",name:id,command:"MAGIC",majorAction:true,effect:{handler:"testSpell"},spellFamily:family,spellLevel:level,prerequisiteAbilityIds:pre,implementation:"DEFERRED"};try{return fn();}finally{G.data.ABILITIES=old;}}
    test("SPELL PREREQUISITE LEARNING WITHOUT AUTOGRANT",()=>spells(()=>{const u=unit("archer");P.earn(u,"archer",1000);check(!G.campaign.AbilityLearningSystem.eligibility(u,"p5blaze2").allowed);G.campaign.AbilityLearningSystem.purchase(u,"p5blaze1");G.campaign.AbilityLearningSystem.purchase(u,"p5blaze2");check(u.classProgress.archer.currentCP===775);}));
    test("ONE MAGIC GROUP PRESERVES FAMILIES LEVELS OWNERS",()=>spells(()=>{const u=learn(learn(learn(unit("archer"),"p5blaze1"),"p5blaze2"),"p5heal1");L.set(u,"secondaryClassId","alchemist");const groups=G.systems.ActionCommandSystem.categories(u,T.start(5)),magic=groups.filter(g=>g.command==="MAGIC");check(magic.length===1&&magic[0].abilities.length===3&&magic[0].families.length===2);same(magic[0].families[0].levels.map(e=>e.spellLevel),[1,2]);const heal=magic[0].abilities.find(e=>e.abilityId==="p5heal1");check(heal.owningClassId==="alchemist"&&heal.accessSource==="SECONDARY");same(P.attribution(u,{abilityId:"p5heal1"},7),{archer:4,alchemist:3});same(P.attribution(u,{abilityId:"p5blaze1"},7),{archer:7});}));
    test("MAGIC DOES NOT EXPOSE UNLEARNED FAMILY LEVELS",()=>spells(()=>{const u=learn(unit("archer"),"p5blaze1"),magic=G.systems.ActionCommandSystem.categories(u,T.start(5)).find(c=>c.command==="MAGIC");check(magic.abilities.length===1&&magic.families[0].levels.length===1);}));
    test("SPELL METHOD CHOICE OPTIONAL ONE MODIFIER AFTER SELECTION",()=>{const S=G.systems.SpellMenuSystem,u=unit(),entry={abilityId:"example"};same(S.castingOptions(u,entry),[]);let selected;const options=S.castingOptions(u,entry,(actor,e)=>{selected=e;return[{id:"enhance",name:"ENHANCE"},{id:"extend",name:"EXTEND"}];});check(selected===entry&&options.length===3&&options[0].id==="normal");check(S.selectMethod(options,"enhance")==="enhance");reject(()=>S.selectMethod(options,["enhance","extend"]));reject(()=>S.castingOptions(u,entry,()=>[{id:"x"},{id:"x"}]));});
    test("WAND ROBE FAMILY SELECTORS WITHOUT NEW ITEM FORMULAS",()=>fixtures(()=>{check(E.matches({slot:"weapon",families:["WAND"]},G.data.ITEMS.p5wand));check(E.matches({slot:"armor",families:["ROBE"]},G.data.ITEMS.p5robe));check(G.data.EQUIPMENT_FAMILIES.weapon.includes("WAND")&&G.data.EQUIPMENT_FAMILIES.armor.includes("ROBE"));}));
    test("PROMPT SIX ADDS ONLY ESTABLISHED SPELL DISCIPLINES",()=>{for(const id of ["mage","wizard","cleric"])check(G.data.CLASSES[id].playable);for(const id of ["hexer","enchanter","advancedHealer","elementalist"])check(!G.data.CLASSES[id]);check(!G.data.CLASSES.mage.legacy);});
    for(const [current,secondary,ability]of [["fighter","thief","stealWeapon"],["alchemist","fighter","powerAttack"]])test(current.toUpperCase()+" SECONDARY "+ability+" CP AND MENU OWNER",()=>{const u=learn(unit(current),ability);L.set(u,"secondaryClassId",secondary);same(P.attribution(u,ability,7),{[current]:4,[secondary]:3});const entry=G.systems.ActionCommandSystem.categories(u,T.start(5)).flatMap(g=>g.abilities||[]).find(a=>a.abilityId===ability);check(entry.owningClassId===secondary&&entry.accessSource==="SECONDARY");});
    test("CONSUMED ITEM PLAN CANNOT REPLAY PERMANENT GAIN",()=>fixtures(()=>{const w=world(load(unit(),"catalyze"));item(w,"b","p5buff");const p=J.plan(w,"actor","actor","b","ITEM",{decide:()=>true,chooseStat:()=>"str"});J.commit(w,p);const before=copy(w);reject(()=>J.commit(w,p));same(w,before);}));
    test("REFINE STALE INPUTS CANNOT MINT ANOTHER COPY",()=>fixtures(()=>{const w=world();item(w,"a","p5small");item(w,"b","p5small");const p=J.refinePlan(w,"actor","a","b",()=>({definitionId:"p5large"}));J.commitRefine(w,p);const before=copy(w);reject(()=>J.commitRefine(w,p));same(w,before);}));
    function battle(w){return new G.states.BattleState({positions,hiddenItems:hidden,participants:[{units:Object.values(w.units).map(u=>({...copy(u),stats:I.stats(w,u.id),possessions:Object.values(w.itemInstances).filter(i=>i.place.id===u.id).map(i=>({instance:copy(i)}))}))}]});}
    test("BATTLE RECEIPT CHECKS BOW BEFORE CP AND DEDUPLICATES",()=>fixtures(()=>{const w=world(learn(unit("archer"),"aimedShot")),empty=battle(w),r=receipt({abilityId:"aimedShot"}),before=copy(empty.state);reject(()=>empty.resolveActionCP("actor",r,{calculate:()=>7}));same(empty.state,before);item(w,"bow","p5bow","actor","EQUIPPED");const b=battle(w);check(b.resolveActionCP("actor",r,{calculate:()=>7}).recipients.archer===7);const after=copy(b.state);reject(()=>b.resolveActionCP("actor",r,{calculate:()=>7}));same(b.state,after);}));
    test("BATTLE TRADE FAILURES ARE ATOMIC AND DEFAULT COST IS MINOR",()=>{const w=world();item(w,"h");const b=battle(w),before=copy(b.state);reject(()=>b.trade("actor","target","missing",null));same(b.state,before);b.trade("actor","target","h",null);check(b.state.itemInstances.h.place.id==="target"&&!b.state.turns.actor.majorUsed);});
    test("SPELLS OUTSIDE PRIMARY OR SECONDARY ARE INACCESSIBLE",()=>spells(()=>{const u=learn(unit(),"p5blaze1");check(!G.systems.ActionCommandSystem.categories(u,T.start(5)).some(g=>g.command==="MAGIC"));}));
    test("ALCHEMIST UNRESOLVED PROBABILITIES AND FORMULAS STAY NULL",()=>{for(const id of ["conservation","purifyingMedicine","catalyze"])check(effect(id).chance===null);check(effect("refine").multiplier===null&&effect("tossItem").range===null&&effect("forage").table===null);});
    test("SCHEMA FOUR COMPLETED OLD HISTORY REMAINS LOADABLE",()=>{const c=G.campaign.createDemo();c.endDay();const s=oldSave(c.snapshot());s.schemaVersion=4;for(const u of Object.values(s.lastResolution.frozenWorld.units)){delete u.learnedAbilityIds;delete u.abilityLoadout;}const history=copy(s.lastResolution.frozenWorld.units);const restored=new G.campaign.Campaign(c.definitions,s);check(restored.state.schemaVersion===8);same(restored.state.lastResolution.frozenWorld.units,history);});
    return out;
  };
}(window.GBTRPG));
