(function(G){
  "use strict";
  G.debug.runResourceTests=function(){
    const results=[],V=G.campaign.Validation,U=G.campaign.UnitManagementSystem,I=G.campaign.InventorySystem,E=G.campaign.EconomySystem;
    const check=(x,m="assertion failed")=>{if(!x)throw Error(m);};
    const test=(name,fn)=>{try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}};
    const rejects=(c,fn)=>{const before=JSON.stringify(c.state);let failed=false;try{fn();}catch(e){failed=true;}check(failed,"expected rejection");check(JSON.stringify(c.state)===before,"failed command mutated state");};
    const restore=c=>new G.campaign.Campaign(c.definitions,JSON.parse(JSON.stringify(c.state)));
    const settle=c=>{if(c.state.phase==="PLANNING")c.endDay();else c.resumeResolution();while(c.state.resolution?.pendingBattleScenario)c.applyBattleResult(G.campaign.PlaceholderBattleResolver.result(c.state.resolution.pendingBattleScenario,"PLAYER","DEFEATED"));};
    const remote=()=>{const c=G.campaign.createDemo();c.supportPolity("galam");const old=c.purchase("granseal","ironSword");c.assignItem(old,"mc");const item=c.purchase("galam","steelSword"),wagon=c.assignItem(item,"mc");return{c,old,item,wagon};};
    const recruit=c=>c.recruit("granseal",c.state.recruitPools.granseal[0].id);
    test("ROSTER REPRESENTATION IS SLOT ONE",()=>{const c=G.campaign.createDemo(),before=c.state.squads.vanguard;
      check(U.sprite(c.state,before)==="unitAren");c.reorderRoster("vanguard","sara",-1);check(U.sprite(c.state,c.state.squads.vanguard)==="unitHealer");
      check(c.state.squads.vanguard.unitIds.slice().sort().join()===before.unitIds.slice().sort().join()&&c.state.day===1&&c.state.squads.vanguard.currentLocationId===before.currentLocationId);
      check(G.ui.MapPresentation.derive(c).find(o=>o.objectId==="vanguard").hasMC);check(restore(c).state.squads.vanguard.unitIds[0]==="sara");
    });
    test("REMOVE AND TRANSFER REPRESENTATIVES",()=>{const c=G.campaign.createDemo();c.removeUnit("mc");check(c.state.units.mc.unassignedLocationId==="granseal"&&U.sprite(c.state,c.state.squads.vanguard)==="unitHealer");c.transferUnit("sara","rangers");c.reorderRoster("rangers","sara","TOP");check(U.sprite(c.state,c.state.squads.vanguard)==="unitCentaur"&&U.sprite(c.state,c.state.squads.rangers)==="unitHealer");});
    test("EMPTY SQUAD FALLBACK AND DISMISSAL",()=>{const c=G.campaign.createDemo();c.dismissSquad("vanguard");check(c.state.units.mc.status==="ACTIVE"&&U.location(c.state,"mc")==="granseal");c.createSquad({id:"empty",name:"EMPTY",faction:"PLAYER",unitIds:[],currentLocationId:"grove"});check(U.sprite(c.state,c.state.squads.empty)==="emptySquad");});
    test("RESOURCE SCHEMA MIGRATION",()=>{const c=G.campaign.createDemo(),s=c.snapshot();s.schemaVersion=2;for(const key of G.campaign.ResourceSystem.keys)delete s[key];for(const u of Object.values(s.units)){const{id,name}=u;Object.keys(u).forEach(k=>delete u[k]);Object.assign(u,{id,name});}const loaded=new G.campaign.Campaign(c.definitions,s);check(loaded.state.schemaVersion===8&&loaded.state.treasuries.PLAYER===1000&&loaded.state.units.mc.unassignedLocationId===null);});
    test("FACTION INCOME AND EXACTLY ONCE RESUME",()=>{const c=G.campaign.createDemo();check(E.expected(c.definitions,c.state,"PLAYER")===85);c.startEndDay();while(c.state.phase!=="DAY_ADVANCE")c.stepResolution();check(c.state.treasuries.PLAYER===1085&&c.state.treasuries.ZEON===515);const loaded=restore(c);loaded.stepResolution();check(loaded.state.day===2&&loaded.state.treasuries.PLAYER===1085);});
    test("NEUTRAL AND ZEON EXCLUDED FROM PLAYER INCOME",()=>{const c=G.campaign.createDemo();c.setController("granseal","NEUTRAL");c.setController("grove","ZEON");c.endDay();check(c.state.treasuries.PLAYER===1000&&c.state.treasuries.ZEON===540);});
    test("RECOVERY INCOME MULTIPLIER HOOK",()=>{const c=G.campaign.createDemo(),s=c.snapshot();s.locations.granseal.recovery={incomeMultiplier:0.5};const f=new G.campaign.Campaign(c.definitions,s);f.endDay();check(f.state.treasuries.PLAYER===1055);});
    test("INFINITE SHOP AND PURCHASE LOCATION",()=>{const c=G.campaign.createDemo(),a=c.purchase("granseal","ironSword"),b=c.purchase("granseal","ironSword");check(a!==b&&c.state.treasuries.PLAYER===900&&c.state.day===1);check(c.state.itemInstances[a].place.id==="granseal"&&I.aggregate(c.state)[0].count===2);});
    test("SHOP TIERS AND ACCESS REJECTION",()=>{const c=G.campaign.createDemo();rejects(c,()=>c.purchase("granseal","steelSword"));rejects(c,()=>c.purchase("galam","ironSword"));rejects(c,()=>c.purchase("fortress","ironSword"));c.supportPolity("galam");check(E.available(c.definitions,c.state,"galam").some(i=>i.id==="steelSword"));});
    test("INSUFFICIENT PURCHASE ATOMIC",()=>{const c=G.campaign.createDemo(),s=c.snapshot();s.treasuries.PLAYER=0;const f=new G.campaign.Campaign(c.definitions,s);rejects(f,()=>f.purchase("granseal","herb"));});
    test("SAME LOCATION EQUIPMENT AND MODIFIERS",()=>{const c=G.campaign.createDemo(),base=I.stats(c.state,"mc").str,id=c.purchase("granseal","ironSword");c.assignItem(id,"mc");check(I.equipment(c.state,"mc").weapon===id&&I.stats(c.state,"mc").str===base+2&&!Object.keys(c.state.shipments).length);});
    test("INCOMPATIBLE EQUIPMENT ATOMIC",()=>{const c=G.campaign.createDemo(),id=c.purchase("granseal","ironSword");rejects(c,()=>c.assignItem(id,"sara"));});
    test("REMOTE EQUIPMENT PRESERVES OLD ITEM",()=>{const{c,item,old,wagon}=remote();check(c.state.itemInstances[item].state==="IN_TRANSIT"&&c.state.itemInstances[item].assignedUnitId==="mc"&&I.equipment(c.state,"mc").weapon===old&&I.stats(c.state,"mc").str===c.state.units.mc.basePrimary.str+2);check(c.state.shipments[wagon].cargoIds[0]===item);});
    test("MULTI EDGE WAGON DELIVERY EXACTLY ONCE",()=>{const{c,item,old,wagon}=remote();c.endDay();check(c.state.shipments[wagon].currentLocationId==="crossroads"&&I.equipment(c.state,"mc").weapon===old);c.endDay();check(!c.state.shipments[wagon]&&I.equipment(c.state,"mc").weapon===item&&c.state.itemInstances[old].state==="AVAILABLE"&&c.state.itemInstances[old].place.id==="granseal");check(Object.keys(c.state.itemInstances).length===2);c.endDay();check(c.state.lastResolution.resourceSummary.delivered===0);});
    test("MULTIPLE CARGO SAME UNIT",()=>{const{c,wagon}=remote(),mail=c.purchase("galam","mail");c.assignItem(mail,"mc");check(Object.keys(c.state.shipments).length===1&&c.state.shipments[wagon].cargoIds.length===2);c.endDay();c.endDay();check(I.equipment(c.state,"mc").armor===mail);});
    test("DUPLICATE SLOT ASSIGNMENT REJECTED",()=>{const{c}=remote(),second=c.purchase("galam","steelSword");rejects(c,()=>c.assignItem(second,"mc"));});
    test("PERSONAL INVENTORY CAPACITY AND RELEASE",()=>{const c=G.campaign.createDemo();for(let n=0;n<4;n++)c.assignItem(c.purchase("granseal","herb"),"mc");const id=c.purchase("granseal","herb");rejects(c,()=>c.assignItem(id,"mc"));const first=Object.values(c.state.itemInstances).find(i=>i.state==="PERSONAL");c.releaseItem(first.id);check(c.state.itemInstances[first.id].place.id==="granseal");});
    test("SAFE ROUTING USES ONLY SUPPLIED KNOWLEDGE",()=>{const c=G.campaign.createDemo(),known={dangerousLocationIds:["crossroads"],dangerousRouteIds:[]};const path=G.campaign.WorldPathfindingSystem.find(c.definitions,c.state,"galam","granseal",G.campaign.TravelerSystem.safeWeight(known));check(path.routeIds.join()==="northPass,marshWay,groveTrail");const safe=G.campaign.WorldPathfindingSystem.find(c.definitions,c.state,"galam","granseal",G.campaign.TravelerSystem.safeWeight({dangerousLocationIds:[],dangerousRouteIds:[]}));check(safe.routeIds.join()==="kingRoad,westRoad");});
    test("KNOWN DANGER REROUTE BETWEEN DAYS",()=>{const{c,item}=remote();let known={dangerousLocationIds:["crossroads"],dangerousRouteIds:[]};const f=new G.campaign.Campaign(c.definitions,c.snapshot(),new G.core.EventBus(),new G.campaign.ZeonOrderProvider(),()=>known);f.startEndDay();check(f.state.resolution.resourceBefore.travelerOrders["wagon_"+f.state.itemInstances[item].place.id].plannedRouteIds[0]==="northPass");});
    test("KNOWN DANGER NO SAFE PATH HOLDS",()=>{const{c,wagon}=remote();const f=new G.campaign.Campaign(c.definitions,c.snapshot(),new G.core.EventBus(),new G.campaign.ZeonOrderProvider(),()=>({dangerousLocationIds:["crossroads","fortress"],dangerousRouteIds:[]}));f.endDay();check(f.state.shipments[wagon].currentLocationId==="galam");});
    test("FROZEN WAGON INTENT BEFORE COMMIT",()=>{const{c,wagon}=remote();c.startEndDay();c.stepResolution();check(c.state.resolution.travelerIntents.length===1&&c.state.shipments[wagon].currentLocationId==="galam");const before=JSON.stringify(c.state);rejects(c,()=>c.releaseItem(c.state.shipments[wagon].cargoIds[0]));check(JSON.stringify(c.state)===before);});
    test("MOVING UNIT RETARGETS DELIVERY",()=>{const{c,item,wagon}=remote();c.queueMovement("vanguard","grove");c.endDay();check(c.state.shipments[wagon].currentLocationId==="crossroads");c.endDay();check(c.state.shipments[wagon].currentLocationId==="granseal");c.endDay();check(I.equipment(c.state,"mc").weapon===item&&U.location(c.state,"mc")==="grove");});
    test("WAGON INTERCEPTION NO BATTLE OR PROTECTION",()=>{const c=G.campaign.createDemo();c.supportPolity("galam");const item=c.purchase("galam","steelSword"),wagon=c.assignItem(item,"mc");c.setController("galam","NEUTRAL");c.relocateForInspection("zeonGuard","galam");c.queueZeonDemoMovement("zeonGuard","crossroads");c.queueMovement("vanguard","crossroads");const b=c.endDay();check(b&&c.state.resolution.travelerOutcomes[0].outcome==="DESTROY_CARGO");c.applyBattleResult(G.campaign.PlaceholderBattleResolver.result(b,"PLAYER","DEFEATED"));check(!c.state.shipments[wagon]&&!c.state.itemInstances[item]&&c.state.lastResolution.battleResults.length===1);});
    test("UNOPPOSED WAGON INTERCEPTION NO BATTLE",()=>{const c=G.campaign.createDemo();c.supportPolity("galam");const item=c.purchase("galam","steelSword"),wagon=c.assignItem(item,"mc");c.setController("galam","NEUTRAL");c.relocateForInspection("zeonGuard","galam");c.queueZeonDemoMovement("zeonGuard","crossroads");check(c.endDay()===null&&!c.state.shipments[wagon]&&!c.state.itemInstances[item]&&c.state.lastResolution.battleResults.length===0);});
    test("RESOURCE EVERY PHASE RESTORES",()=>{const{c}=remote();c.startEndDay();let guard=0;while(c.state.phase!=="PLANNING"){const f=restore(c);settle(f);const expected=restore(c);settle(expected);check(JSON.stringify(f.state)===JSON.stringify(expected.state));c.stepResolution();check(++guard<20);}});
    test("BATTLE PAUSE PRESERVES WAGON RESOLUTION",()=>{const{c}=remote();c.relocateForInspection("rangers","grove");c.queueMovement("rangers","fortress");c.endDay();check(c.state.resolution.pendingBattleScenario);const f=restore(c);settle(c);settle(f);check(JSON.stringify(c.state)===JSON.stringify(f.state));});
    test("RECRUIT PURCHASE COSTS G AND STAYS LOCAL",()=>{const c=G.campaign.createDemo(),candidate=c.state.recruitPools.granseal[0],id=recruit(c);check(c.state.treasuries.PLAYER===1000-candidate.costG&&c.state.day===1&&c.state.units[id].unassignedLocationId==="granseal"&&!U.squadFor(c.state,id));check(!c.state.recruitPools.granseal.some(x=>x.id===candidate.id));});
    test("RECRUIT ACCESS AND INSUFFICIENT G",()=>{const c=G.campaign.createDemo();rejects(c,()=>c.recruit("galam",c.state.recruitPools.galam[0].id));c.setController("grove","ZEON");rejects(c,()=>c.recruit("grove",c.state.recruitPools.grove[0].id));const s=c.snapshot();s.treasuries.PLAYER=0;const f=new G.campaign.Campaign(c.definitions,s);rejects(f,()=>recruit(f));});
    test("AUTOMATIC SEVEN DAY REFRESH DETERMINISTIC",()=>{const c=G.campaign.createDemo(),initial=JSON.stringify(c.state.recruitPools);for(let i=0;i<6;i++)c.endDay();check(c.state.day===7&&JSON.stringify(c.state.recruitPools)===initial);const f=restore(c);c.endDay();f.endDay();check(c.state.day===8&&JSON.stringify(c.state.recruitPools)!==initial&&JSON.stringify(c.state)===JSON.stringify(f.state));check(!("refreshRecruits" in c));});
    test("RECRUIT GENERATION USES BENCHMARK INTERFACE",()=>{const c=G.campaign.createDemo(),s=c.snapshot();let called=0;G.campaign.RecruitmentSystem.generate(c.definitions,s,1,{calculate(){called++;return 10;}});check(called===1&&s.recruitPools.granseal.every(x=>x.characterLevel>=8&&x.characterLevel<=9));});
    test("LOCAL JOIN REMOTE JOIN REJECTED",()=>{const c=G.campaign.createDemo(),id=recruit(c);c.relocateForInspection("vanguard","crossroads");rejects(c,()=>c.transferUnit(id,"vanguard"));c.transferUnit(id,"rangers");check(c.state.units[id].unassignedLocationId===null);});
    test("LONE UNIT ONE EDGE AND GEOGRAPHIC JOIN",()=>{const c=G.campaign.createDemo(),id=recruit(c);c.queueLoneUnit(id,"grove");c.endDay();check(c.state.units[id].unassignedLocationId==="grove"&&!U.squadFor(c.state,id));rejects(c,()=>c.transferUnit(id,"vanguard"));c.relocateForInspection("vanguard","grove");c.transferUnit(id,"vanguard");check(c.state.squads.vanguard.unitIds.at(-1)===id);});
    test("LONE UNIT INTERCEPTION CAPTURE NO BATTLE",()=>{const c=G.campaign.createDemo(),id=c.recruit("grove",c.state.recruitPools.grove[0].id);c.queueLoneUnit(id,"fortress");check(c.endDay()===null&&c.state.units[id].status==="CAPTURED"&&c.state.lastResolution.battleResults.length===0);});
    test("LONE UNIT SERIALIZED MULTI EDGE TRAVEL",()=>{const c=G.campaign.createDemo(),id=recruit(c);c.queueLoneUnit(id,"galam");c.startEndDay();c.stepResolution();const f=restore(c);settle(c);settle(f);check(JSON.stringify(c.state)===JSON.stringify(f.state)&&U.location(f.state,id)==="crossroads");f.endDay();check(U.location(f.state,id)==="galam");});
    test("REMOTE SQUAD ASSEMBLY REJECTS",()=>{const c=G.campaign.createDemo(),id=recruit(c);rejects(c,()=>c.createSquad({id:"remote",name:"REMOTE",faction:"PLAYER",unitIds:[id],currentLocationId:"grove"}));});
    for(const [name,corrupt]of [
      ["TREASURY",s=>s.treasuries.PLAYER=-1], ["UNIT LOCATION",s=>s.units.mc.unassignedLocationId="grove"],
      ["ITEM PLACE",s=>{const i=Object.values(s.itemInstances)[0];i.place={type:"LOCATION",id:"missing"};}],
      ["SHIPMENT CARGO",s=>Object.values(s.shipments)[0].cargoIds.push(Object.values(s.shipments)[0].cargoIds[0])],
      ["POOL CANDIDATE",s=>s.recruitPools.granseal.push(s.recruitPools.granseal[0])],
      ["SCHEDULE",s=>s.recruitment.nextRefreshDay=2]
    ])test("VALIDATION REJECTS "+name,()=>{const{c}=remote(),s=c.snapshot();corrupt(s);let failed=false;try{new G.campaign.Campaign(c.definitions,s);}catch(e){failed=true;}check(failed);});
    test("RESOURCE RESOLUTION TAMPERING REJECTED",()=>{const{c}=remote();c.startEndDay();c.stepResolution();for(const mutate of[s=>s.treasuries.PLAYER++,s=>s.resolution.travelerIntents[0].destinationLocationId="grove"]){const s=c.snapshot();mutate(s);let failed=false;try{new G.campaign.Campaign(c.definitions,s);}catch(e){failed=true;}check(failed);}});
    test("BATTLE SNAPSHOT EXCLUDES UNDELIVERED BONUSES",()=>{
      const {c,old,item}=remote();c.relocateForInspection("vanguard","grove");c.queueMovement("vanguard","fortress");const b=c.endDay();
      const mc=b.participants.flatMap(q=>q.units).find(u=>u.id==="mc");check(mc.equipment.weapon===old&&mc.stats.str===c.state.units.mc.basePrimary.str+2&&!mc.possessions.some(p=>p.instance.id===item));
      check(Object.isFrozen(b)&&Object.isFrozen(mc.possessions));
    });
    test("RESOURCE COUNTER CANNOT REUSE ITEM ID",()=>{const{c}=remote(),s=c.snapshot();s.nextItemId=1;let failed=false;try{new G.campaign.Campaign(c.definitions,s);}catch(e){failed=true;}check(failed);});
    test("CLOSED ROUTE HOLDS AND REPLANS WAGON",()=>{const{c,wagon}=remote();c.setRouteAvailability("kingRoad",{blocked:true});check(!c.state.travelerOrders["wagon_"+wagon]);c.endDay();check(c.state.shipments[wagon].currentLocationId==="galam");c.setRouteAvailability("kingRoad",{blocked:false});c.endDay();check(c.state.shipments[wagon].currentLocationId==="crossroads");});
    test("THIRTEENTH TRANSFER REJECTS ATOMICALLY",()=>{const c=G.campaign.createDemo(),s=c.snapshot();for(let i=0;i<12;i++)s.units["reserve"+i]=U.make("reserve"+i,"swordsman","PLAYER","granseal");const f=new G.campaign.Campaign(c.definitions,s);f.createSquad({id:"full",name:"FULL",faction:"PLAYER",currentLocationId:"granseal",unitIds:Array.from({length:12},(_,i)=>"reserve"+i)});rejects(f,()=>f.transferUnit("mc","full"));});
    return results;
  };
}(window.GBTRPG));
