(function(G){
  "use strict";
  G.debug.runRouteMidpointTests=function(){
    const out=[],V=G.campaign.Validation,A=G.campaign.AwolSystem,B=G.campaign.BattleLocationSystem,R=G.core.DeterministicRandom;
    const check=(value,message="assertion failed")=>{if(!value)throw Error(message);},same=(a,b)=>check(JSON.stringify(a)===JSON.stringify(b),"values differ");
    const test=(name,fn)=>{try{fn();out.push({name:"P6B "+name,pass:true});}catch(e){out.push({name:"P6B "+name,pass:false,error:e.message});}};
    function network(weight=8){
      const d={locations:{a:{id:"a",locationType:"CROSSROADS",mapPosition:{x:0,y:0}},b:{id:"b",locationType:"CROSSROADS",mapPosition:{x:100,y:0}},x:{id:"x",locationType:"VILLAGE",mapPosition:{x:50,y:0}},y:{id:"y",locationType:"VILLAGE",mapPosition:{x:99999,y:99999}}},routes:{}},s={locations:{a:{controller:"ZEON"},b:{controller:"ZEON"},x:{controller:"PLAYER"},y:{controller:"PLAYER"}},routes:{},squads:{},units:{}};
      const edge=(id,a,b,travelDays)=>{d.routes[id]={id,locationAId:a,locationBId:b,travelDays};s.routes[id]={available:true,blocked:false};};
      edge("ab","a","b",weight);edge("ax","a","x",3);edge("bx","b","x",8);edge("ay","a","y",7);edge("by","b","y",2);
      return{d,s,edge,record:{battleLocationId:null,routeId:"ab",faction:"PLAYER"}};
    }
    test("PRAYER REMAINS CLERIC THREE AT 25 PERCENT",()=>{const a=G.data.ABILITIES.prayer;check(a.classId==="cleric"&&a.category==="REACTION"&&a.level===3&&a.effect.chance===0.25&&G.config.SPELLS.prayerChance===0.25);});
    test("PRAYER SAVES THIS EVENT BUT LATER LETHAL POISON STILL CAUSES DYING",()=>{const fixture=G.data.SpellLabScenario.create(),b=new G.states.BattleState(fixture.scenario);b.command(s=>{s.positions.labCleric={x:2,y:3};G.campaign.AbilityLoadoutSystem.set(s.units.labCleric,"reactionId","prayer");s.units.labWizard.tactical.statuses=[{id:"POISON"}];});b.damage("labWizard",100,{prayerRoll:()=>0.1});let t=b.state.units.labWizard.tactical;check(t.hp===1&&t.life==="ALIVE"&&t.dyingCounter===null);same(t.statuses,[{id:"POISON"}]);b.damage("labWizard",1,{prayerRoll:()=>0.25});t=b.state.units.labWizard.tactical;check(t.hp===0&&t.life==="DYING"&&t.dyingCounter===3);same(t.statuses,[{id:"POISON"}]);});
    test("ROUTE LOCATION IS A VIRTUAL MIDPOINT WITH TWO CONNECTIONS",()=>{const {d,record}=network();same(B.resolve(d,record),{kind:"ROUTE_MIDPOINT",routeId:"ab",connections:[{locationId:"a",distance:4},{locationId:"b",distance:4}]});});
    for(const weight of [8,5,2.5])test("MIDPOINT WEIGHT "+weight+" REACHES EACH ENDPOINT WITHOUT ROUNDING",()=>{const {d,s,record}=network(weight);check(B.distance(d,s,record,"a")===weight/2&&B.distance(d,s,record,"b")===weight/2);check(G.config.SPELLS.rounding===null);});
    test("ABSENT TRAVEL WEIGHT USES EXISTING ONE DAY DEFAULT",()=>{const {d,s,record}=network();delete d.routes.ab.travelDays;check(B.distance(d,s,record,"a")===0.5&&B.distance(d,s,record,"b")===0.5);});
    test("MIDPOINT SETTLEMENT DISTANCE USES CHEAPER ENDPOINT AND WEIGHTS",()=>{const {d,s,record}=network();check(B.distance(d,s,record,"x")===7&&B.distance(d,s,record,"y")===6);check(A.settlement(d,s,record,R.create(0)).locationId==="y");});
    test("CHEAPER PATH THROUGH ENDPOINT A CAN SELECT ITS SETTLEMENT",()=>{const {d,s,record}=network();d.routes.ax.travelDays=1;check(B.distance(d,s,record,"x")===5);check(A.settlement(d,s,record,R.create(0)).locationId==="x");});
    test("PIXEL COORDINATES CANNOT CHANGE MIDPOINT NETWORK CHOICE",()=>{const {d,s,record}=network(),before=A.settlement(d,s,record,R.create(0));for(const l of Object.values(d.locations))l.mapPosition={x:-100000,y:0};same(A.settlement(d,s,record,R.create(0)),before);});
    test("NODE BATTLE RETAINS ITS ORIGINAL NETWORK DISTANCE",()=>{const {d,s}=network();check(B.resolve(d,{locationId:"a"}).kind==="NODE");check(B.distance(d,s,{battleLocationId:"a"},"x")===3);check(A.settlement(d,s,{battleLocationId:"a",routeId:null,faction:"PLAYER"},R.create(0)).locationId==="x");});
    test("MIDPOINT TIE RETAINS FARTHEST FROM NEAREST ENEMY RULE",()=>{const {d,s,record}=network();d.routes.ax.travelDays=2;s.squads.enemy={id:"enemy",faction:"ZEON",currentLocationId:"x",unitIds:["enemy"]};s.units.enemy={status:"ACTIVE"};check(B.distance(d,s,record,"x")===B.distance(d,s,record,"y"));check(A.settlement(d,s,record,R.create(0)).locationId==="y");});
    for(const count of [2,3,4])test("MIDPOINT COMPLETE "+count+" WAY TIE USES EXISTING EQUAL RNG CHOICE",()=>{const {d,s,record,edge}=network();d.routes.ax.travelDays=2;for(let i=2;i<count;i++){const id="extra"+i;d.locations[id]={id,locationType:"VILLAGE"};s.locations[id]={controller:"PLAYER"};edge("road"+i,"a",id,2);}const selected=[];for(let n=0;n<count;n++)selected.push(A.settlement(d,s,record,R.create(0),(rng,min,max)=>{check(min===0&&max===count-1);return n;}).locationId);check(new Set(selected).size===count);});
    test("MIDPOINT COMPLETE TIE IS REPRODUCIBLE WITH ACTUAL SEEDED RNG",()=>{const {d,s,record}=network();d.routes.ax.travelDays=2;const first=R.create(900),second=R.create(900);same(A.settlement(d,s,record,first),A.settlement(d,s,record,second));check(first.state===second.state&&first.state!==900);});
    test("MIDPOINT CAN RETURN THROUGH ONLY ONE REACHABLE ENDPOINT",()=>{const {d,s,record}=network();s.locations.x.controller="ZEON";s.routes.ay.blocked=true;s.routes.ax.blocked=true;s.routes.ab.blocked=true;check(B.distance(d,s,record,"y")===6);check(A.settlement(d,s,record,R.create(0)).locationId==="y");});
    test("ROUTE NO REACHABLE FRIENDLY SETTLEMENT REMAINS UNRESOLVED",()=>{const {d,s,record}=network();for(const r of Object.values(s.routes))r.available=false;const rng=R.create(1);same(A.settlement(d,s,record,rng),{locationId:null,reason:"NO REACHABLE FRIENDLY SETTLEMENT"});check(rng.state===1);});
    function routeCampaign(){const demo=G.campaign.createDemo();demo.loadDevelopmentScenario("crossing");const s=demo.snapshot();let seed=0;for(;seed<10000;seed++){const o=A.outcome(false,R.create(seed));if(o.kind==="ABSENT"&&o.delay===2)break;}s.awol.seed=seed;const c=new G.campaign.Campaign(demo.definitions,s);c.endDay();const battle=c.state.resolution.pendingBattleScenario;check(battle.battleType==="ROUTE_INTERCEPTION"&&battle.locationId===null&&battle.routeId);check(B.resolve(c.definitions,battle).kind==="ROUTE_MIDPOINT");c.applyBattleResult({...G.campaign.PlaceholderBattleResolver.result(battle,"ZEON"),awolUnitIds:["mc"]});return c;}
    test("PRODUCTION ROUTE AWOL RETURNS FROM MIDPOINT ON ESTABLISHED DAY",()=>{const c=routeCampaign(),pending=V.clone(c.state.awol.pending.mc),seed=c.state.awol.seed;check(pending.returnDay===3);const restored=new G.campaign.Campaign(c.definitions,c.snapshot());restored.endDay();check(restored.state.day===3&&restored.state.units.mc.status==="ACTIVE"&&!restored.state.awol.pending.mc);check(restored.state.units.mc.unassignedLocationId==="granseal"&&restored.state.awol.seed===seed&&restored.state.schemaVersion===8);});
    function oldCompletedUpdate(){const c=routeCampaign();c.startEndDay();while(c.state.phase!=="WORLD_UPDATE")c.stepResolution();const update=A.update;try{A.update=(d,s,events)=>update(d,s,events,["mc"]);c.stepResolution();}finally{A.update=update;}check(c.state.phase==="DAY_ADVANCE"&&c.state.awol.pending.mc.blockedReason==="BATTLE ROUTE POSITION UNRESOLVED");return c;}
    for(const phase of ["DAY_ADVANCE","PLANNING"])test("OLD SCHEMA EIGHT ROUTE HOLD RESTORES FROM "+phase+" WITHOUT REROLLS",()=>{const c=oldCompletedUpdate();if(phase==="PLANNING")c.stepResolution();const old=c.snapshot(),pending=V.clone(old.awol.pending.mc),seed=old.awol.seed,restored=new G.campaign.Campaign(c.definitions,old);same(restored.state,old);if(phase==="DAY_ADVANCE")restored.stepResolution();same(restored.state.awol.pending.mc,pending);check(restored.state.awol.seed===seed);restored.endDay();check(restored.state.units.mc.status==="ACTIVE"&&restored.state.units.mc.unassignedLocationId==="granseal"&&!restored.state.awol.pending.mc&&restored.state.awol.seed===seed);});
    test("OLD ROUTE HOLD RECHECKS TO NO FRIENDLY SETTLEMENT WITHOUT REROLL",()=>{const c=oldCompletedUpdate();c.stepResolution();for(const id of Object.keys(c.state.locations))c.setController(id,"ZEON");const old=c.snapshot(),seed=old.awol.seed,due=old.awol.pending.mc.returnDay,restored=new G.campaign.Campaign(c.definitions,old);restored.endDay();check(restored.state.units.mc.status==="AWOL"&&restored.state.awol.pending.mc.returnDay===due&&restored.state.awol.seed===seed);check(restored.state.awol.pending.mc.blockedReason==="NO REACHABLE FRIENDLY SETTLEMENT");});
    return out;
  };
}(window.GBTRPG));
