(function(G){
 "use strict";
 G.debug.runSpellCorrectionsTests=function(){
  const out=[],V=G.campaign.Validation,P=G.campaign.ClassProgressionSystem,L=G.campaign.AbilityLoadoutSystem,M=G.systems.MagicSystem,T=G.systems.TargetingSystem,B=G.systems.BattleStatusSystem,Portal=G.systems.PortalSystem,F=G.campaign.CharacterGrowthSystem,C=G.systems.CombatSystem;
  const check=(x,m="assertion failed")=>{if(!x)throw Error(m);},same=(a,b)=>check(JSON.stringify(a)===JSON.stringify(b),"values differ"),copy=V.clone,reject=f=>{let caught=false;try{f();}catch(e){caught=true;}check(caught,"expected rejection");};
  const test=(name,fn)=>{try{fn();out.push({name:"P6A "+name,pass:true});}catch(e){out.push({name:"P6A "+name,pass:false,error:e.message});}};
  const unit=(id="a",faction="PLAYER",cl="wizard")=>({id,name:id,typeId:"mage",faction,status:"ACTIVE",unassignedLocationId:null,...F.simulateRecruitGrowth({raceId:"HUMAN",currentClassId:cl,characterLevel:1,seed:99})});
  function learn(u,...ids){for(const id of ids){const a=G.data.ABILITIES[id];P.earn(u,a.classId,Math.max(0,G.config.CLASSES.thresholds[a.level-1]-P.progress(u,a.classId).lifetimeCP));if(!u.learnedAbilityIds.includes(id))u.learnedAbilityIds.push(id);}return u;}
  function equip(u,id){learn(u,id);L.set(u,{SUPPORT:"supportId",REACTION:"reactionId",MOVEMENT:"movementId"}[G.data.ABILITIES[id].category],id);return u;}
  const allModifiers=["extend","focus","expand","overcharge"];
  function caster(cl="wizard",secondary="mage"){const u=learn(unit("a","PLAYER",cl),...allModifiers,...Object.keys(G.data.SPELLS));L.set(u,"secondaryClassId",secondary);return u;}
  const inBounds=(x,y)=>x>=0&&y>=0&&x<12&&y<12,terrain={inBounds,occupiable:()=>true,canEnter:()=>true};
  function battle(units=[caster(),unit("b","ZEON","fighter")],positions={a:{x:2,y:2},b:{x:3,y:2}}){return new G.states.BattleState({scenarioId:"testBattle",positions,participants:["PLAYER","ZEON"].map(faction=>({squadId:faction,units:units.filter(u=>u.faction===faction).map(u=>({...u,stats:{...G.campaign.CharacterStatsSystem.deriveStats(u),maxHp:100,maxMp:100},possessions:[]}))}))});}
  function ongoingBattle(units=[caster(),unit("b","ZEON","fighter")],positions={a:{x:2,y:2},b:{x:3,y:2}}){return battle([...units,unit("playerReserve","PLAYER"),unit("enemyReserve","ZEON")],{...positions,playerReserve:{x:10,y:10},enemyReserve:{x:11,y:11}});}
  function balance(id,extra={}){const s=G.data.SPELLS[id];return{[id]:{castingRange:4,effectRadius:2,mpCost:20,magnitude:10,duration:3,...extra},...(s.magnitudeBalanceKey?{[s.magnitudeBalanceKey]:10}:{})};}
  const options=id=>({...terrain,balance:balance(id),rounding:Math.ceil}); // Explicit deterministic test policy, not production defaults.
  test("MARTYR RAISE AND EVERY DISTINCT DYING TRANSITION",()=>{const b=ongoingBattle([equip(unit(),"martyr"),unit("b","ZEON")]);b.damage("b",100);check(b.state.units.b.tactical.dyingCounter===2);b.startTurn("b");check(b.state.units.b.tactical.dyingCounter===1);b.endTurn("b");b.command(s=>B.raise(s.units.b));check(b.state.units.b.tactical.life==="ALIVE"&&b.state.units.b.tactical.dyingCounter===null);b.damage("b",100);check(b.state.units.b.tactical.dyingCounter===2&&!Object.hasOwn(b.state.units.b.tactical,"hasEnteredDying"));});
  function healingBattle(){return battle([caster("wizard","cleric"),unit("b","PLAYER"),unit("enemy","ZEON")],{a:{x:2,y:2},b:{x:3,y:2},enemy:{x:10,y:10}});}
  for(const life of ["HEALTHY","INJURED","DEAD","AWOL"])test("RAISE REJECTS "+life+" BEFORE ANY RESOURCE OR RECEIPT",()=>{const b=healingBattle();b.command(s=>{const t=s.units.b.tactical;if(life==="INJURED")t.hp=1;else if(life!=="HEALTHY")t.life=life;});check(!T.unitAllowed(b.state.units.a,b.state.units.b,G.data.SPELLS.raise1));const before=copy(b.state);reject(()=>b.cast("a","raise1",null,{x:3,y:2},{...options("raise1"),cpCalculator:{calculate:()=>{throw Error("must not award");}}}));same(b.state,before);});
  test("RAISE ONE ACTUAL CAST HEALS HALF AND PRESERVES OTHER STATUSES",()=>{const b=healingBattle();b.command(s=>s.units.b.tactical.statuses=[{id:"POISON"}]);b.damage("b",100);check(T.unitAllowed(b.state.units.a,b.state.units.b,G.data.SPELLS.raise1));b.cast("a","raise1",null,{x:3,y:2},options("raise1"));check(b.state.units.b.tactical.hp===50&&b.state.units.b.tactical.life==="ALIVE"&&b.state.units.b.tactical.dyingCounter===null);same(b.state.units.b.tactical.statuses,[{id:"POISON"}]);});
  test("FUTURE RAISE TWO FULL RESTORATION WITHOUT CLERIC ENTRY",()=>{const b=healingBattle(),def=G.data.RAISE_BEHAVIORS[2];check(def.lifeTarget==="DYING"&&def.effect==="RAISE");b.damage("b",100);b.command(s=>B.raise(s.units.b,def.maxHpFraction));check(b.state.units.b.tactical.hp===100&&b.state.units.b.tactical.life==="ALIVE"&&b.state.units.b.tactical.dyingCounter===null);check(!G.data.SPELLS.raise2&&!G.data.ABILITIES.raise2&&!G.data.CLASSES.advancedHealer);});
  function counterBattle(faction="PLAYER"){return battle([equip(learn(unit("a",faction),"blaze1","blaze2","blaze3","blaze4","freeze1","bolt1","bolt2"),"spellCounter"),unit("b",faction==="PLAYER"?"ZEON":"PLAYER")]);}
  function counterOptions(){return{...options("blaze1"),attackId:"attackA",canCounter:true,roll:()=>0.19,spellEligible:()=>true,normalCounter:()=>{throw Error("success must suppress ordinary counter");},selectSpell:()=>{throw Error("must not silently select for player");}};}
  test("PLAYER COUNTER REQUESTS ONLY PURCHASED LEVEL ONE SPELLS",()=>{const b=counterBattle(),before=copy(b.state.units),r=b.resolveCounters("a","b",counterOptions());check(r.kind==="SPELL_SELECTION");same(r.eligibleSpellIds,["blaze1","freeze1","bolt1"]);same(b.state.units,before);same(b.state.pendingCounter.eligibleSpellIds,r.eligibleSpellIds);check(!b.state.actionRecords.length);});
  test("COUNTER CHOICE ZERO MP MAJOR UNCHANGED NO CP AND DEDUP",()=>{const b=counterBattle();b.command(s=>s.units.a.tactical.mp=0);b.resolveCounters("a","b",counterOptions());const before=copy(b.state);reject(()=>b.chooseCounter("blaze4",options("blaze4")));same(b.state,before);reject(()=>b.startTurn("a"));reject(()=>b.resolveCounters("a","b",counterOptions()));const result=b.chooseCounter("blaze1",options("blaze1"));check(result.cast.paidMpCost===0&&b.state.units.a.tactical.mp===0&&!b.state.turns.a.majorUsed&&result.cp.status==="REACTION_NO_CP"&&b.state.pendingCounter===null);reject(()=>b.chooseCounter("blaze1",options("blaze1")));reject(()=>b.resolveCounters("a","b",counterOptions()));});
  test("FAILED COUNTER PERMITS ORDINARY CHECK",()=>{const b=counterBattle();let count=0;const r=b.resolveCounters("a","b",{...counterOptions(),roll:()=>0.2,normalCounter:()=>{count++;return true;}});check(r.kind==="NORMAL"&&count===1&&!b.state.pendingCounter);});
  test("ONLY HIGHER PURCHASES DO NOT OFFER LEVEL ONE COUNTER",()=>{const b=counterBattle();b.command(s=>s.units.a.learnedAbilityIds=s.units.a.learnedAbilityIds.filter(id=>!G.data.SPELLS[id]||G.data.SPELLS[id].spellLevel>1));const r=b.resolveCounters("a","b",{...counterOptions(),roll:()=>{throw Error("no roll");},normalCounter:()=>true});check(r.kind==="NORMAL");});
  test("ENEMY SPELL CHOICE REMAINS UNRESOLVED AND ATOMIC",()=>{const b=counterBattle("ZEON"),before=copy(b.state);reject(()=>b.resolveCounters("a","b",{...counterOptions(),selectSpell:undefined}));same(before,b.state);check(G.config.SPELLS.counterSpellSelection===null);});
  for(const [cl,yes,no]of [["mage","WAND","STAFF"],["wizard","STAFF","WAND"]])test(cl.toUpperCase()+" FINAL WEAPON AND ROBE IDENTITY",()=>{const E=G.campaign.EquipmentEligibility,u=unit("a","PLAYER",cl);check(E.allows(u,{equipmentSlot:"weapon",weaponFamily:yes})&&E.allows(u,{equipmentSlot:"armor",armorFamily:"ROBE"}));check(!E.allows(u,{equipmentSlot:"weapon",weaponFamily:no,allowedClasses:[cl]})&&!E.allows(u,{equipmentSlot:"armor",armorFamily:"PLATE",allowedClasses:[cl]}));});
  function flyingBattle(){const b=ongoingBattle();b.terrain=terrain;b.cast("a","fly",null,{x:2,y:2},{...options("fly"),balance:balance("fly",{effectRadius:1})});return b;}
  const timer=b=>b.state.units.a.tactical.statuses.find(s=>s.sourceKey==="fly")?.remaining;
  test("FLY COUNTER THREE AND ONLY AFFECTED END TURNS",()=>{const b=flyingBattle();check(timer(b)===3);b.startTurn("b");b.endTurn("b");check(timer(b)===3);b.startTurn("a");check(timer(b)===3);for(const n of [2,1,0]){b.endTurn("a");check(n?timer(b)===n:timer(b)===undefined);if(n)b.startTurn("a");}check(!B.flying(b.state.units.a)&&!b.state.units.a.tactical.escapeRequired);});
  test("FLY CAST ON OTHER TARGET DOES NOT TICK WITH CASTER",()=>{const b=healingBattle();b.command(s=>s.units.a.abilityLoadout.secondaryClassId="wizard");b.cast("a","fly",null,{x:3,y:2},{...options("fly"),balance:balance("fly",{effectRadius:1})});b.endTurn("a",terrain);check(b.state.units.b.tactical.statuses[0].remaining===3);b.startTurn("b");b.endTurn("b",terrain);check(b.state.units.b.tactical.statuses[0].remaining===2);});
  for(const source of ["RACE","CLASS"])test(source+" FLYING SURVIVES SPELL EXPIRATION",()=>{const b=flyingBattle(),catalog=source==="RACE"?G.data.RACES.HUMAN:G.data.CLASSES.wizard,old=catalog.capabilities;try{catalog.capabilities=["FLYING"];for(let n=0;n<3;n++){b.startTurn("a");b.endTurn("a");}check(B.flying(b.state.units.a)&&timer(b)===undefined&&G.systems.FlyingSystem.sources(b.state.units.a).some(s=>s.sourceType===source));}finally{if(old===undefined)delete catalog.capabilities;else catalog.capabilities=old;}});
  test("SPELL EXPIRY PRESERVES INDEPENDENT CAPABILITY SOURCE",()=>{const b=flyingBattle();b.command(s=>s.units.a.tactical.capabilitySources=[{id:"FLYING",sourceType:"EQUIPMENT",sourceKey:"fixture"}]);b.expireStatus("a","FLYING",terrain);check(B.flying(b.state.units.a)&&b.state.units.a.tactical.capabilitySources.length===1);});
  test("FLY FINALIZED DURATION CANNOT BE OVERRIDDEN BY BALANCE",()=>{check(M.definition("fly",balance("fly",{duration:90})).appliesStatuses[0].duration===3);const u=caster();check(M.compatible(u,M.definition("fly",balance("fly")),"expand"));for(const id of ["focus","overcharge","extend"])check(!M.compatible(u,M.definition("fly",balance("fly")),id));});
  function expireOver(legal){const b=flyingBattle();b.terrain={...terrain,occupiable:(x,y)=>legal.some(p=>p.x===x&&p.y===y),canEnter:(x,y)=>legal.some(p=>p.x===x&&p.y===y)};for(let n=0;n<3;n++){b.startTurn("a");b.endTurn("a");}return b;}
  for(const p of [{x:2,y:3},{x:1,y:1}])test("REQUIRED ESCAPE TO "+p.x+","+p.y,()=>{const b=expireOver([p]);check(b.state.units.a.tactical.escapeRequired&&b.state.units.a.tactical.life==="ALIVE");b.startTurn("a");const turn=copy(b.state.turns.a);reject(()=>b.endTurn("a"));reject(()=>b.cast("a","blaze1",null,{x:3,y:2},options("blaze1")));reject(()=>b.move("a",[[0,1]],terrain));reject(()=>b.startTurn("a"));b.escape("a",p);same(b.state.positions.a,p);check(!b.state.units.a.tactical.escapeRequired&&!b.state.turns.a.escapeRequired&&b.state.turns.a.remainingMov===turn.remainingMov);b.endTurn("a");});
  test("ESCAPE REJECTS OCCUPIED ILLEGAL AND OUT OF BOUNDS",()=>{const b=expireOver([{x:2,y:3},{x:3,y:2}]);b.startTurn("a");const before=copy(b.state);for(const p of [{x:3,y:2},{x:1,y:2},{x:-1,y:2}])reject(()=>b.escape("a",p));same(before,b.state);});
  test("NO ADJACENT ESCAPE CAUSES IMMEDIATE AWOL",()=>{const b=expireOver([]),u=b.state.units.a;check(u.tactical.life==="AWOL"&&!b.state.positions.a&&u.tactical.dyingCounter===null&&!B.active(u));check(!Object.values(b.state.rosters).some(q=>q.unitIds.includes("a")));reject(()=>b.startTurn("a"));reject(()=>b.move("a",[[0,1]],terrain));check(!T.unitAllowed(b.state.units.b,u,G.data.SPELLS.blaze1)&&!T.unitAllowed(u,b.state.units.b,G.data.SPELLS.blaze1));});
  test("ESCAPE BLOCKED BEFORE NEXT TURN RECHECKS TO AWOL",()=>{const b=expireOver([{x:2,y:3}]);b.command(s=>s.positions.b={x:2,y:3});b.startTurn("a");check(b.state.units.a.tactical.life==="AWOL"&&!b.state.positions.a);});
  test("EXPIRY LEGAL TILE HAS NO SPECIAL STATE",()=>{const b=expireOver([{x:2,y:2}]);check(b.state.units.a.tactical.life==="ALIVE"&&!b.state.units.a.tactical.escapeRequired);});
  test("FUTURE LETHAL POISON CANNOT REVERSE IMMEDIATE DEFEAT",()=>{const b=battle();b.command(s=>{s.units.b.tactical.hp=1;s.units.b.tactical.statuses=[{id:"POISON",futureDamage:1}];});b.damage("a",100);check(b.state.presentation.pendingWinner==="ZEON"&&b.state.units.a.tactical.dyingCounter===3);const before=copy(b.state);reject(()=>b.startTurn("b"));reject(()=>b.damage("b",1));same(before,b.state);b.animationComplete();check(b.state.presentation.phase==="MAP_RETURN");b.mapRendered();check(b.state.presentation.banner==="DEFEAT");});
  test("DYING DEAD AWOL DO NOT KEEP FACTION ACTIVE",()=>{for(const life of ["DYING","DEAD","AWOL"]){const b=ongoingBattle();b.command(s=>{s.units.enemyReserve.tactical.life=life;s.units.b.tactical.life=life;});check(C.conclusion(b.state)==="PLAYER");}});
  test("LAST ACTIVE AWOL QUEUES MAP THEN DEFEAT AND RESULT",()=>{const b=battle();b.terrain={...terrain,occupiable:()=>false};b.cast("a","fly",null,{x:2,y:2},{...options("fly"),balance:balance("fly",{effectRadius:1})});b.animationComplete();b.mapRendered();for(let n=0;n<3;n++){b.startTurn("a");b.endTurn("a");}check(b.state.presentation.pendingWinner==="ZEON"&&b.state.presentation.phase==="MAP_RETURN");b.mapRendered();same(b.result().awolUnitIds,["a"]);same(b.result().deadUnitIds,[]);});
  test("PORTAL EXTEND NOW APPROVED WITHOUT MUTATING DEFINITION",()=>{const u=caster(),base=copy(G.data.SPELLS.portal),normal=M.resolve(u,"portal",null,options("portal")),extended=M.resolve(u,"portal","extend",options("portal"));check(normal.castingRange===4&&extended.castingRange===5&&extended.effectRadius===1&&extended.paidMpCost===22);for(const id of ["focus","expand","overcharge"])reject(()=>M.resolve(u,"portal",id,options("portal")));same(base,G.data.SPELLS.portal);});
  const A=G.campaign.AwolSystem,R=G.core.DeterministicRandom;
  function seedFor(kind,delay){for(let seed=0;seed<20000;seed++){const o=A.outcome(false,R.create(seed));if(o.kind===kind&&(delay===undefined||o.delay===delay))return seed;}throw Error("seed not found");}
  function awolCampaign(won=false,seed=seedFor("ABSENT",2),ids=null){const demo=G.campaign.createDemo();demo.loadDevelopmentScenario("defender");const s=demo.snapshot();s.awol.seed=seed;const c=new G.campaign.Campaign(demo.definitions,s);c.endDay();const pending=c.state.resolution.pendingBattleScenario,member=pending.participants.find(p=>p.faction==="PLAYER").unitIds[0],result={...G.campaign.PlaceholderBattleResolver.result(pending,won?"PLAYER":"ZEON"),awolUnitIds:ids||[member]};return{c,pending,member,result};}
  test("WINNING AWOL RETURNS TO ORIGINAL SQUAD WITHOUT RNG",()=>{const {c,member,result}=awolCampaign(true),seed=c.state.awol.seed;c.applyBattleResult(result);check(c.state.units[member].status==="ACTIVE"&&c.state.squads.vanguard.unitIds.includes(member)&&!c.state.awol.pending[member]&&c.state.awol.seed===seed);});
  test("LOSING AWOL FAILED HALF CHECK USES PERMANENT CASUALTY",()=>{const {c,member,result}=awolCampaign(false,seedFor("DEAD"));const itemId=c.snapshot().nextItemId;c.applyBattleResult(result);check(c.state.units[member].status==="DEAD"&&!Object.values(c.state.squads).some(q=>q.unitIds.includes(member))&&!c.state.awol.pending[member]);same(new G.campaign.Campaign(c.definitions,c.snapshot()).state,c.state);});
  for(const delay of [2,3,4])test("LOSING AWOL SCHEDULES "+delay+" DAYS SURVIVES SAVE AND RETURNS BY NAME",()=>{const {c,member,result}=awolCampaign(false,seedFor("ABSENT",delay));c.applyBattleResult(result);check(c.state.units[member].status==="AWOL"&&c.state.awol.pending[member].returnDay===1+delay&&!Object.values(c.state.squads).some(q=>q.unitIds.includes(member)));let restored=new G.campaign.Campaign(c.definitions,c.snapshot()),messages=[];restored.events.on("AWOL_RETURNED",e=>messages.push(e));while(restored.state.day<1+delay){restored.endDay();while(restored.state.phase!=="PLANNING"){if(restored.state.resolution.pendingBattleScenario)restored.applyBattleResult(G.campaign.PlaceholderBattleResolver.result(restored.state.resolution.pendingBattleScenario,"ZEON"));else restored.stepResolution();}if(restored.state.day<1+delay)check(restored.state.units[member].status==="AWOL");}check(restored.state.units[member].status==="ACTIVE"&&!restored.state.awol.pending[member]);check(!Object.values(restored.state.squads).some(q=>q.unitIds.includes(member)));check(restored.state.locations[restored.state.units[member].unassignedLocationId].controller==="PLAYER");check(messages.length===1&&messages[0].message===restored.state.units[member].name+" has returned from the wilderness.");same(new G.campaign.Campaign(restored.definitions,restored.snapshot()).state,restored.state);});
  test("EACH LOSING AWOL GETS INDEPENDENT HALF CHECK",()=>{const {c,pending}=awolCampaign(),s=c.snapshot(),ids=pending.participants.find(p=>p.faction==="PLAYER").unitIds;let seed=0;for(;seed<20000;seed++){const rng=R.create(seed),outcomes=ids.map(()=>A.outcome(false,rng).kind);if(outcomes.includes("DEAD")&&outcomes.includes("ABSENT"))break;}s.awol.seed=seed;s.resolution.resourceBefore.awol.seed=seed;const restored=new G.campaign.Campaign(c.definitions,s),rng=R.create(seed),expected=[...ids].sort().map(id=>({id,result:A.outcome(false,rng)}));restored.applyBattleResult({...G.campaign.PlaceholderBattleResolver.result(pending,"ZEON"),awolUnitIds:ids});for(const {id,result}of expected)check(restored.state.units[id].status===(result.kind==="DEAD"?"DEAD":"AWOL"));check(restored.state.awol.seed===rng.state);});
  test("AWOL RESULT RESTORES WHILE WAITING FOR SIMULTANEOUS COMMIT",()=>{const {c,result,member}=awolCampaign(),s=c.snapshot();G.campaign.BattleBoundary.apply(s,result,[]);const resumed=new G.campaign.Campaign(c.definitions,s);check(resumed.state.units[member].status==="ACTIVE");resumed.resumeResolution();check(resumed.state.units[member].status==="AWOL");});
  test("AWOL DEAD OVERLAP AND FOREIGN RESULT IDS REJECT ATOMICALLY",()=>{const {c,result,member}=awolCampaign(),before=c.snapshot();reject(()=>c.applyBattleResult({...result,deadUnitIds:[member]}));reject(()=>c.applyBattleResult({...result,awolUnitIds:["notHere"]}));same(before,c.state);});
  function network(){const ids=["battle","a","b","c","enemy"],d={locations:Object.fromEntries(ids.map((id,n)=>[id,{id,locationType:"VILLAGE",mapPosition:{x:100-n*20,y:0}}])),routes:{}},s={locations:Object.fromEntries(ids.map(id=>[id,{controller:["a","b","c"].includes(id)?"PLAYER":"ZEON"}])),routes:{},squads:{e:{id:"e",faction:"ZEON",currentLocationId:"enemy",unitIds:["e"]}},units:{e:{status:"ACTIVE"}}};function edge(id,a,b,days){d.routes[id]={id,locationAId:a,locationBId:b,travelDays:days};s.routes[id]={available:true,blocked:false};}edge("ba","battle","a",1);edge("bb","battle","b",1);edge("bc","battle","c",1);edge("ea","enemy","a",1);edge("eb","enemy","b",3);edge("ec","enemy","c",3);return{d,s,record:{faction:"PLAYER",battleLocationId:"battle"}};}
  test("SETTLEMENT UNIQUE SHORTEST NETWORK DISTANCE BEATS GEOMETRY",()=>{const {d,s,record}=network();d.routes.bb.travelDays=8;d.routes.bc.travelDays=7;check(A.settlement(d,s,record,R.create(1)).locationId==="a");});
  test("TIED BATTLE DISTANCE PREFERS FARTHEST NEAREST ENEMY",()=>{const {d,s,record}=network();s.locations.c.controller="ZEON";check(A.settlement(d,s,record,R.create(1)).locationId==="b");});
  test("SAFETY MEASURES NEAREST OF ALL ENEMY SQUADS",()=>{const {d,s,record}=network();s.locations.c.controller="ZEON";s.squads.e2={id:"e2",faction:"ZEON",currentLocationId:"b",unitIds:["e2"]};s.units.e2={status:"ACTIVE"};check(A.settlement(d,s,record,R.create(1)).locationId==="a");});
  for(const count of [2,3,4])test("EXACT "+count+" WAY TIE USES ONE UNIFORM INTEGER CHOICE",()=>{const {d,s,record}=network();s.squads={};if(count===2)s.locations.c.controller="ZEON";if(count===4){d.locations.d={id:"d",locationType:"PORT"};s.locations.d={controller:"PLAYER"};d.routes.bd={id:"bd",locationAId:"battle",locationBId:"d",travelDays:1};s.routes.bd={available:true,blocked:false};}const results=[];for(let i=0;i<count;i++)results.push(A.settlement(d,s,record,R.create(0),(rng,min,max)=>{check(min===0&&max===count-1);return i;}).locationId);check(new Set(results).size===count);});
  test("NETWORK BLOCKAGE EXCLUDES UNREACHABLE SETTLEMENTS",()=>{const {d,s,record}=network();for(const r of Object.values(s.routes))r.blocked=true;check(A.settlement(d,s,record,R.create(1)).reason==="NO REACHABLE FRIENDLY SETTLEMENT");});
  test("NO CONTROLLED SETTLEMENT EXPOSES UNRESOLVED BOUNDARY",()=>{const {d,s,record}=network();for(const l of Object.values(s.locations))l.controller="ZEON";const chosen=A.settlement(d,s,record,R.create(1));check(chosen.locationId===null&&chosen.reason==="NO REACHABLE FRIENDLY SETTLEMENT");});
  test("ROUTE BATTLE MIDPOINT RESOLVES PREVIOUSLY UNDEFINED POSITION",()=>{const {d,s,record}=network();record.battleLocationId=null;record.routeId="ba";const selected=A.settlement(d,s,record,R.create(1));check(selected.locationId==="a"&&selected.reason===null);});
  test("DUE AWOL WITHOUT DESTINATION RETAINS SAVEABLE ABSENCE",()=>{const {c,member,result}=awolCampaign();c.applyBattleResult(result);let s=c.snapshot();for(const l of Object.values(s.locations))l.controller="ZEON";s.day=3;const events=[];A.update(c.definitions,s,events);check(s.units[member].status==="AWOL"&&s.awol.pending[member].blockedReason&&events[0].type==="AWOL_RETURN_UNRESOLVED");same(new G.campaign.Campaign(c.definitions,s).state,s);});
  test("SCHEMA SEVEN MIGRATES WITH EMPTY ABSENCE WITHOUT CHARACTER CHANGES",()=>{const c=G.campaign.createDemo(),old=c.snapshot();old.schemaVersion=7;delete old.awol;delete old.legacyEquipment;const n=new G.campaign.Campaign(c.definitions,old);check(n.state.schemaVersion===8);same(n.state.awol.pending,{});for(const key of ["units","recruitPools","itemInstances","squads","treasuries"])same(n.state[key],old[key]);});
  function legacyStaff(){const c=G.campaign.createDemo(),s=c.snapshot(),id="oldStaff",u=Object.values(s.units).find(u=>u.currentClassId==="mage");check(u);s.itemInstances[id]={id,definitionId:"staff",ownerFaction:u.faction,place:{type:"UNIT",id:u.id},state:"EQUIPPED",assignedUnitId:null};s.schemaVersion=7;delete s.awol;delete s.legacyEquipment;return{c,s,id,unitId:u.id};}
  test("OLD MAGE STAFF PRESERVED ONLY AS THAT EQUIPPED INSTANCE",()=>{const {c,s,id,unitId}=legacyStaff(),restored=new G.campaign.Campaign(c.definitions,s);same(restored.state.itemInstances,s.itemInstances);same(restored.state.units,s.units);check(restored.state.legacyEquipment[id]===unitId);check(!G.campaign.EquipmentEligibility.allows(restored.state.units[unitId],G.data.ITEMS.staff));restored.releaseItem(id);reject(()=>restored.assignItem(id,unitId));same(new G.campaign.Campaign(c.definitions,restored.snapshot()).state,restored.state);});
  test("OLD MAGE STAFF MID RESOLUTION MIGRATES AND REPLAYS",()=>{const {c,s,id,unitId}=legacyStaff(),restored=new G.campaign.Campaign(c.definitions,s);restored.startEndDay();const old=restored.snapshot();old.schemaVersion=7;delete old.awol;delete old.legacyEquipment;delete old.resolution.resourceBefore.awol;delete old.resolution.resourceBefore.legacyEquipment;const n=new G.campaign.Campaign(c.definitions,old);n.resumeResolution();check(n.state.itemInstances[id].state==="EQUIPPED"&&n.state.legacyEquipment[id]===unitId);});
  test("FINAL ROBE IDENTITY APPLIES TO EXISTING CLOTH ROBE",()=>{for(const cl of ["mage","wizard"])check(G.campaign.EquipmentEligibility.allows(unit("a","PLAYER",cl),G.data.ITEMS.cloth));});
  test("GLOBAL ROUNDING STILL NULL AND FRACTIONAL RAISE BLOCKED",()=>{const b=healingBattle();b.command(s=>s.units.b.tactical.maxHp=101);b.damage("b",100);const before=copy(b.state);reject(()=>b.cast("a","raise1",null,{x:3,y:2},{...terrain,balance:balance("raise1")}));same(before,b.state);check(G.config.SPELLS.rounding===null);});
  test("LEGACY MAGE IN FLIGHT STAFF DELIVERY SURVIVES MIGRATION",()=>{const c=G.campaign.createDemo();c.supportPolity("galam");const mage=Object.values(c.state.units).find(u=>u.currentClassId==="mage");let old;const flag=G.data.CLASSES.mage.legacy;try{G.data.CLASSES.mage.legacy=true;const item=c.purchase("galam","staff");c.assignItem(item,mage.id);c.startEndDay();while(c.state.phase!=="DAY_ADVANCE"){if(c.state.resolution.pendingBattleScenario)c.applyBattleResult(G.campaign.PlaceholderBattleResolver.result(c.state.resolution.pendingBattleScenario,"PLAYER"));else c.stepResolution();}old=c.snapshot();old.schemaVersion=7;delete old.awol;delete old.legacyEquipment;delete old.resolution.resourceBefore.awol;delete old.resolution.resourceBefore.legacyEquipment;}finally{G.data.CLASSES.mage.legacy=flag;}const restored=new G.campaign.Campaign(c.definitions,old);restored.stepResolution();restored.endDay();check(G.campaign.InventorySystem.equipmentDefinitions(restored.state,mage.id).some(d=>d.id==="staff"));same(new G.campaign.Campaign(restored.definitions,restored.snapshot()).state,restored.state);});
  test("AWOL FAILED CHECK RETAINS OWNED PHYSICAL ITEMS",()=>{const {c,result,member}=awolCampaign(false,seedFor("DEAD")),s=c.snapshot(),id="casualtyItem",item={id,definitionId:"herb",ownerFaction:"PLAYER",place:{type:"UNIT",id:member},state:"PERSONAL",assignedUnitId:null};s.itemInstances[id]=copy(item);s.resolution.resourceBefore.itemInstances[id]=copy(item);const conflict=s.resolution.conflicts[s.resolution.nextConflictIndex];s.resolution.pendingBattleScenario=G.campaign.BattleBoundary.scenario(s.resolution,conflict,G.campaign.MovementConflictSystem.activePair(s.resolution,conflict));const restored=new G.campaign.Campaign(c.definitions,s);restored.applyBattleResult(result);same(restored.state.itemInstances[id],item);check(restored.state.units[member].status==="DEAD");});
  function prayerBattle(){return battle([equip(unit(),"prayer"),unit("b","PLAYER"),unit("enemy","ZEON")],{a:{x:2,y:2},b:{x:3,y:2},enemy:{x:9,y:9}});}
  for(const [roll,activates]of [[0,true],[0.249999,true],[0.25,false],[0.999999,false]])test("PRAYER FINAL 25 PERCENT BOUNDARY "+roll,()=>{const b=prayerBattle();b.command(s=>s.units.b.tactical.statuses=[{id:"POISON"}]);b.damage("b",100,{prayerRoll:()=>roll});check(b.state.units.b.tactical.hp===(activates?1:0)&&b.state.units.b.tactical.life===(activates?"ALIVE":"DYING"));same(b.state.units.b.tactical.statuses,[{id:"POISON"}]);});
  test("PRAYER CONFIG METADATA AND OUTCOME ADAPTER AGREE ON 25 PERCENT",()=>{check(G.config.SPELLS.prayerChance===0.25&&G.data.ABILITIES.prayer.effect.chance===0.25);const b=prayerBattle();let seen=false;b.damage("b",100,{prayerDecision:(ally,target,chance)=>{check(ally.id==="a"&&target.id==="b"&&chance===0.25);seen=true;return true;}});check(seen&&b.state.units.b.tactical.hp===1);});
  test("PRAYER INVALID OR MISSING RNG REJECTS ATOMICALLY",()=>{const b=prayerBattle(),before=copy(b.state);for(const roll of [-0.01,1,NaN,Infinity]){reject(()=>b.damage("b",100,{prayerRoll:()=>roll}));same(before,b.state);}reject(()=>b.damage("b",100));same(before,b.state);});
  test("PRAYER DOES NOT ROLL ON NONLETHAL DAMAGE",()=>{const b=prayerBattle();b.damage("b",99,{prayerRoll:()=>{throw Error("no lethal transition");}});check(b.state.units.b.tactical.hp===1&&b.state.units.b.tactical.life==="ALIVE");});
  return out;
 };
}(window.GBTRPG));
