(function(G){
 "use strict";
 G.debug.runSpellFrameworkTests=function(){
  const out=[],V=G.campaign.Validation,P=G.campaign.ClassProgressionSystem,L=G.campaign.AbilityLoadoutSystem,M=G.systems.MagicSystem,T=G.systems.TargetingSystem,B=G.systems.BattleStatusSystem,Portal=G.systems.PortalSystem,F=G.campaign.CharacterGrowthSystem,C=G.systems.CombatSystem;
  const check=(x,m="assertion failed")=>{if(!x)throw Error(m);},same=(a,b)=>check(JSON.stringify(a)===JSON.stringify(b),"values differ"),copy=V.clone,reject=f=>{let caught=false;try{f();}catch(e){caught=true;}check(caught,"expected rejection");};
  const test=(name,fn)=>{try{fn();out.push({name:"P6 "+name,pass:true});}catch(e){out.push({name:"P6 "+name,pass:false,error:e.message});}};
  const unit=(id="a",faction="PLAYER",cl="wizard")=>({id,name:id,typeId:"mage",faction,status:"ACTIVE",unassignedLocationId:null,...F.simulateRecruitGrowth({raceId:"HUMAN",currentClassId:cl,characterLevel:1,seed:99})});
  function learn(u,...ids){for(const id of ids){const a=G.data.ABILITIES[id];P.earn(u,a.classId,Math.max(0,G.config.CLASSES.thresholds[a.level-1]-P.progress(u,a.classId).lifetimeCP));if(!u.learnedAbilityIds.includes(id))u.learnedAbilityIds.push(id);}return u;}
  function equip(u,id){learn(u,id);L.set(u,{SUPPORT:"supportId",REACTION:"reactionId",MOVEMENT:"movementId"}[G.data.ABILITIES[id].category],id);return u;}
  const allModifiers=["extend","focus","expand","overcharge"];
  function caster(cl="wizard",secondary="mage"){const u=learn(unit("a","PLAYER",cl),...allModifiers,...Object.keys(G.data.SPELLS));L.set(u,"secondaryClassId",secondary);return u;}
  const inBounds=(x,y)=>x>=0&&y>=0&&x<12&&y<12,terrain={inBounds,occupiable:()=>true,canEnter:()=>true};
  function battle(units=[caster(),unit("b","ZEON","fighter")],positions={a:{x:2,y:2},b:{x:3,y:2}}){return new G.states.BattleState({scenarioId:"testBattle",positions,participants:["PLAYER","ZEON"].map(faction=>({squadId:faction,units:units.filter(u=>u.faction===faction).map(u=>({...u,stats:{...G.campaign.CharacterStatsSystem.deriveStats(u),maxHp:100,maxMp:100},possessions:[]}))}))});}
  function ongoingBattle(units=[caster(),unit("b","ZEON","fighter")],positions={a:{x:2,y:2},b:{x:3,y:2}}){return battle([...units,unit("playerReserve","PLAYER"),unit("enemyReserve","ZEON")],{...positions,playerReserve:{x:10,y:10},enemyReserve:{x:11,y:11}});}
  function balance(id,extra={}){const s=G.data.SPELLS[id];return{[id]:{castingRange:4,effectRadius:2,mpCost:20,magnitude:10,duration:3,...extra},...(s.magnitudeBalanceKey?{[s.magnitudeBalanceKey]:10}:{})};}
  const options=id=>({...terrain,balance:balance(id),rounding:Math.ceil}); // Explicit deterministic test policy, not production defaults.
  for(const [r,count]of [[1,1],[2,5],[3,13],[4,25],[5,41]])test("RADIUS "+r+" DIAMOND HAS "+count+" TILES",()=>check(T.affectedTiles({x:0,y:0},r).length===count));
  test("RANGE DISTINCT FROM RADIUS",()=>{check(T.targetTiles({x:0,y:0},4).length===41);check(T.affectedTiles({x:0,y:0},4).length===25);check(G.data.SPELLS.portal.castingRange===4&&G.data.SPELLS.portal.effectRadius===1);});
  test("ALL SPELLS EXPOSE EXPLICIT CONTRACT",()=>{for(const s of Object.values(G.data.SPELLS))for(const key of ["id","name","spellFamily","spellLevel","owningClassId","castingRange","effectRadius","magnitude","mpCost","element","dealsDamage","restoresHp","appliesStatuses","curesStatuses","targetAllegiances","targetTypes","canTargetCaster","canTargetDying","canTargetDead","placement","modifierCompatibility"])check(Object.hasOwn(s,key),s.id+" missing "+key);});
  for(const [family,element]of [["blaze","FIRE"],["freeze","ICE"],["bolt","LIGHTNING"],["gale","AIR"],["quake","EARTH"],["torrent","WATER"]])test(family.toUpperCase()+" FOUR SPELLS OWNERSHIP UNLOCKS GEOMETRY",()=>{for(let tier=1;tier<=4;tier++){const s=G.data.SPELLS[family+tier],a=G.data.ABILITIES[s.id];check(s.element===element&&s.owningClassId==="mage"&&a.level===[1,3,5,7][tier-1]&&s.effectRadius===[1,2,2,3][tier-1]);}check(G.data.SPELLS[family+1].magnitudeBalanceKey===G.data.SPELLS[family+2].magnitudeBalanceKey);});
  test("MAGE SPELLS PURCHASED SEPARATELY NEVER AUTOGRANTED",()=>{const u=unit("a","PLAYER","mage");P.earn(u,"mage",2700);same(u.learnedAbilityIds,[]);G.campaign.AbilityLearningSystem.purchase(u,"quake1");check(u.learnedAbilityIds.length===1&&u.classProgress.mage.currentCP===2600);});
  test("CLERIC ACTION LEVELS AND EXPLICIT STATUS CURES",()=>{for(const [id,status]of [["detox","POISON"],["clearSight","BLIND"],["unseal","MUTE"],["awaken","SLEEP"],["clarity","CONFUSED"]])same(G.data.SPELLS[id].curesStatuses,[status]);check(G.data.ABILITIES.raise1.level===4);check(!G.data.CLASSES.cleric.abilityIds.some(id=>G.data.ABILITIES[id].category==="ACTION"&&G.data.ABILITIES[id].level>=8));});
  test("USER CONFIRMED CLERIC PASSIVE LEVELS",()=>{for(const [id,level]of Object.entries({prayer:3,martyr:7,faith:6,divineWard:8,gracefulStep:10}))check(G.data.ABILITIES[id].level===level);});
  test("WIZARD PREREQUISITE PERSONAL MAGE FIVE",()=>{const u=unit();check(!P.availability(u,"wizard").allowed);P.earn(u,"mage",700);check(P.availability(u,"wizard").allowed);check(G.data.CLASSES.wizard.movModifier===0);});
  test("WIZARD STAFF ROBE PERMISSIONS",()=>{const E=G.campaign.EquipmentEligibility,u=unit();check(E.allows(u,{equipmentSlot:"weapon",weaponFamily:"STAFF"}));check(E.allows(u,{equipmentSlot:"armor",armorFamily:"ROBE"}));check(!E.allows(u,{equipmentSlot:"weapon",weaponFamily:"WAND"}));});
  for(const [method,range,radius,amount,mp]of [["extend",5,2,10,22],["focus",4,1,17.5,25],["expand",4,3,10,30],["overcharge",4,2,20,50]])test(method.toUpperCase()+" CHANGES ONLY SPECIFIED CAST FIELDS",()=>{const u=caster(),s=M.resolve(u,"blaze2",method,options("blaze2"));check(s.castingRange===range&&s.effectRadius===radius&&s.magnitude.amount===amount&&s.paidMpCost===mp&&s.owningClassId==="mage"&&s.innateRadius===2);check(G.data.SPELLS.blaze2.effectRadius===2);});
  test("FOCUS REQUIRES INNATE AREA",()=>reject(()=>M.resolve(caster(),"blaze1","focus",options("blaze1"))));
  test("MODIFIERS CANNOT STACK",()=>reject(()=>M.resolve(caster(),"blaze2",["extend","expand"],options("blaze2"))));
  test("BOTH PRIMARY SECONDARY ARRANGEMENTS ALLOW MAGE MODIFIERS",()=>{for(const [cl,secondary]of [["mage","wizard"],["wizard","mage"]])check(M.resolve(caster(cl,secondary),"torrent3","expand",options("torrent3")).effectRadius===3);});
  test("UNPURCHASED MODIFIER OR INACCESSIBLE WIZARD REJECTS",()=>{const u=caster();u.learnedAbilityIds=u.learnedAbilityIds.filter(id=>id!=="extend");reject(()=>M.resolve(u,"blaze1","extend",options("blaze1")));u.currentClassId="fighter";reject(()=>M.resolve(u,"blaze2","expand",options("blaze2")));});
  test("WIZARD MODIFIER GENERATES NO SEPARATE CP",()=>{same(P.attribution(caster(),"extend",9),{});same(P.attribution(caster(),"blaze2",9),{wizard:5,mage:4});});
  test("CAST MODIFIER UI NO DUPLICATE MAGIC COMMANDS",()=>{const groups=G.systems.ActionCommandSystem.categories(caster(),G.systems.TurnSystem.start(5));check(groups.filter(g=>g.command==="MAGIC").length===1);check(!groups.flatMap(g=>g.abilities||[]).some(a=>a.abilityId==="extend"));});
  test("DIVINE ARCANA AUTHORIZES HEAL MAGNITUDE MODIFICATION",()=>{const u=caster("wizard","cleric");reject(()=>M.resolve(u,"heal2","focus",options("heal2")));equip(u,"divineArcana");const s=M.resolve(u,"heal2","focus",options("heal2"));check(s.restoresHp&&!s.dealsDamage&&s.magnitude.amount===17.5&&s.effectRadius===1&&s.owningClassId==="cleric");});
  test("ARCANA SUPPORT EXCLUSIVE AND FUTURE CLASS GROUPS DATA ONLY",()=>{const u=caster("wizard","cleric");equip(u,"divineArcana");check(M.compatible(u,M.definition("heal2",balance("heal2")),"expand"));equip(u,"hexArcana");check(!M.compatible(u,M.definition("heal2",balance("heal2")),"expand"));check(!G.data.CLASSES.hexer&&!G.data.CLASSES.enchanter);});
  test("FRACTIONAL MP CENTRAL ROUNDING STAYS UNRESOLVED",()=>{check(G.config.SPELLS.rounding===null);reject(()=>M.resolve(caster(),"blaze1","extend",{balance:balance("blaze1",{mpCost:7})}));check(M.resolve(caster(),"blaze1","extend",{balance:balance("blaze1",{mpCost:7}),rounding:Math.ceil}).mpCost===8);});
  test("UNRESOLVED SPELL CAST IS ATOMIC",()=>{const b=battle(),before=copy(b.state);reject(()=>b.cast("a","blaze1",null,{x:3,y:2}));same(b.state,before);});
  test("SPELL DAMAGE MP AND UNDERLYING CP RECEIPT EXECUTE",()=>{const b=battle(),r=b.cast("a","quake1","overcharge",{x:3,y:2},{...options("quake1"),cpCalculator:{calculate:()=>7}});check(b.state.units.b.tactical.hp===80&&b.state.units.a.tactical.mp===50);same(r.cp.recipients,{wizard:4,mage:3});check(b.state.actionRecords.length===1);});
  test("CAST INSUFFICIENT MP AND RANGE REJECT ATOMICALLY",()=>{const b=battle(),before=copy(b.state);reject(()=>b.cast("a","blaze1",null,{x:11,y:11},options("blaze1")));same(b.state,before);reject(()=>b.cast("a","blaze1",null,{x:3,y:2},{...terrain,balance:balance("blaze1",{mpCost:101})}));same(b.state,before);});
  function counterWorld(){const u=equip(caster(),"spellCounter");return battle([u,unit("b","ZEON","fighter")]);}
  test("SPELL COUNTER TWENTY PERCENT ZERO MP FIRST EXCLUDES NORMAL",()=>{const b=counterWorld();let normal=0;const r=b.resolveCounters("a","b",{attackId:"trigger1",...options("blaze1"),canCounter:true,spellEligible:s=>s.id==="blaze1",selectSpell:()=>"blaze1",roll:()=>0.19,normalCounter:()=>{normal++;return true;}});const castResult=b.chooseCounter("blaze1",options("blaze1"));check(r.kind==="SPELL_SELECTION"&&normal===0&&b.state.units.a.tactical.mp===100&&b.state.units.b.tactical.hp===90);check(castResult.cp.status==="REACTION_NO_CP"&&!b.state.turns.a.majorUsed);});
  test("SPELL COUNTER FAILURE PROCEEDS TO NORMAL ONCE",()=>{const b=counterWorld();let normal=0;const r=C.counters(b.state,"a","b",{canCounter:true,spellEligible:()=>true,roll:()=>0.2,normalCounter:()=>{normal++;return true;}});check(r.kind==="NORMAL"&&normal===1);});
  test("SPELL COUNTER NO PURCHASE DOES NOT GRANT SPELLS",()=>{const u=equip(unit(),"spellCounter"),b=battle([u,unit("b","ZEON")]);const r=C.counters(b.state,"a","b",{canCounter:true,spellEligible:()=>true,roll:()=>{throw Error("must not roll");},normalCounter:()=>true});check(r.kind==="NORMAL");});
  test("PLAYER COUNTER REQUIRES EXPLICIT CHOICE",()=>{const b=counterWorld();check(C.counters(b.state,"a","b",{canCounter:true,spellEligible:()=>true,roll:()=>0}).kind==="SPELL_SELECTION");});
  test("DYING CANNOT COUNTER OR REACT",()=>{const b=counterWorld();b.damage("a",100);check(C.counters(b.state,"a","b",{canCounter:true,roll:()=>{throw Error("no roll");}}).kind==="NONE");same(L.effects(b.state.units.a,"spellCounter"),[]);});
  test("ARCANE SIPHON USES PAID MODIFIED MP AND DAMAGE X POINT NINE",()=>{const b=battle([equip(unit(),"arcaneSiphon"),unit("b","ZEON")]);b.command(s=>s.units.a.tactical.mp=20);b.damage("a",50,{cast:{dealsDamage:true,paidMpCost:30}});check(b.state.units.a.tactical.hp===55&&b.state.units.a.tactical.mp===50);});
  test("ARCANE SIPHON IGNORES PHYSICAL DAMAGE",()=>{const b=battle([equip(unit(),"arcaneSiphon"),unit("b","ZEON")]);b.command(s=>s.units.a.tactical.mp=20);b.damage("a",50);check(b.state.units.a.tactical.hp===50&&b.state.units.a.tactical.mp===20);});
  for(const [cl,support,key,bonus]of [["cleric","faith","wis",1],["wizard","intelligenceTraining","int",2]])test(support.toUpperCase()+" FUTURE GROWTH ONLY",()=>{const u=unit("a","PLAYER",cl),before=copy(u.basePrimary),plain=copy(u);equip(u,support);same(u.basePrimary,before);F.advanceLevel(u);F.advanceLevel(plain);check(u.basePrimary[key]===plain.basePrimary[key]+bonus);same(u.growthRngState,plain.growthRngState);});
  for(const [cl,key,bonus]of [["mage","int",1],["cleric","wis",1],["wizard","int",2]])test(cl.toUpperCase()+" FIXED GROWTH",()=>{const u=unit("a","PLAYER",cl),plain=copy(u);F.advanceLevel(u);F.advanceLevel(plain,{getGrowth:()=>({})});check(u.basePrimary[key]===plain.basePrimary[key]+bonus);});
  for(const [ability,resource]of [["gracefulStep","hp"],["manaStep","mp"]])test(ability.toUpperCase()+" FIRST COMPLETED MOVEMENT NOT STILL",()=>{const b=battle([equip(unit(),ability),unit("b","ZEON")]);b.command(s=>s.units.a.tactical[resource]=40);b.move("a",[],terrain);check(b.state.units.a.tactical[resource]===40);b.move("a",[[0,1]],terrain);check(b.state.units.a.tactical[resource]===45);b.move("a",[[0,1]],terrain);check(b.state.units.a.tactical[resource]===45);b.endTurn("a");b.startTurn("a");b.move("a",[[0,-1]],terrain);check(b.state.units.a.tactical[resource]===50);});
  test("GRACEFUL STEP ROUNDING UNRESOLVED IS ATOMIC",()=>{const b=battle([equip(unit(),"gracefulStep"),unit("b","ZEON")]);b.command(s=>{s.units.a.tactical.maxHp=101;s.units.a.tactical.hp=30;});const before=copy(b.state);reject(()=>b.move("a",[[0,1]],terrain));same(b.state,before);});
  for(const faction of ["PLAYER","ZEON"])test(faction+" ZERO HP DYING OWN TURN COUNTDOWN REMOVES MAP AND ROSTER",()=>{const b=ongoingBattle(),id=faction==="PLAYER"?"a":"b";b.damage(id,100);check(b.state.units[id].tactical.life==="DYING"&&b.state.units[id].tactical.dyingCounter===3&&b.state.positions[id]);for(const count of [2,1,0]){b.startTurn(id);check(b.state.units[id].tactical.dyingCounter===count);b.endTurn(id);}check(b.state.units[id].tactical.life==="DEAD"&&!b.state.positions[id]);check(!Object.values(b.state.rosters).some(q=>q.unitIds.includes(id)));});
  test("DYING ACTIONS MOVEMENT ORDINARY TARGETS AND AOE EXCLUDED",()=>{const b=ongoingBattle();b.damage("b",100);const before=copy(b.state);reject(()=>b.move("b",[[0,1]],terrain));same(b.state,before);check(!G.systems.TurnSystem.availability(b.state.turns.b,"ATTACK").allowed);check(!T.unitAllowed(b.state.units.a,b.state.units.b,G.data.SPELLS.blaze2));check(T.affectedUnits(b.state,b.state.units.a,G.data.SPELLS.blaze2,{x:3,y:2}).every(u=>u.id!=="b"));check(T.affectedUnits(b.state,b.state.units.a,G.data.SPELLS.blaze2,{x:3,y:2}).some(u=>u.id==="a"));});
  test("BOTH SIDES PASS THROUGH DYING TILE BUT CANNOT STOP",()=>{const b=ongoingBattle();b.damage("b",100);reject(()=>b.move("a",[[1,0]],terrain));b.move("a",[[1,0],[1,0]],terrain);check(b.state.positions.a.x===4&&b.state.positions.b.x===3);});
  test("RAISE HALF MAX HP CLEAR COUNTER NOT DEAD",()=>{const b=ongoingBattle();b.damage("b",100);b.command(s=>B.raise(s.units.b));check(b.state.units.b.tactical.hp===50&&b.state.units.b.tactical.life==="ALIVE"&&b.state.units.b.tactical.dyingCounter===null);b.damage("b",100);for(let n=0;n<3;n++){b.startTurn("b");b.endTurn("b");}reject(()=>b.command(s=>B.raise(s.units.b)));});
  test("DIVINE ARCANA EXPANDED RAISE AFFECTS MULTIPLE DYING ALLIES",()=>{const u=equip(caster("wizard","cleric"),"divineArcana"),b=battle([u,unit("b","PLAYER"),unit("c","PLAYER"),unit("enemy","ZEON")],{a:{x:2,y:2},b:{x:3,y:2},c:{x:4,y:2},enemy:{x:10,y:10}});b.damage("b",100);b.damage("c",100);const result=b.cast("a","raise1","expand",{x:3,y:2},{...terrain,balance:balance("raise1",{effectRadius:1}),rounding:Math.ceil});same(result.affectedUnitIds,["b","c"]);check(b.state.units.b.tactical.hp===50&&b.state.units.c.tactical.hp===50&&result.cast.owningClassId==="cleric");});
  test("PRAYER PREVENTS DYING BUT KEEPS POISON",()=>{const b=battle([equip(unit(),"prayer"),unit("b","PLAYER"),unit("e","ZEON")],{a:{x:2,y:2},b:{x:3,y:2},e:{x:9,y:9}});b.command(s=>s.units.b.tactical.statuses=[{id:"POISON"}]);b.damage("b",100,{prayerDecision:()=>true});check(b.state.units.b.tactical.hp===1&&b.state.units.b.tactical.life==="ALIVE"&&b.state.units.b.tactical.statuses[0].id==="POISON");b.damage("b",1,{prayerDecision:()=>false});check(b.state.units.b.tactical.life==="DYING");});
  test("PRAYER NOT SELF OR DISTANT FRIENDLY",()=>{const b=battle([equip(unit(),"prayer"),unit("b","PLAYER"),unit("e","ZEON")],{a:{x:2,y:2},b:{x:5,y:2},e:{x:9,y:9}});b.damage("b",100);check(b.state.units.b.tactical.life==="DYING");b.damage("a",100);check(b.state.units.a.tactical.life==="DYING");});
  test("MARTYR EACH NEW ENEMY DYING ENTRY ONLY",()=>{const b=ongoingBattle([equip(unit(),"martyr"),unit("b","ZEON")]);b.damage("b",100);check(b.state.units.b.tactical.dyingCounter===2);b.startTurn("b");check(b.state.units.b.tactical.dyingCounter===1);b.command(s=>B.raise(s.units.b));b.damage("b",100);check(b.state.units.b.tactical.dyingCounter===2);});
  test("DIVINE WARD DAMAGE THIRTY PERCENT",()=>{const b=battle([equip(unit(),"divineWard"),unit("b","ZEON")]);b.damage("a",50,{cast:{dealsDamage:true,paidMpCost:10}});check(b.state.units.a.tactical.hp===65);});
  for(const [chance,expected]of [[0.5,0.2],[0.3,0],[0.2,0]])test("DIVINE WARD STATUS "+chance+" MINUS FLAT THIRTY POINTS",()=>check(Math.abs(B.statusChance(equip(unit(),"divineWard"),chance)-expected)<1e-9));
  test("FLY EXPAND ONLY COMPATIBILITY",()=>{const u=caster();check(M.resolve(u,"fly","expand",options("fly")).effectRadius===3);for(const method of ["extend","focus","overcharge"])reject(()=>M.resolve(u,"fly",method,options("fly")));});
  test("FLY TRAVERSAL OCCUPANCY COST ONE ON IMPASSABLE TERRAIN",()=>{const b=battle();b.command(s=>s.units.a.tactical.statuses=[{id:"FLYING",duration:3}]);const before=b.state.turns.a.remainingMov;b.move("a",[[0,1],[0,1]],{...terrain,canEnter:()=>false,cost:()=>99});check(b.state.positions.a.y===4&&b.state.turns.a.remainingMov===before-2);reject(()=>b.move("a",[[0,1]],{...terrain,inBounds:()=>false}));});
  test("FLY CAST ADDS STATUS AND EXPLICIT EXPIRY REMOVES IT",()=>{const b=battle();b.cast("a","fly",null,{x:2,y:2},options("fly"));check(B.flying(b.state.units.a));b.expireStatus("a","FLYING",terrain);check(!B.flying(b.state.units.a));});
  const portalCast=(b,ends,method=null)=>b.cast("a","portal",method,ends,options("portal"));
  test("PORTAL BASE AND EXTEND KEEP SINGLE TILE RADIUS",()=>{const u=caster(),normal=M.resolve(u,"portal",null,options("portal")),ext=M.resolve(u,"portal","extend",options("portal"));check(normal.castingRange===4&&ext.castingRange===5&&ext.effectRadius===1);for(const m of ["focus","expand","overcharge"])reject(()=>M.resolve(u,"portal",m,options("portal")));});
  test("PORTAL TWO DISTINCT ENDPOINTS EACH IN RANGE",()=>{for(const endpoints of [[{x:2,y:2}],[{x:2,y:2},{x:2,y:2}],[{x:2,y:3},{x:9,y:2}]]){const b=battle(),before=copy(b.state);reject(()=>portalCast(b,endpoints));same(b.state,before);}});
  for(const order of [false,true])test("PORTAL OWN TILE FORCED TRANSFER ORDER "+order,()=>{const b=battle(),ends=[{x:2,y:2},{x:2,y:5}];portalCast(b,order?ends.reverse():ends);same(b.state.positions.a,{x:2,y:5});});
  test("PORTAL CAST TWO OCCUPANTS SWAPS BOTH",()=>{const b=battle();portalCast(b,[{x:2,y:2},{x:3,y:2}]);same(b.state.positions.a,{x:3,y:2});same(b.state.positions.b,{x:2,y:2});});
  test("PORTAL FORCE MOVES DYING AND RESTRICTED WITHOUT CURING",()=>{const b=ongoingBattle();b.command(s=>s.units.b.tactical.statuses=[{id:"FROZEN"},{id:"IMMOBILIZED"}]);b.damage("b",100);const before=copy(b.state.units.b.tactical);portalCast(b,[{x:3,y:2},{x:2,y:4}]);same(b.state.positions.b,{x:2,y:4});same(b.state.units.b.tactical,before);});
  test("PORTAL OCCUPIED TERRAIN EXCEPTION ONLY",()=>{const b=battle();b.cast("a","portal",null,[{x:2,y:2},{x:3,y:2}],{...options("portal"),occupiable:()=>false});check(Object.keys(b.state.portals).length===1);const c=battle();reject(()=>c.cast("a","portal",null,[{x:2,y:3},{x:3,y:3}],{...options("portal"),occupiable:()=>false}));});
  test("PORTAL RECAST REPLACES ONLY OWNER MULTIPLE PAIRS COEXIST",()=>{const u=learn(unit("c","PLAYER","wizard"),"portal"),b=battle([caster(),unit("b","ZEON"),u],{a:{x:2,y:2},b:{x:3,y:2},c:{x:7,y:7}});portalCast(b,[{x:2,y:3},{x:2,y:4}]);b.cast("c","portal",null,[{x:7,y:6},{x:7,y:5}],options("portal"));const other=copy(b.state.portals.c);b.endTurn("a");b.startTurn("a");portalCast(b,[{x:1,y:2},{x:1,y:3}]);same(b.state.portals.c,other);check(Object.keys(b.state.portals).length===2&&b.state.portals.a.endpoints[0].x===1);});
  test("PORTAL CANNOT OVERLAP ANOTHER CASTER PORTAL",()=>{const b=battle([caster(),learn(unit("b","ZEON"),"portal")]);b.cast("b","portal",null,[{x:2,y:3},{x:2,y:4}],options("portal"));const before=copy(b.state);reject(()=>portalCast(b,[{x:2,y:3},{x:1,y:3}]));same(b.state,before);});
  test("PORTAL CASTING TURN SKIPPED THEN THREE OWNER EXPIRATIONS",()=>{const b=battle();portalCast(b,[{x:2,y:3},{x:2,y:4}]);b.endTurn("a");check(b.state.portals.a.remaining===3);b.startTurn("b");b.endTurn("b");check(b.state.portals.a.remaining===3);for(const n of [2,1,0]){b.startTurn("a");b.endTurn("a");check(n?b.state.portals.a.remaining===n:!b.state.portals.a);}});
  test("ENTER PORTAL PRESERVES MOV AND MAJOR THEN CONTINUE MOVING",()=>{const b=battle();portalCast(b,[{x:2,y:3},{x:2,y:5}]);b.startTurn("a");b.move("a",[[0,1]],terrain);const turn=copy(b.state.turns.a);check(b.commands("a").some(c=>c.command==="ENTER PORTAL"));b.enterPortal("a");same(b.state.turns.a,turn);same(b.state.positions.a,{x:2,y:5});b.move("a",[[0,1]],terrain);check(b.state.positions.a.y===6&&!b.state.turns.a.majorUsed);});
  test("PORTAL ENEMY VOLUNTARY USE AND OCCUPIED DESTINATION REJECT",()=>{const b=battle();portalCast(b,[{x:2,y:3},{x:2,y:5}]);b.command(s=>{s.positions.b={x:2,y:3};});check(!Portal.availability(b.state,"b").allowed);b.command(s=>{s.positions.a={x:2,y:3};s.positions.b={x:2,y:5};});check(!Portal.availability(b.state,"a").allowed);});
  test("PORTAL HIGHLIGHT ONLY CURSOR OR CONTROLLED ACTIVE INTERACTION",()=>{const b=battle();portalCast(b,[{x:2,y:3},{x:2,y:5}]);b.command(s=>{s.positions.a={x:2,y:3};s.controlledUnitId="a";});const p=b.state.portals.a;check(!Portal.highlighted(b.state,p,null,null));check(Portal.highlighted(b.state,p,{x:2,y:5},null));check(Portal.highlighted(b.state,p,null,{active:true,unitId:"a"}));check(!Portal.highlighted(b.state,p,null,{active:true,unitId:"b"}));});
  test("FINAL ZERO HP QUEUES CONCLUSION BEFORE DYING COUNTDOWN",()=>{const b=battle();b.damage("b",100);check(b.state.presentation.pendingWinner==="PLAYER"&&b.state.presentation.phase==="ANIMATION"&&b.state.units.b.tactical.dyingCounter===3);check(b.state.presentation.banner===null);b.animationComplete();check(b.state.presentation.phase==="MAP_RETURN"&&b.state.presentation.banner===null);b.mapRendered();check(b.state.presentation.banner==="VICTORY");});
  test("FINAL PLAYER ZERO HP DISPLAYS DEFEAT",()=>{const b=battle();b.damage("a",100);b.animationComplete();b.mapRendered();check(b.state.presentation.banner==="DEFEAT");});
  test("REAL ANIMATION PLAYER FINISHES BEFORE MAP RETURN",()=>{const b=battle();b.damage("b",100);b.playAnimation({frames:2,durations:[10,10],loop:false},()=>{});b.update(10);check(b.state.presentation.phase==="ANIMATION");b.update(10);check(b.state.presentation.phase==="MAP_RETURN");});
  test("DEATH RATTLE IS NOT IMPLEMENTED",()=>check(!G.data.ABILITIES.deathRattle));
  test("SCHEMA SIX MIGRATES WITHOUT CHANGING CHARACTERS",()=>{const c=G.campaign.createDemo(),old=c.snapshot();old.schemaVersion=6;const n=new G.campaign.Campaign(c.definitions,old);check(n.state.schemaVersion===8);same(n.state.units,old.units);same(n.state.recruitPools,old.recruitPools);});
  test("BATTLE DEAD ROSTER PERSISTS THROUGH RESOLUTION AND RESTORE",()=>{const c=G.campaign.createDemo();c.loadDevelopmentScenario("multiple");c.endDay();let pending=c.state.resolution.pendingBattleScenario,dead=pending.participants.find(p=>p.faction==="PLAYER").unitIds[1];check(!!dead);c.applyBattleResult({...G.campaign.PlaceholderBattleResolver.result(pending,"PLAYER"),deadUnitIds:[dead]});let restored=new G.campaign.Campaign(c.definitions,c.snapshot());while(restored.state.phase!=="PLANNING"){pending=restored.state.resolution.pendingBattleScenario;if(pending)restored.applyBattleResult(G.campaign.PlaceholderBattleResolver.result(pending,"PLAYER"));else restored.stepResolution();}check(restored.state.units[dead].status==="DEAD"&&!Object.values(restored.state.squads).some(q=>q.unitIds.includes(dead)));same(new G.campaign.Campaign(restored.definitions,restored.snapshot()).state,restored.state);});
  test("REAL SCHEMA SIX POST REFRESH PRESERVES OLD MAGE ROLLS",()=>{const oldGrowth=G.data.CLASSES.mage.growth;let snapshot,definitions;try{G.data.CLASSES.mage.growth=null;const initial=G.campaign.createDemo(),s=initial.snapshot();s.day=7;for(const u of Object.values(s.units))u.characterLevel=10;const c=new G.campaign.Campaign(initial.definitions,s);c.startEndDay();while(c.state.phase!=="DAY_ADVANCE"){if(c.state.resolution.pendingBattleScenario)c.applyBattleResult(G.campaign.PlaceholderBattleResolver.result(c.state.resolution.pendingBattleScenario,"PLAYER"));else c.stepResolution();}snapshot=c.snapshot();snapshot.schemaVersion=6;definitions=c.definitions;}finally{G.data.CLASSES.mage.growth=oldGrowth;}const restored=new G.campaign.Campaign(definitions,snapshot);same(restored.state.recruitPools,snapshot.recruitPools);check(restored.state.resolution.legacyRecruitGrowth===true);restored.stepResolution();check(restored.state.day===8);});
  test("DYING CANNOT GENERATE CP OR RECEIVE ITEMS OR TRADE",()=>{const b=battle();b.damage("a",100);reject(()=>b.resolveActionCP("a",{executionId:"illegal",command:"ATTACK",legal:true,executed:true},{calculate:()=>7}));check(G.systems.TradeSystem.targets(b.state,"a",b.state.positions).length===0);same(G.systems.ItemSystem.effects(b.state.units.a,{effects:[{handler:"active"}]}),[]);});
  test("FINAL ZERO BLOCKS NEW TURNS WITHOUT WAITING FOR DYING",()=>{const b=battle();b.damage("b",100);const before=copy(b.state);reject(()=>b.startTurn("b"));reject(()=>b.move("a",[[0,1]],terrain));same(b.state,before);});
  test("COUNTER TRIGGER CANNOT PRODUCE A SECOND OPPORTUNITY",()=>{const b=counterWorld(),ctx={attackId:"sameAttack",canCounter:true,spellEligible:()=>false,normalCounter:()=>true};check(b.resolveCounters("a","b",ctx).kind==="NORMAL");const before=copy(b.state);reject(()=>b.resolveCounters("a","b",ctx));same(b.state,before);});
  test("ORDINARY CAST CANNOT CLAIM FREE REACTION COST",()=>{const b=battle();reject(()=>b.cast("a","blaze1",null,{x:3,y:2},{...options("blaze1"),counter:true}));});
  test("CURATIVE SPELL REMOVES ONLY DECLARED CONDITION",()=>{const b=battle([caster("wizard","cleric"),unit("b","PLAYER"),unit("e","ZEON")],{a:{x:2,y:2},b:{x:3,y:2},e:{x:8,y:8}});b.command(s=>s.units.b.tactical.statuses=[{id:"POISON"},{id:"BLIND"}]);b.cast("a","detox",null,{x:3,y:2},options("detox"));same(b.state.units.b.tactical.statuses,[{id:"BLIND"}]);});
  test("REPLACING OWN PORTAL CAN REUSE ITS VACATED ENDPOINT",()=>{const b=battle();portalCast(b,[{x:2,y:3},{x:2,y:4}]);b.startTurn("a");portalCast(b,[{x:2,y:3},{x:1,y:3}]);check(Object.keys(b.state.portals).length===1&&b.state.portals.a.endpoints[1].x===1);});
  test("FOCUS CHECKS INNATE RADIUS EVEN ON AN EXPANDED CAST",()=>{const u=caster(),expanded=M.resolve(u,"blaze1","expand",options("blaze1"));check(expanded.effectRadius===2&&!M.compatible(u,expanded,"focus"));});
  return out;
 };
}(window.GBTRPG));
